demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstSpringmvcIntf.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestResponse.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
=> [SCB-1896]improve demo test case for testing http headers

demo/demo-local-registry/README.md, demo/demo-local-registry/demo-local-registry-client/pom.xml, demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/registry/Application.java, demo/demo-local-registry/demo-local-registry-client/src/main/resources/application.yml, demo/demo-local-registry/demo-local-registry-client/src/main/resources/logback.xml, demo/demo-local-registry/demo-local-registry-client/src/main/resources/microservices/demo-local-registry-server/ServerEndpoint.yaml, demo/demo-local-registry/demo-local-registry-client/src/main/resources/registry.yaml, demo/demo-local-registry/demo-local-registry-client/src/test/java/org/apache/servicecomb/demo/registry/LocalRegistryIT.java, demo/demo-local-registry/demo-local-registry-server/pom.xml, demo/demo-local-registry/demo-local-registry-server/src/main/java/org/apache/servicecomb/demo/registry/ServerApplication.java, demo/demo-local-registry/demo-local-registry-server/src/main/java/org/apache/servicecomb/demo/registry/ServerEndpoint.java, demo/demo-local-registry/demo-local-registry-server/src/main/resources/application.yml, demo/demo-local-registry/demo-local-registry-server/src/main/resources/logback.xml, demo/demo-local-registry/pom.xml, demo/demo-register-url-prefix/README.md, demo/docker-run-config-local/pom.xml, demo/pom.xml, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/ServiceRegistryFactory.java
=> [SCB-1911]add integration tests for local registry discovery

service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigRegistryApplicationListener.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigRegistryConstants.java
=> [SCB-1922]Use DynamicPropertyFacotry way to read environment variables

core/src/main/java/org/apache/servicecomb/core/definition/ServiceRegistryListener.java, demo/demo-multi-registries/demo-multi-registries-client/src/main/java/org/apache/servicecomb/demo/registry/IServerEndpoint.java, demo/demo-multi-registries/demo-multi-registries-client/src/main/java/org/apache/servicecomb/demo/registry/SchemaDiscoveryTestCase.java, demo/demo-multi-registries/pom.xml, demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CategorizedTestCaseRunner.java, dependencies/bom/pom.xml, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/Discovery.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/Registration.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/cache/MicroserviceInstanceCache.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/swagger/SwaggerLoader.java, service-registry/pom.xml, service-registry/registry-local/pom.xml, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalDiscovery.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, service-registry/registry-schema-discovery/pom.xml, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscoveryEndpoint.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscoveryService.java, service-registry/registry-schema-discovery/src/main/resources/META-INF/services/org.apache.servicecomb.registry.api.Discovery, service-registry/registry-schema-discovery/src/main/resources/microservice.yaml, service-registry/registry-service-center/pom.xml, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/swagger/TestSwaggerLoader.java
=> [SCB-1650]discovery schema from instancies directly

demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/Application.java, demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/CodeFirstService.java, demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/LocalRegistryServerTest.java, demo/demo-local-registry/demo-local-registry-client/src/main/resources/registry.yaml, demo/demo-local-registry/demo-local-registry-server/src/main/java/org/apache/servicecomb/demo/localRegistryServer/CodeFirstEndpoint.java, demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CategorizedTestCaseRunner.java
=> [SCB-1958]local registry support register `code first schema` for microservices

core/src/main/java/org/apache/servicecomb/core/definition/ServiceRegistryListener.java, core/src/main/java/org/apache/servicecomb/core/registry/discovery/OperationInstancesDiscoveryFilter.java, demo/demo-edge/consumer/src/main/resources/microservice.yaml, demo/demo-edge/pom.xml, integration-tests/jaxrs-tests/src/test/resources/microservice.yaml, integration-tests/pojo-test/src/test/resources/microservice.yaml, integration-tests/spring-jaxrs-tests/src/test/resources/microservice.yaml, integration-tests/spring-pojo-connection-limit-test/src/test/resources/microservice.yaml, integration-tests/spring-pojo-tests/src/test/resources/microservice.yaml, integration-tests/springmvc-tests/connection-limit/src/test/resources/microservice.yaml, integration-tests/springmvc-tests/general-with-springboot/src/test/resources/microservice.yaml, integration-tests/springmvc-tests/general/src/test/resources/microservice.yaml, integration-tests/springmvc-tests/simplified-mapping-with-springboot/src/test/resources/microservice.yaml, integration-tests/springmvc-tests/simplified-mapping/src/test/resources/microservice.yaml, integration-tests/tracing-tests/src/test/resources/microservice.yaml, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/Const.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalDiscovery.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistration.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/Const.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterRegistration.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java
=> [SCB-1957]local and service-center Discovery and Registration must enabled together

service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/client/ClientUtil.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/client/ZeroConfigClient.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/client/ZeroConfigRegistryClientImpl.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ServerUtil.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ZeroConfigRegistryService.java, service-registry/registry-zero-config/src/test/java/org/apache/servicecomb/zeroconfig/client/TestZeroConfigClient.java, service-registry/registry-zero-config/src/test/java/org/apache/servicecomb/zeroconfig/client/TestZeroConfigRegistryClientImpl.java, service-registry/registry-zero-config/src/test/java/org/apache/servicecomb/zeroconfig/server/TestZeroConfigRegistryService.java
=> [SCB-1971] minor change to fix an issue

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java, demo/demo-zeroconfig-schemadiscovery-registry/README.md, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/ClientApplication.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/pom.xml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/src/main/java/org/apache/servicecomb/demo/zeroconfig/edge/EdgeApplication.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/src/main/java/org/apache/servicecomb/demo/zeroconfig/edge/SelfServiceInvoker.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/src/main/java/org/apache/servicecomb/demo/zeroconfig/edge/ServerEndpoint.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/src/main/resources/application.yml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/src/main/resources/logback.xml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/pom.xml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/ServerTest.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/resources/microservices/demo-zeroconfig-schemadiscovery-registry-edge/ClientServerEndpoint.yaml, demo/demo-zeroconfig-schemadiscovery-registry/pom.xml, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterHttpClientOptionsSPI.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/ConfigKieHttpClientOptionsSPI.java, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocation.java, foundations/foundation-registry/pom.xml, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/AppManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceManager.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/executor/SinglePoolBlockingExecutor.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/executor/VertxContextExecutor.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RegistryHttpClientOptionsSPI.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RegistryWatchHttpClientOptionsSPI.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayTransport.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/Http2TransportHttpClientOptionsSPI.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/HttpTransportHttpClientOptionsSPI.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestTransport.java
=> [SCB-2000]schema discovery working in edge service

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscoveryService.java
=> [SCB-1999]loadbalance handler support read endpoint from invocation

dependencies/default/pom.xml
=> [SCB-2010]dependency update: upgrade swagger-core from 1.5.22 to 1.5.24

dependencies/default/pom.xml
=> [SCB-2005]dependency update: upgrade slf4j from 1.7.26 to 1.7.30

service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ServerUtil.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ZeroConfigRegistryService.java
=> [SCB-2016]Tiny logging improvement

dependencies/default/pom.xml, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientPoolFactory.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
=> [SCB-2014]dependency update: upgrade vert.x from 3.8.3 to 3.8.5

dependencies/default/pom.xml
=> [SCB-2015]remove not used dependency management for jedis

demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/LocalRegistryServerTest.java, demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/RegistryBeansConfiguration.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/RegistryBean.java
=> [SCB-1991]local registration given an easier way to register schema

dependencies/default/pom.xml, handlers/handler-tracing-zipkin/pom.xml, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/TracingConfiguration.java, integration-tests/test-common/pom.xml, tracing/tracing-zipkin/pom.xml
=> [SCB-1945] support zipkin with log4j2

dependencies/default/pom.xml
=> [SCB-2018]dependency update: upgrade tcnative from 2.0.28 to 2.0.31

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/internal/converter/SwaggerToProtoGenerator.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/internal/converter/TestSwaggerToProtoGenerator.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestWeakSpringmvc.java
=> [SCB-2017]fix invoke with appid and highway throw error

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/ConsumerTestsAfterBootup.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringMVCSchema.java, demo/demo-springmvc/springmvc-client/src/main/resources/SpringMVCSchema.yaml, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/AnnotationUtils.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/models/ResponseConfig.java
=> [SCB-2020]support @Example to add examples to API

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java, demo/demo-spring-boot-provider/demo-spring-boot-springmvc-client/src/test/java/org/apache/servicecomb/springboot/springmvc/client/SpringmvcClientIT.java, demo/demo-spring-boot-provider/demo-spring-boot-springmvc-server/pom.xml, demo/demo-spring-boot-provider/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/SpringmvcServer.java, demo/demo-spring-boot-provider/demo-spring-boot-springmvc-server/src/main/resources/microservice.yaml
=> [SCB-2024]support not resolve place holder when running in spring boot

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestApiOperationOverride.java, integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ApiOperationJaxrsSchema.java, integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ApiOperationSpringmvcSchema.java, integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ApiOpertionPojoSchema.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/definition/PojoConsumerMeta.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerConsumer.java
=> [SCB-2031] Fix mapping problem between pojo consumer method and provider swagger operation

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieWatcher.java, handlers/handler-router/src/main/java/org/apache/servicecomb/router/cache/RouterRuleCache.java, handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/RouterInvokeFilter.java
=>  [SCB-2036] fix memory leak when router pass header

service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigRegistryConstants.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/client/ClientUtil.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/client/ZeroConfigClient.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ServerMicroserviceInstance.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ServerUtil.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ZeroConfigRegistryService.java, service-registry/registry-zero-config/src/test/java/org/apache/servicecomb/zeroconfig/server/TestZeroConfigRegistryService.java
=> [SCB-2035]Use vertx Json and Pojo to replace own serizalization mechanism

core/src/main/java/org/apache/servicecomb/core/handler/impl/ProducerOperationHandler.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java
=> [SCB-2049]fix trace id logger do not print error message in codes

demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/PojoProducersCustomized.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/RestProducersCutomized.java
=> [SCB-2046]support customize RestProducers and RpcProducers

demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/MyStrategy.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/MyStrategyFactory.java, demo/demo-springmvc/springmvc-server/src/main/resources/META-INF/services/org.apache.servicecomb.qps.strategy.IStrategyFactory, demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/AbstractQpsStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/DefaultStrategyFactory.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/FixedWindowStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/IStrategyFactory.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/StrategyType.java, handlers/handler-flowcontrol-qps/src/main/resources/META-INF/services/org.apache.servicecomb.qps.strategy.IStrategyFactory, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestQpsStrategy.java
(cherry picked from commit eed0e46cf448b0caab1b7211f9780bbd82f55a6b)
---
=> [SCB-2043] flow control support custom / bug fix

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/SchemeInterfaceJaxrs.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestSchemeInterfaceJaxrs.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/SchemeInterfaceJaxrs.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/SchemeInterfaceJaxrsImpl.java, demo/demo-jaxrs/jaxrs-server/src/main/resources/microservice.yaml, demo/demo-jaxrs/pom.xml, swagger/swagger-generator/generator-spring-data/src/main/java/org/apache/servicecomb/swagger/generator/springdata/SpringDataModule.java, swagger/swagger-generator/generator-spring-data/src/test/java/org/apache/servicecomb/swagger/generator/springdata/TestPageResponseTypeProcessor.java
=> [SCB-2053]support define interface or abstract class as model

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestSchemeInterfaceJaxrs.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/SchemeInterfaceJaxrs.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/SchemeInterfaceJaxrsImpl.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayCodec.java
=> [SCB-2047]when ruturn null for primitive type of highway will throw NPE

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/ClientPoolManager.java
=> [SCB-2056]print a verbose log when no registration is configured

core/src/main/java/org/apache/servicecomb/core/executor/GroupExecutor.java, core/src/main/java/org/apache/servicecomb/core/executor/LinkedBlockingQueueEx.java, core/src/main/java/org/apache/servicecomb/core/executor/ThreadPoolExecutorEx.java, core/src/test/java/org/apache/servicecomb/core/executor/TestThreadPoolExecutorEx.java, integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/handler/ExceptionConvertHandler.java
=> [SCB-1753]accessor problem fix: LinkedBlockingQueueEx queue features

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceRegistry.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/InstanceCacheChecker.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/cache/MicroserviceCacheKey.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/TestRegistry.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/TestInstanceCacheCheckerMock.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/registry/EmptyMockServiceRegistry.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/registry/cache/MicroserviceCacheKeyTest.java
=> [SCB-2064]Fix RegistryUtils API not using version rule parameter problem

core/src/main/java/org/apache/servicecomb/core/provider/producer/ProducerProviderManager.java
=> Fix word grammar errors

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/deploy/Deploys.java, integration-tests/it-producer/src/main/resources/microservice.yaml, scripts/build.sh
github using higher version of JDK, for convenient using openssl for ALPN
---
=> [SCB-2068]add github action to RUN PR check

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieUtil.java
=> [SCB-2071] fix kie can not get version level config

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/TryingIsolatedServerMarker.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestConfiguration.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombServerStats.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilterTest.java
Please see the details in https://issues.apache.org/jira/browse/SCB-2077
=> [SCB-2077] fix instance isolation trying chance not released problem

clients/config-center-client/pom.xml, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/AddressManager.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterManager.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterOperation.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigurationChangedEvent.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/exception/OperationException.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/model/QueryConfigurationsRequest.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/model/QueryConfigurationsResponse.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/HttpUtils.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/task/AbstractTask.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/task/Task.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterDiscovery.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java
=> [SCB-2083]provide client api for config center using blocking http client

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/model/QueryConfigurationsRequest.java
=> [SCB-2083]add environment header

core/src/main/java/org/apache/servicecomb/core/invocation/endpoint/EndpointUtils.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/OperationPostProcessor.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/SwaggerGeneratorUtils.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java
=> [SCB-2088] add OperationPostProcessor to swagger generator

huawei-cloud/dtm/src/main/java/org/apache/servicecomb/huaweicloud/dtm/DtmConsumerHandler.java, huawei-cloud/dtm/src/main/java/org/apache/servicecomb/huaweicloud/dtm/DtmProviderHandler.java
=> [SCB-2084] ServiceComb support dtm: fix bug. init hasn't been invoked

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestCodeFirstJaxrs.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java
=> [#1979] add a sample for user issue 1979

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/SchemaInterface.java, demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestSchemeInterface.java, demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/SchemaInterface.java, demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/SchemaInterfaceImpl.java, demo/demo-pojo/pojo-server/src/main/resources/META-INF/spring/pojo.server.bean.xml, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/PojoProducerProvider.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/schema/PojoProducerMeta.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/schema/SchemaDefParser.java, providers/provider-pojo/src/main/resources/META-INF/spring/spring-paas-cse-rpc-1.0.xsd
=> [SCB-2090]rpc-schema xml configuration supports interface schema

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/auth/Cipher.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/auth/DefaultCipher.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/api/request/RbacTokenRequest.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/api/response/RbacTokenResponse.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenAuthHeaderProvider.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/ServiceRegistryClient.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java, service-registry/registry-service-center/src/main/resources/META-INF/services/org.apache.servicecomb.foundation.auth.AuthHeaderProvider, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java
=> [SCB-2089] 支持服务中心rbac认证

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/NetUtils.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java
=> [SCB-2095] support config ipv6 wildcart address

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java
=> [SCB-2100]Solve the problem of not setting keepaliveTimeout, client idleTimeout does not work

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/ReadStreamPart.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpCommon.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpFromPart.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerResponseToHttpServletResponse.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
=> SCB-2102 Fix the problem of unable to return due to abnormal file upload

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestVertxTransportConfig.java, java-chassis-dependencies/default/pom.xml
=> SCB-2103: Upgraded Netty version

dependencies/default/pom.xml, foundations/foundation-common/pom.xml, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/parser/ContentFileReader.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/parser/ProtoParser.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestDefaultHttpClientFilter.java
1、guava 29.0 cache has to dependency failureaccess
2、commons-io 2.8.0 add check filename logic, ContentFileReader#read method change to read from content, loader#load set a default name.
---
=> [SCB-2098] update some 3rd dependencies

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/HttpServerExceptionHandler.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
=> [SCB-2106]add an exception handler for vert.x http server starup failure

handlers/handler-bizkeeper/readme.MD
=> [SCB-2113] fix handler module readme error

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java
=> [SCB-2111]config client do not properly handle service scope

huawei-cloud/environment/README.md
=> [SCB-2115]fix readme format error

core/src/main/java/org/apache/servicecomb/core/registry/discovery/EndpointDiscoveryFilter.java, core/src/test/java/org/apache/servicecomb/core/registry/discovery/TestEndpointDiscoveryFilter.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CustomEndpointDiscoveryFilter.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/AbstractEndpointDiscoveryFilter.java, foundations/foundation-registry/src/test/java/org/apache/servicecomb/registry/discovery/TestAbstractTransportDiscoveryFilter.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServer.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/event/IsolationServerEvent.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/ServerDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceCreator.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombServer.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombServerStats.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestSessionSticknessRule.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilterTest.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/TestServerDiscoveryFilter.java
=> [SCB-2112]isolation recovery should be immediatly after success

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java, core/src/test/java/org/apache/servicecomb/core/TestConfigurationSpringInitializer.java, dynamic-config/config-apollo/src/main/java/org/apache/servicecomb/config/archaius/sources/ApolloConfigurationSourceImpl.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/archaius/sources/ConfigCenterConfigurationSourceImpl.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/archaius/sources/KieConfigurationSourceImpl.java, dynamic-config/config-nacos/src/main/java/org/apache/servicecomb/config/nacos/archaius/sources/NacosConfigurationSourceImpl.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/spi/ConfigCenterConfigurationSourceLoader.java, foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigUtil.java, foundations/foundation-spi/src/main/java/org/apache/servicecomb/foundation/bootstrap/BootStrapService.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalancer.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/TestRegistry.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestMicroServiceInstance.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/registry/TestLocalServiceRegistry.java
=> [SCB-2119]improve config loading process and delete useless methods

demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/SchemeInterfaceJaxrsImpl.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/MessageReadSchema.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerEnvironment.java
=> [SCB-2120]fix operation override when using schema interface

demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITInvoker.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/PojoConsumerMetaRefresher.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/PojoInvocationCreator.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/definition/PojoConsumerMeta.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/definition/PojoConsumerOperationMeta.java, providers/provider-pojo/src/test/java/org/apache/servicecomb/provider/pojo/TestInvoker.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerConsumerOperation.java
=> [SCB-2123] extract meta refresher and invocation creator from Invoker to make read and add new feature easier

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultMethod.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/DefaultMethodMeta.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/utils/MethodUtils.java
=> [SCB-2122] consumer interface support default method

core/src/main/java/org/apache/servicecomb/core/registry/ThirdServiceRegister.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/ThirdSvc.java, demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/StaticMicroserviceVersions.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/registry/ThirdServiceWithInvokerRegister.java
=> [SCB-2125] third service support multi schemas

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/auth/ShaAKSKCipher.java
=> [SCB-2126]ShaAKSKCipher not used

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestClientTimeout.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
=> [SCB-2127]when timeout, will not isolate service

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/archaius/sources/ConfigCenterConfigurationSourceImpl.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/WebsocketClientUtil.java
=> [SCB-2130]vert.x 3.9.4 ping/pong message will call on message

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestQueryParamWithListSchema.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/QueryParamWithListSchema.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
=> [#2081]add a test case for query with List<String>

java-chassis-dependencies/default/pom.xml
=> [SCB-2134]Upgrade tcnative to 2.0.31.Final to obtain arm64 ssl lib

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestEngineSchemaListener.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java, core/src/main/java/org/apache/servicecomb/core/registry/ThirdServiceRegister.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestMaxHttpUrlLength.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/executor/VertxContextExecutor.java, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestVertxTransportConfig.java
=> [SCB-2138] fix 3rd service register problem

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java, transports/transport-rest/transport-rest-client/pom.xml, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/BoundaryFactory.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientExceptionCodes.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientRequestParameters.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientRequestParametersImpl.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContext.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContextFactory.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContextFactoryTest.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestFeatureController.java
=> [SCB-2141] add RestClientTransportContext

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClient.java, demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestFlowControl.java, demo/demo-pojo/pojo-client/src/main/resources/microservice.yaml, demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/FlowControlClientSchema.java, demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/FlowControlSchema.java, demo/demo-pojo/pojo-server/src/main/resources/microservice.yaml, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/Config.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/AbstractQpsStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/DefaultStrategyFactory.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/FixedWindowStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/IStrategyFactory.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/TokenBucketStrategy.java, handlers/handler-flowcontrol-qps/src/main/resources/META-INF/services/org.apache.servicecomb.qps.strategy.IStrategyFactory, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/QpsControllerManagerTest.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConfig.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestQpsStrategy.java
=> [SCB-2135]merge flow control function from 2.1.x to 1.3.x

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientEncoder.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/FakeRestTransport.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientEncoderTest.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientTestBase.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContextFactoryTest.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestFeatureController.java
=> [SCB-2142] add RestClientEncoder

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/YAMLUtil.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/archaius/sources/YAMLConfigLoader.java, java-chassis-dependencies/default/pom.xml, service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
=> [SCB-2145]fix local yaml unsafe parse problem

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientDecoder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientExceptionCodes.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientDecoderTest.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientTestBase.java
=> [SCB-2146] add RestClientDecoder

core/src/main/java/org/apache/servicecomb/core/filter/FilterNode.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/URIEndpointObject.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientEncoder.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilterTest.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientEncoderTest.java
=> [SCB-2147] add RestClientCodecFilter

swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/Response.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContext.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilterTest.java
=> [SCB-2148] add RestClientSender

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/HttpClientRequestFactory.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContextFactory.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContextFactoryTest.java
=> [SCB-2150] allowed modify host before create HttpClientRequest

core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientFilterProvider.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSenderFilter.java
=> [SCB-2149] add RestClientSenderFilter

core/src/main/java/org/apache/servicecomb/core/Invocation.java, core/src/main/java/org/apache/servicecomb/core/definition/InvocationRuntimeType.java, core/src/main/java/org/apache/servicecomb/core/filter/Filter.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/AsyncUtils.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/DownloadUtils.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpCommon.java, integration-tests/test-common/src/test/java/org/apache/servicecomb/tests/tracing/TracingTestBase.java, integration-tests/tracing-tests/src/test/java/org/apache/servicecomb/tests/tracing/TracingTestMain.java, integration-tests/tracing-tests/src/test/java/org/apache/servicecomb/tests/tracing/ZipkinTracingIntegrationTest.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClientFilter.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayFilterProvider.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayTransport.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientDecoder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientEncoder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSenderFilter.java
=> [SCB-2156] add HighwayClientFilter

core/src/main/java/org/apache/servicecomb/core/filter/FilterNode.java, core/src/main/java/org/apache/servicecomb/core/invocation/ProducerInvocationFlow.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/AsyncUtils.java
=> [SCB-2157] enhance AsyncUtils.tryCatch

core/src/main/java/org/apache/servicecomb/core/Invocation.java, core/src/main/java/org/apache/servicecomb/core/filter/FilterChainsManager.java, core/src/main/java/org/apache/servicecomb/core/invocation/InvocationFactory.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, core/src/main/resources/microservice.yaml, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITInvoker.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/FilterInvocationCaller.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/HandlerInvocationCaller.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/InvocationCaller.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/PojoInvocation.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/definition/PojoConsumerOperationMeta.java
=> [SCB-2152] allow pojo invoker process by filter chain

core/src/main/java/org/apache/servicecomb/core/exception/Exceptions.java, core/src/main/java/org/apache/servicecomb/core/exception/converter/DefaultExceptionConverter.java, core/src/main/java/org/apache/servicecomb/core/filter/impl/ProducerOperationFilter.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/FilterInvocationCaller.java
=> [SCB-2158] optimize exception log

core/src/main/java/org/apache/servicecomb/core/exception/converter/TimeoutExceptionConverter.java, core/src/main/resources/META-INF/services/org.apache.servicecomb.core.exception.ExceptionConverter
=> [SCB-2159] add TimeoutExceptionConverter

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java, demo/demo-crossapp/crossapp-client/src/main/java/org/apache/servicecomb/demo/crossapp/CrossappClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestRestTemplate.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseRestTemplate.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseUriTemplateHandler.java
=> [SCB-2074]using servicecomb:// instead of cse://

demo/demo-schema/src/main/java/org/apache/servicecomb/demo/DemoSSLCustom.java, foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/KeyStoreUtil.java, foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLManager.java, foundations/foundation-ssl/src/test/java/org/apache/servicecomb/foundation/ssl/SSLManagerTest.java, foundations/foundation-ssl/src/test/resources/server.ssl.resource.properties, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
=> [SCB-1856]support reading certificates in jar

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestSpringConfiguration.java, integration-tests/it-consumer/src/main/resources/microservice.yaml
=> [SCB-2160] can not resolve list placeholders by environment.getProperty

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClients.java
=> [SCB-2163] tiny code improve

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java
=> [SCB-2174]ignore swagger and method parameter count check

core/src/main/java/org/apache/servicecomb/core/filter/EndpointDiscoveryFilter.java, core/src/test/java/org/apache/servicecomb/core/filter/TestEndpointDiscoveryFilter.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServer.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/event/IsolationServerEvent.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/ServerDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceCreator.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombServer.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombServerStats.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestSessionSticknessRule.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilterTest.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/TestServerDiscoveryFilter.java, java-chassis-spring-boot/spring-boot-starter/spring-boot-starter-discovery/src/main/java/org/apache/servicecomb/springboot/starter/discovery/ScbRibbonEndpointDiscoveryFilter.java, java-chassis-spring-boot/spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/ScbRibbonEndpointDiscoveryFilter.java, service-registry/src/main/java/org/apache/servicecomb/serviceregistry/discovery/AbstractEndpointDiscoveryFilter.java, service-registry/src/test/java/org/apache/servicecomb/serviceregistry/discovery/TestAbstractTransportDiscoveryFilter.java
=> [SCB-2167]isolation recovery should be immediatly after success

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java, foundations/foundation-ssl/src/test/java/org/apache/servicecomb/foundation/ssl/SSLManagerTest.java
=> release 1.3.2, fix some tests error

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestClientTimeout.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
=> [SCB-2171]avoid leak server ip when process TimeoutException

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/fix/TestDoSFix.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestCookieProcessor.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestHeaderProcessor.java, dependencies/default/pom.xml
=> SCB-2168 Upgrade jackson from 2.10.5 to 2.12.0

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/WeightedResponseTimeRuleExt.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestWeightedResponseTimeRuleExt.java
#之前使用的策略是会一直累积计算平均响应时间，会导致出现影响速度较慢。
#通过使用时间窗口来计算平均响应时间，可以提高响应的敏感度。
---
=> SCB-2178 Improve algorithm of loadBalance strage WeightedResponse

governance/src/main/java/org/apache/servicecomb/governance/handler/AbstractGovernanceHandler.java
=> [SCB-2116]add current control for configure change

handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/RouterInvokeFilter.java
=> canary release bug fix

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterManager.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/HttpTransportFactory.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/HttpTransportImpl.java
=> [SCB-2184]common http client api refactor to support users need

huawei-cloud/environment/src/main/resources/mapping.yaml
=> [SCB-2177]mapping dashboard service address

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java
=> [SCB-2190] allow customer exclude servicecomb configuration mechanism

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestUploadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/UploadSchema.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpFromPart.java
=> [SCB-2189]uploading multiple files using RestTemplate randomly fail

core/src/main/java/org/apache/servicecomb/core/registry/ThirdServiceRegister.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/DynamicEnum.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/DynamicEnumCache.java, foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/base/DynamicEnumTest.java
=> [SCB-2193] dynamic enum can indicate value is static or dynamic

demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/ClientServerEndpoint.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/IRpcEndpoint.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-server/src/main/java/org/apache/servicecomb/demo/zeroconfig/server/RpcEndpoint.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/ServerTest.java, dependencies/default/pom.xml
=> [SCB-2194]upgrade netty from 4.1.47 to 4.1.59

demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/java/org/apache/servicecomb/springboot/springmvc/client/PlaceHolderSchemaTest.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/resources/application.yml, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/PlaceHolderSchema.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/resources/application.yml, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestWeakSpringmvc.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
=> [#1946] add examples/test case for this issue

handlers/handler-router/src/main/java/org/apache/servicecomb/router/RouterFilter.java, handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/RouterServerListFilter.java, handlers/handler-router/src/test/java/org/apache/servicecomb/router/RouterDistributorTest.java
=> [SCB-2209]fix RouterFilter print logs for each invocation

handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/QpsControllerManagerTest.java
=> [SCB-2210]fix the flow control error when configuration changed in config center

NOTICE
=> [SCB-2208]update NOTICE

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/Microservice.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceFactory.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/definition/DefinitionConst.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightDiscovery.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightRegistration.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/RegisterRequest.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/Self.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestMicroserviceFactory.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/Config.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/Multicast.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigDiscovery.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigServer.java
=> [SCB-2225] zero-config ignore different app's register request when disable cross app

huawei-cloud/environment/src/main/resources/mapping.yaml
=> [SCB-2229]adapt PAAS_CSE_DS_ENDPOINT for servicestage

huawei-cloud/servicestage/pom.xml, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/AKSKAuthHeaderProvider.java, huawei-cloud/servicestage/src/test/java/org/apache/servicecomb/huaweicloud/servicestage/TestAKSKAuthHeaderProvider.java
=> [SCB-2230]encoding project name for non english

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceFactory.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/ServiceCombVersion.java, foundations/foundation-registry/src/main/resources/META-INF/services/org.apache.servicecomb.registry.api.Versions, foundations/foundation-registry/src/test/java/org/apache/servicecomb/registry/api/registry/TestServiceCombVersion.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java
=> [SCB-2235] should init microservice.framework for all registry type

doap_ServiceComb_Java-Chassis.rdf
=> add doap file

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/query/QueryCodecCsvTest.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/query/QueryCodecMultiTest.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/query/QueryCodecPipesTest.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/query/QueryCodecSsvTest.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/query/QueryCodecTsvTest.java, pom.xml, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/RestClientTestBase.java
=> [SCB-2240] upgrade maven-surefire-plugin version to 3.0.0-M5 to support junit5

governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java, governance/src/test/resources/application.yaml
add a getter method for CircuitBreaker
=> [SCB2236]fix circuit breaker bean property slidingWindowType

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/config/ConfigurePropertyUtils.java, handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/HystrixPropertiesStrategyExt.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/config/TestConfigurePropertyUtils.java
=> [SCB-2241] fix microservice.basePaths data type bug

core/src/main/java/org/apache/servicecomb/core/BootListener.java, core/src/main/java/org/apache/servicecomb/core/definition/MicroserviceVersionsMeta.java
=> [SCB-2242] fix org.apache.servicecomb.core.definition.MicroserviceVersionsMeta#MicroserviceVersionsMeta bug of OOM

service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/AbstractModeCondition.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/Config.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigConst.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/local/LocalRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/multicast/ConditionOnMulticast.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/multicast/Multicast.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/multicast/MulticastRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/multicast/MulticastServer.java
=> [SCB-2243] zero-config remove @Conditional to not trigger configuration bug

core/src/main/java/org/apache/servicecomb/core/invocation/InvocationTimeoutBootListener.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/DiscoveryClient.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/DiscoveryEndpoint.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/StoreService.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/store/Store.java, service-registry/registry-lightweight/src/main/resources/microservice.yaml, service-registry/registry-lightweight/src/test/java/org/apache/servicecomb/registry/lightweight/StoreServiceTest.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/Config.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigConst.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/multicast/Multicast.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/multicast/MulticastRegistration.java
=> [SCB-2244] change DiscoveryEndpoint to make mock multiple instances possible when test zero config performance

core/src/main/java/org/apache/servicecomb/core/invocation/InvocationTimeoutBootListener.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
=> [SCB-2247] consumer invocation with filter throw NPE when http status is not 2xx

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/AddressManager.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRawClient.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/RBACBootStrapService.java
=> [SCB-2246]fix common client retry given wrong address and fail with 404

service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightRegistration.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/RegisterInstanceEvent.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/StoreService.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/AbstractZeroConfigRegistration.java
=> [SCB-2250] optimize zero-config register instance

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestProducerInvocationFlow.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java, core/src/main/java/org/apache/servicecomb/core/exception/DefaultExceptionProcessor.java, core/src/main/java/org/apache/servicecomb/core/exception/ExceptionProcessor.java, core/src/main/java/org/apache/servicecomb/core/exception/Exceptions.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, core/src/test/java/org/apache/servicecomb/core/exception/ExceptionsTest.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/InjectProperties.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerCodecFilter.java
=> [SCB-2251] make exception processor extendable

core/src/main/java/org/apache/servicecomb/core/exception/DefaultExceptionProcessor.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/ConfigObjectProperty.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/PriorityProperty.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/PriorityPropertyManager.java
=> [SCB-2253] reduce invoke setter when configuration changed for @InjectProperties

clients/http-client-common/pom.xml, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/WebSocketListener.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/WebSocketTransport.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/task/AbstractTask.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/AddressManager.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/DiscoveryEvents.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterDiscovery.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRawClient.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterWatch.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/MicroserviceInstance.java, demo/demo-multi-service-center/demo-multi-service-center-client/src/main/java/org/apache/servicecomb/demo/multiServiceCenterClient/RegistryClientTest.java, dependencies/default/pom.xml
=> [SCB-2254]common service center client support websocket

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/SSLSocketFactoryExt.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/WebSocketTransport.java
…centerwatch fails. An error is reported, indicating web socket closed, code = - 1
---
=> SCB-2255 Start the watch mode of servicecenter. Web socket in servicecenterwatch fails. An error is reported, indicating web socket closed, code = - 1

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java, core/src/main/java/org/apache/servicecomb/core/definition/ConsumerMicroserviceVersionsMeta.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/ReferenceConfig.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestInvokeWhenServerNotReady.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java
=> [SCB-2252]report error when invoke a service when SCBEngine is not ready

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceTextPlainProcessor.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/MultiErrorCodeServiceClient.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/Discovery.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceInstances.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightDiscovery.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalDiscovery.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java
=> [SCB--2252]fix discovery revision API not used and other TODOs

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/DefaultHttpClientMetrics.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/DefaultHttpServerMetrics.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultEndpointMetric.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultHttpSocketMetric.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/metrics/TestDefaultHttpClientMetrics.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/metrics/TestDefaultHttpServerMetrics.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/SessionStickinessRule.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/vertx/EndpointMeter.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/ClientEndpointsLogPublisher.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/ServerEndpointsLogPublisher.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java
=> [SCB-2268]metrics add requests and latency for endpoint

README.md, README_ZH.md
=> [#2378]fix broken developer documentation link

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/IpPortManager.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/client/TestIpPortManager.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestClientHttp.java
=> [SCB-2266]IpPortManager Uses RoundRobin rule

core/src/main/java/org/apache/servicecomb/core/invocation/endpoint/EndpointUtils.java, dependencies/default/pom.xml
=> [SCB-2277]upgrade httpcomponents from 4.5.7 to 4.5.13

.github/workflows/maven.yml
=> upgrade cache plugin

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/HttpTransportFactory.java, deployment/src/main/java/org/apache/servicecomb/deployment/Deployment.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/ConfigCenterConfig.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/ConfigCenterConfigurationSourceImpl.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/KieConfig.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/KieConfigurationSourceImpl.java
=> [SCB-2279]config service client should support proxy

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java
=> [SCB-2282]RBAC token using cache api

governance/src/main/java/org/apache/servicecomb/governance/marker/Matcher.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, governance/src/test/resources/application.yaml
=> [SCB-2281]governance match support multiple items

huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/DefaultMonitorDataPublisher.java
=> [SCB-2284]when dashboard enabled may cause NPE and startup fail

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/NetUtils.java, foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/net/TestNetUtils.java
=> [SCB-2285]find publish address may get wrong docker address

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/Microservice.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfigBuilder.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
=> [SCB-2291]allow configuration to override schema always

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java
=> [SCB-2292]afterRegistryInstance should @EnableExceptionPropagation

handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/Configuration.java, handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/TestConfiguration.java
=> [SCB-2296]fallback.enabled not used and can be deleted in code

providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/RpcReference.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/RpcSchema.java, providers/provider-rest-common/src/main/java/org/apache/servicecomb/provider/rest/common/RestSchema.java, spring-boot/spring-boot-starters/java-chassis-spring-boot-starter/src/main/java/org/apache/servicecomb/springboot2/starter/EnableServiceComb.java
=> [SCB-2297]@RpcReference add annotation type to support customization

governance/src/main/java/org/apache/servicecomb/governance/handler/BulkheadHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RateLimitingHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RetryHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/ext/AbstractRetryExtension.java, governance/src/main/java/org/apache/servicecomb/governance/handler/ext/RetryExtension.java, governance/src/main/java/org/apache/servicecomb/governance/policy/AbstractPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/BulkheadPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/RateLimitingPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/RetryPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/properties/GovernanceProperties.java, governance/src/main/java/org/apache/servicecomb/governance/utils/GovernanceUtils.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, governance/src/test/java/org/apache/servicecomb/governance/MockRetryExtension.java, governance/src/test/java/org/apache/servicecomb/governance/OperatorTest.java, governance/src/test/java/org/apache/servicecomb/governance/handler/ext/RetryExtensionTest.java, governance/src/test/resources/application.yaml, handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ServiceCombRetryExtension.java
=> SCB-2295 Governance supports time periods of string type

java-chassis-dependencies/default/pom.xml, java-chassis-distribution/src/release/LICENSE
=> [SCB-2300]upgrade netty to 4.1.66 and vert.x to 3.9.8

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpFromPart.java
=> [SCB-2301]fix upload randomly fail

handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/QpsControllerManagerTest.java, integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestVertxTransportConfig.java
=> [SCB-2302]fix flowcontrol configuration changed cause NPE

governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java
=> #SCB-2304modify the parameters type of parameter circuitBreakerPolicy from int to float

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterOperation.java, clients/service-center-client/src/test/java/org/apache/servicecomb/service/center/client/ServiceCenterClientTest.java
=> [SCB-2306]service center client query schema list should include content

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/OperationEvents.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/ErrorMessage.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/event/NotPermittedEvent.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/event/ServiceCenterEventBus.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/ServiceRegistryFactory.java
=> [SCB-2307]send unauthorized event when service center operation fails

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java
=> # SCB-2309 Change token refresh retry error code

governance/src/main/java/org/apache/servicecomb/governance/policy/BulkheadPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java
=> SCB-2308 the parameter of bulkhead supports to be 0

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/event/DynamicConfigurationChangedEvent.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/event/RefreshGovernanceConfigurationEvent.java, governance/src/main/java/org/apache/servicecomb/governance/event/GovernanceConfigurationChangedEvent.java, governance/src/main/java/org/apache/servicecomb/governance/event/GovernanceEventManager.java, governance/src/main/java/org/apache/servicecomb/governance/handler/AbstractGovernanceHandler.java, governance/src/main/java/org/apache/servicecomb/governance/properties/GovernanceProperties.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ServiceCombConfigurationEventAdapter.java
=> #SCB-2310 Controls the order of configuration change event listening

dependencies/default/pom.xml
=> [SCB-2311]upgrade resilence4j to 1.7.0

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterDiscovery.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java, governance/src/main/java/org/apache/servicecomb/governance/properties/GovernanceProperties.java
=> [SCB-2313]make service center client pull interval configurable

core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
=> [SCB-2314]fix problem when calling RPC code fail in vert.x worker pool

demo/demo-multi-service-center/demo-multi-service-center-client/src/main/java/org/apache/servicecomb/demo/multiServiceCenterClient/Application.java, demo/demo-multi-service-center/demo-multi-service-center-client/src/main/resources/application.yml, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/SharedVertxFactory.java
=> [SCB-2315]transport event loop size configurable

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestClientRequest.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java, core/src/main/java/org/apache/servicecomb/core/Invocation.java, core/src/main/java/org/apache/servicecomb/core/invocation/InvocationStageTrace.java, core/src/test/java/org/apache/servicecomb/core/invocation/TestInvocationStageTrace.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestInvocationPublishModelFactory.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClientFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientRequestParameters.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSenderFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java
=> [SCB-2299]improve request write time calculation

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestRestTransportClient.java
=> [SCB-1715] Fix idleTimeout not work in client side without keepaliveTimeout set

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpServerFilterBeforeSendResponseExecutor.java
…cause server hang without any information
---
=> [SCB-1740]RouterInvokeFilter beforeSendResponseAsync return null and cause server hang without any information

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultHttpSocketMetric.java
=> [SCB-2052] fix get connection time is 0 when get connection timeout

core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultHttpSocketMetric.java, handlers/handler-bizkeeper/readme.MD, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
=> [SCB-2069][SCB-2113][SCB-2127]throw exception in event-loop,fix readme error,not isolate service when timeout

providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/RestTemplateCopyHeaderFilter.java, providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestRestTemplateCopyHeaderFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestDefaultHttpClientFilter.java
=> #SCB-2321 change DefaultHttpClientFilter order not with max value

demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CategorizedTestCaseRunner.java, dependencies/default/pom.xml, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/CommonHttpEdgeDispatcher.java
=> [SCB-2323]fix CommonHttpEdgeDispatcher request already write problem

clients/config-common/src/main/java/org/apache/servicecomb/config/common/ConfigurationChangedEvent.java, clients/config-common/src/test/java/org/apache/servicecomb/config/common/TestConfigurationChangedEvent.java, clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java, clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieConfigManager.java, demo/demo-cse-v1/README.md, demo/demo-cse-v2/README.md, demo/demo-cse-v2/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerConfigController.java, demo/demo-cse-v2/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerConfigurationProperties.java, demo/demo-cse-v2/consumer/src/main/resources/application.yml, demo/demo-cse-v2/gateway/src/main/resources/application.yml, demo/demo-cse-v2/provider/src/main/resources/application.yml, demo/demo-cse-v2/test-client/src/main/java/org/apache/servicecomb/samples/ConsumerConfigIT.java, demo/demo-cse-v2/test-client/src/main/resources/application.yml, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/ConfigCenterConfigurationSourceImpl.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/KieConfigurationSourceImpl.java
=> [SCB-2325]when configurations not changed do not send event

clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieConfigManager.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/ConfigCenterConfigurationSourceImpl.java
=> [SCB-2326]when do not have any configurations do not fail in first pull

java-chassis-dependencies/default/pom.xml
=> [SCB-2300]upgrade netty to 4.1.67

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfigBuilder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java, transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestTransportClientConfig.java
=> #scb-2317 change client default connection idle timeout to 30s

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDownloadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/DownloadUtils.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/StandardHttpServletResponseEx.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerResponseToHttpServletResponse.java
=> SCB-2319 when dowanload part is null, will throw NPE

demo/docker-build-config/pom.xml, demo/pom.xml
=> fix problem of highest-basedir

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java
Looping is not necessary for basic data types, and null pointer judgment.
=> [SCB-2331]Looping is not necessary for basic data types, and null pointer judgment.

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/FormRequestClient.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/FormRequest.java, demo/demo-jaxrs/jaxrs-server/src/main/resources/microservice.yaml, demo/docker-build-config/pom.xml, demo/pom.xml, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestTransportConfig.java
=> [SCB-2333] HttpServerOptions.maxFormAttributeSize can be configurable

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManagerTest.java, service-registry/registry-service-center/src/test/resources/microservice.yaml
=> #2585 Make the user name not decrypted

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpParser.java
=> [SCB-2338]highway should not have a default response body limit of 20M

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/CodeFirstPojoClient.java, demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/CodeFirstPojo.java, demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/MapModel.java, integration-tests/pojo-test/src/test/java/org/apache/servicecomb/demo/pojo/test/endpoints/CodeFirstPojo.java
=> add more test cases to 20M limit and null map value

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceManager.java
=> [SCB-2337]add synchronized check for MicroserviceVersions update

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/StandardHttpServletResponseEx.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java
=> [SCB-2339]HttpServletResponseEx implements setStatus

dependencies/default/pom.xml
=> [#2669] upgrade netty and vert.x version

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/PriorityInstancePropertyDiscoveryFilter.java, handlers/handler-loadbalance/src/main/resources/META-INF/services/org.apache.servicecomb.registry.discovery.DiscoveryFilter, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/PriorityInstancePropertyDiscoveryFilterTest.java
=> [SCB-2354]Provide a flexible discovery filter based on instance property and filtering with priority

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/PriorityInstancePropertyDiscoveryFilter.java, handlers/handler-loadbalance/src/main/resources/META-INF/services/org.apache.servicecomb.serviceregistry.discovery.DiscoveryFilter, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/PriorityInstancePropertyDiscoveryFilterTest.java
=> merge #2677 into 1.3.x branch

NOTICE
=> Updated Notice file to 2022

dependencies/default/pom.xml
- Bump hibernate version to 6.2.1.Final
- Remove the duplicate depdency definition
---
=> [SCB-2370]upgrade hibernate from 6.1.5.Final to 6.2.1.Final

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestFlowControl.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/FixedWindowStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java
=> [SCB-2369] improve fow control logs and message

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestFlowControl.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/FixedWindowStrategy.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConsumerQpsFlowControlHandler.java, handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java
=> [SCB-2369] improve fow controller logs and message

core/src/main/java/org/apache/servicecomb/core/provider/consumer/SyncResponseExecutor.java
=> [SCB-2382]guarded wait timeout is not correct

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestUploadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/UploadSchema.java
=> [SCB-2384] add multi file upload demo through rpc

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
=> [SCB-2385]fix IsolationDiscoveryFilter create many temporary objects

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/AddressManager.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/AbstractAddressManager.java, clients/http-client-common/src/test/java/org/apache/servicecomb/http/client/common/AbstractAddressManagerTest.java, dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/ConfigCenterConfigurationSourceImplTest.java, dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/center/client/AddressManagerTest.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfigBuilder.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/refresh/AddressManager.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/refresh/ClassificationAddress.java
=> [SCB-2386] Optimiza AZ affinity logic

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/refresh/AddressManager.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/refresh/AddressManagerTest.java
=> [SCB-2361] modify transformIpPort logic

java-chassis-dependencies/default/pom.xml
=> [SCB-2364] upgrate netty and vertx version

pom.xml
upgrade maven compiler plugin version to 3.10.1 to support java17
=> [SCB-2427] upgrade maven compiler plugin version to 3.10.1

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/refresh/ClassificationAddress.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/client/TestIpPortManager.java
=> [SCB-2361] Support AZ information and IP grouping strategy

archetypes/business-service-jaxrs/src/main/resources/archetype-resources/pom.xml, archetypes/business-service-pojo/src/main/resources/archetype-resources/pom.xml, archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/pom.xml, archetypes/business-service-springmvc/src/main/resources/archetype-resources/pom.xml, pom.xml
make archetype springboot version consistent with project
update springboot version from `2.1.2.RELEASE` to `2.5.6`
=> [SCB-2430]make archetype springboot version consistent with project

demo/demo-jaxrs/jaxrs-client/pom.xml, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/JaxrsClient.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestCodeFirstJaxrs.java, demo/demo-jaxrs/jaxrs-client/src/test/java/org/apache/servicecomb/demo/jaxrs/JaxrsIT.java, demo/demo-jaxrs/jaxrs-server/pom.xml, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/JaxrsServer.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java, demo/demo-spring-boot-provider/demo-spring-boot-jaxrs-client/src/main/java/org/apache/servicecomb/springboot/jaxrs/client/JaxrsClient.java
=> move test case main class to make it more easier to find

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestFormRequestSchema.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestDispatcher.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestVertxRestDispatcher.java
=> [SCB-2433] Edge service exception handle do not sent unexpected message

archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/pom.xml, dependencies/default/pom.xml, pom.xml
=> [SCB-2439]upgrate spring to 5.3.18 and spring boot to 2.5.12

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
=> [SCB-2440] remove non-essential null judgment

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/AbstractAddressManager.java, core/src/test/java/org/apache/servicecomb/core/exception/converter/TimeoutExceptionConverterTest.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/KieConfigurationSourceImpl.java, foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/KeyStoreUtil.java, handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/BizkeeperCommand.java, handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/ConsumerBizkeeperHandler.java, handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/ProviderBizkeeperHanlder.java, handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/TestBizkeeperHandler.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/exception/LoadbalanceExceptionUtils.java, huawei-cloud/darklaunch/src/main/java/org/apache/servicecomb/darklaunch/MicroserviceCache.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/StoreService.java
=> [SCB-2441] delete redundant local variables

swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/context/InvocationContext.java, swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/context/TestInvocationContext.java
=> [SCB-2465]Fix InvocationContext merge logic encapsulation violation

huawei-cloud/darklaunch/src/main/java/org/apache/servicecomb/darklaunch/oper/AbstractCondition.java
=> [SCB-2471] optimize the compareTo(···) method

dependencies/default/pom.xml
=> [SCB-2487] Remove unused xstream maven dependency

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/task/AbstractTask.java, dynamic-config/config-nacos/src/main/java/org/apache/servicecomb/config/nacos/client/NacosClient.java, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedConfigurationLoader.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/config/PaaSResourceUtils.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/Log4jUtils.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/MimeTypesUtils.java, foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrap.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientWithContext.java, governance/src/main/java/org/apache/servicecomb/governance/handler/AbstractGovernanceHandler.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/InstancePropertyDiscoveryFilter.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/ZoneAwareDiscoveryFilter.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/NetMeter.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/net/InterfaceUsage.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CommonToHttpServletRequest.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/pojo/PojoOperationGenerator.java
=> [SCB-2494] use lambda for some code

clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/model/KVDoc.java, clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/model/LabelDocResponse.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/HeartbeatsRequest.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/MicroserviceInstance.java
=> [SCB-2496] remove unnecessary explicit type declaration

foundations/foundation-test-scaffolding/src/main/java/io/vertx/core/impl/SyncContext.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/BufferOutputStream.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServer.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/AbstractBaseIntegerProperty.java
=> [SCB-2501] add @Override annotation on missing implementing methods

.github/workflows/checkstyle.yml, .github/workflows/maven.yml, .github/workflows/rat_check.yml, .github/workflows/spotbugs.yml, .github/workflows/unit-test-jdk11.yml, .github/workflows/unit-test-jdk17.yml
=> [SCB-2503]Add timeout for workflows

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/UploadConfig.java, core/src/main/java/org/apache/servicecomb/core/transport/AbstractTransport.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/YAMLUtil.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/cpu/ProcessCpuUsage.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerProducerOperation.java
=> [SCB-2504] remove unused "LOGGER" private field

governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/main/java/org/apache/servicecomb/governance/marker/GovernanceRequest.java, governance/src/main/java/org/apache/servicecomb/governance/marker/Matcher.java, governance/src/main/java/org/apache/servicecomb/governance/marker/RequestProcessor.java, governance/src/test/java/org/apache/servicecomb/governance/FlowControlTest.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, governance/src/test/java/org/apache/servicecomb/governance/InstanceIsolationTest.java, governance/src/test/resources/application.yaml
=> [SCB-2514]governance rate limiting support service name match

.github/dependabot.yml, dependencies/default/pom.xml
- add protostuff-parser 5.x ignore
- bump protostuff-parser to 2.2.27
=> [SCB-2489] Add dependeny bot ignore protostuff-parser

common/common-protobuf/src/test/java/io/protostuff/runtime/model/ModelProtobuf.java, dependencies/default/pom.xml, foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/internal/model/ProtobufRoot.java
`src/test/java/org/apache/servicecomb/foundation/protobuf/internal/model/ProtobufRoot.java`AND `src/test/java/io/protostuff/runtime/model/ModelProtobuf.java` regenerate by protoc-3.20.1
=> [SCB-2519]Bump protobuf-java from 3.7.1 to 3.20.1

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterDiscovery.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java
=> [SCB-2578]instance pull should avoid too many queued events

governance/pom.xml, governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/test/java/org/apache/servicecomb/governance/InstanceIsolationTest.java, huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/DataFactory.java, huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/DefaultMonitorDataPublisher.java, huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/HealthMonitorDataProvider.java, huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/MetricsMonitorDataProvider.java, huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/model/MonitorDataProvider.java, huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/model/MonitorDataPublisher.java, huawei-cloud/dashboard/src/test/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/MetricsMonitorDataProviderTest.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestThreadPoolPublishModelFactory.java
=> [SCB-2588]circuit breaker provider a name to distinguish metrics

governance/src/main/java/org/apache/servicecomb/governance/handler/BulkheadHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RateLimitingHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RetryHandler.java, governance/src/main/java/org/apache/servicecomb/governance/policy/RetryPolicy.java, governance/src/test/java/org/apache/servicecomb/governance/CircuitBreakerHandlerTest.java, governance/src/test/java/org/apache/servicecomb/governance/RetryHandlerTest.java
=> [SCB-2596]retry add failAfterMaxAttempts property

governance/src/main/java/org/apache/servicecomb/governance/handler/AbstractGovernanceHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/BulkheadHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RateLimitingHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RetryHandler.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, governance/src/test/java/org/apache/servicecomb/governance/InstanceIsolationTest.java, governance/src/test/java/org/apache/servicecomb/governance/RetryHandlerTest.java, governance/src/test/resources/application.yaml
=> [SCB-2290]isolation implementation of instance method

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterManager.java, clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/model/ConfigCenterConfiguration.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/ConfigCenterConfig.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/ConfigCenterConfigurationSourceImpl.java
=> [SCB-2592] configuration refresh time is configurable for config center

ci/checkstyle/checkstyle.xml, common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/internal/converter/SwaggerToProtoGenerator.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/ConfigObjectFactory.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/DeserializerSchemaManager.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/SerializerSchemaManager.java
=> [SCB-2595] enable checkstyle missingSwitchDefault

huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/data/CPUMonitorCalc.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/adapter/EnvAdapterManager.java
=> [SCB-2599] fix some singleton classes construction method not private

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/KieConfig.java
=> [SCB-2601] fix kie fileSource not support comma separated

governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java
=> [SCB-2600]add forceClosed and forceOpen parameter to circuit breaker

swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/producer/codec/ArgWrapperJavaType.java
=> [SCB-2614] remove debug code (main method) of ArgWrapperJavaType

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringMVCSchema.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestRestTemplate.java, demo/demo-springmvc/springmvc-client/src/main/resources/SpringMVCSchema.yaml, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/OperationGenerator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java, swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestMappingMethodAnnotationProcessor.java, swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/TestSpringmvc.java, swagger/swagger-generator/generator-springmvc/src/test/resources/schemas/requestMappingHttpMethod.yaml
=> [3108] support @RequestMapping annotation

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/BeansHolder.java
=> [SCB-2619] remove @Component annotation of BeansHolder

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java
=> [SCB-2629] use SystemUtils.JAVA_IO_TMPDIR

huawei-cloud/environment/src/main/resources/mapping.yaml, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/CasEnvConfig.java, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/CasEnvVariablesAdapter.java, huawei-cloud/servicestage/src/test/java/org/apache/servicecomb/huaweicloud/servicestage/TestCasEnvConfig.java, huawei-cloud/servicestage/src/test/java/org/apache/servicecomb/huaweicloud/servicestage/TestEnvVariablesAdapter.java
…check in to the registry.
---
=> [SCB-2639]Support microservice component labels and instance routing labels register to service center

core/src/main/java/org/apache/servicecomb/core/handler/impl/ProducerOperationHandler.java
=> [SCB-2642] Fix ProducerOperationHandler log tracing problem

.github/actions/copy-integration-tests-logs/action.yml, .github/workflows/maven.yml, .github/workflows/unit-test-jdk17.yml, ci/copy-integration-tests-logs.sh
In github actions summary
artifacts
=> [SCB-2649] Upload integration-tests logs when failure

demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/resources/application.yml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-server/src/main/resources/application.yml, foundations/foundation-common/src/main/resources/config/base/log4j.properties, governance/src/main/java/org/apache/servicecomb/governance/GovernanceConfiguration.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceBulkheadHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/ext/AbstractFailurePredictor.java, governance/src/main/java/org/apache/servicecomb/governance/policy/CircuitBreakerPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/RetryPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/properties/InstanceBulkheadProperties.java, governance/src/test/java/org/apache/servicecomb/governance/AbstractFailurePredictorTest.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, governance/src/test/java/org/apache/servicecomb/governance/InstanceBulkheadHandlerTest.java, governance/src/test/resources/application.yaml, handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ConsumerInstanceBulkheadHandler.java, handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ConsumerInstanceIsolationHandler.java, handlers/handler-governance/src/main/resources/config/cse.handler.xml, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/IsolationDiscoveryFilter.java
=> [SCB-2650][SCB-2290]support instance isolation and instance bulkhead

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/ConfigObjectFactory.java
=> [SCB-2646] fix metaspace oom problem

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/ConfigObjectFactory.java
=> [SCB-2650][SCB-2290]fix retry will always wait

dependencies/default/pom.xml, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedEdgeDispatcher.java, foundations/foundation-test-scaffolding/src/main/java/io/vertx/core/impl/SyncContext.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java, foundations/foundation-vertx/src/test/java/io/vertx/ext/web/impl/TestHttpServerRequestUtils.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerRequestToHttpServletRequest.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestVertxRestDispatcher.java
- https://vertx.io/blog/eclipse-vert-x-4-3-0/
=> [SCB-2509] Bump vertx version from 4.2.7 to 4.3.2

governance/pom.xml, governance/src/main/java/org/apache/servicecomb/governance/GovernanceConfiguration.java, governance/src/main/java/org/apache/servicecomb/governance/handler/AbstractGovernanceHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/BulkheadHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/Disposable.java, governance/src/main/java/org/apache/servicecomb/governance/handler/DisposableBulkhead.java, governance/src/main/java/org/apache/servicecomb/governance/handler/DisposableCircuitBreaker.java, governance/src/main/java/org/apache/servicecomb/governance/handler/DisposableHolder.java, governance/src/main/java/org/apache/servicecomb/governance/handler/DisposableMap.java, governance/src/main/java/org/apache/servicecomb/governance/handler/DisposableRateLimiter.java, governance/src/main/java/org/apache/servicecomb/governance/handler/DisposableRetry.java, governance/src/main/java/org/apache/servicecomb/governance/handler/FaultInjectionHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/IdentifierRateLimitingHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceBulkheadHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RetryHandler.java, governance/src/main/java/org/apache/servicecomb/governance/marker/GovernanceRequest.java, governance/src/main/java/org/apache/servicecomb/governance/marker/RequestProcessor.java, governance/src/main/java/org/apache/servicecomb/governance/policy/IdentifierRateLimitingPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/policy/RateLimitingPolicy.java, governance/src/main/java/org/apache/servicecomb/governance/properties/IdentifierRateLimitProperties.java, governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java, governance/src/test/java/org/apache/servicecomb/governance/IdentifierRateLimitingHandlerTest.java, governance/src/test/java/org/apache/servicecomb/governance/InstanceIsolationTest.java, governance/src/test/java/org/apache/servicecomb/governance/RetryHandlerTest.java, governance/src/test/resources/application.yaml, governance/src/test/resources/log4j.properties
=> [SCB-2661]add identifier based rate limiting

demo/demo-jaxrs/jaxrs-client/pom.xml, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestCodeFirstJaxrs.java, demo/demo-jaxrs/jaxrs-client/src/main/resources/microservice.yaml, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java, demo/demo-spring-boot-provider/demo-spring-boot-jaxrs-client/src/main/resources/application.yml, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/event/ServiceCenterEventBus.java, handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ConsumerInstanceIsolationHandler.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/refresh/ClassificationAddress.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/ServiceRegistryFactory.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/TestConsumers.java
=> [SCB-2662]trigger pull instance event when instance isolated

handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java
=> [SCB-2666]The bucket value logic is incorrect

governance/src/main/java/org/apache/servicecomb/router/RouterFilter.java, governance/src/main/java/org/apache/servicecomb/router/match/RouterRuleMatcher.java, governance/src/main/java/org/apache/servicecomb/router/model/PolicyRuleItem.java, governance/src/main/java/org/apache/servicecomb/router/model/ServiceInfoCache.java, governance/src/test/java/org/apache/servicecomb/router/RouterDistributorDynamicConfig2Test.java, governance/src/test/java/org/apache/servicecomb/router/RouterDistributorDynamicConfigTest.java, governance/src/test/java/org/apache/servicecomb/router/RouterDistributorFileConfigTest.java
=> [SCB-2658]minor code improvement and add test case

core/src/main/java/org/apache/servicecomb/core/governance/MatchType.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/ClientModel.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/ClientServerEndpoint.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/resources/application.yml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/ClientModel.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/ServerTest.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/resources/microservices/demo-zeroconfig-schemadiscovery-registry-edge/ClientServerEndpoint.yaml, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/scalar/Int64WriteSchemas.java, foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/TestISODateTimeParsing.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/tcp/TcpConnection.java
=> [SCB-2686]fix date time from edge not parsed by highway problem

demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/resources/microservice.yaml, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestMaxHttpUrlLength.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestThirdPartyRegistration.java, demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/third/Register.java, demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml, governance/src/main/java/org/apache/servicecomb/governance/marker/TrafficMarker.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestDispatcher.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestTransport.java
=> [SCB-2690]support configure url prefix for vert.x rest dispatcher

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestRpcReferenceMethodInjection.java, demo/demo-pojo/pojo-client/src/main/resources/microservice.yaml, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/RpcReference.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/reference/RpcReferenceProcessor.java
=> [SCB-2424]RpcReference support setter injection

dependencies/default/pom.xml, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/YAMLUtil.java, governance/src/main/java/org/apache/servicecomb/governance/properties/GovernanceProperties.java, governance/src/main/java/org/apache/servicecomb/router/cache/RouterRuleCache.java
=> Bump snakeyaml from 1.32 to 1.33

demo/demo-multi-service-center/demo-multi-service-center-client/src/main/java/org/apache/servicecomb/demo/multiServiceCenterClient/Application.java
=> fix ut not stable problem

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/IsolationDiscoveryFilter.java
=> [SCB-2703]servicecomb.loadbalance.isolation.enabled not work

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestUploadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/UploadSchema.java
=> add a test case for upload using String with Spring MVC

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/validation/ValidationServiceClient.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/validation/ValidationService.java
=> [#3354 ]add a test case for not null

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestCodec.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestBodyProcessor.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/validation/ValidationServiceClient.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/validation/ValidationService.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/AnnotationsTest.java, providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequestTest.java
=> [SCB-2715]if body parameter not provided should fail for spring mvc

dependencies/default/pom.xml, parents/default/pom.xml
=> Bump mockito.version from 4.0.0 to 4.8.1

governance/src/main/java/org/apache/servicecomb/governance/handler/ext/FailurePredictor.java
=> [SCB-2717] add exception retry for SslHandshakeTimeoutException

governance/src/main/java/org/apache/servicecomb/router/model/HeaderRule.java, governance/src/test/java/org/apache/servicecomb/router/RouterDistributorDynamicConfig2Test.java
=> [SCB-2719]route configuration caseInsensitve meaning is wrong

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java
=> [#3457]swaggerDifferent add post MicroserviceRegistrationEvent

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/RegistrationEvents.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java
=> [SCB-2721]registration events include Microservice information

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestQueryParamSchema.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/QueryParamSchema.java
=> [SCB-2701] add a test case for encode query plus

dependencies/default/pom.xml, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/BufferOutputStream.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestStream.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
=> Bump vertx.version from 4.3.4 to 4.3.7

demo/demo-edge/business-2.0.0/src/main/java/org/apache/servicecomb/demo/edge/business/EdgeServiceGovernanceService.java, demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/ConsumerMain.java, demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/EdgeServiceGovernanceTest.java, demo/demo-edge/edge-service/pom.xml, demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/EdgeMain.java, demo/demo-edge/edge-service/src/main/resources/microservice.yaml, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/IsolationDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/cache/RefreshableMicroserviceCache.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/cache/RefreshableServiceRegistryCache.java
=> [SCB-2742]change IsolationDiscoveryFilter enabled by false

core/src/main/java/org/apache/servicecomb/core/provider/producer/ProducerBootListener.java
=> [SCB-2737]do not print swagger contents to logs any more

.github/workflows/checkstyle.yml, .github/workflows/maven.yml, .github/workflows/rat_check.yml, .github/workflows/spotbugs.yml, .github/workflows/unit-test-jdk11.yml, .github/workflows/unit-test-jdk17.yml
=> change ci configuration for 2.8.x

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
=> [SCB-2751] continueFailure is always validate when setting below zero or zero, cause errorPercentage can not be used

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java
=> rebase master changes to 2.8.x

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestBizkeeper.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/ServiceCombConstants.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/YAMLUtil.java, foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigUtil.java, foundations/foundation-config/src/test/java/org/apache/servicecomb/config/archaius/sources/TestYAMLConfigurationSource.java, huawei-cloud/darklaunch/src/main/java/org/apache/servicecomb/darklaunch/DarklaunchServerListFilter.java
=> [SCB-2754] remove cse prefix configuration support

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/Http2TransportHttpClientOptionsSPI.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java
Signed-off-by: Youling Cheng <spadgerlin888@163.com>
=> #3607 fix idle time out and keep alive timeout not properly set problem

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceVersions.java
=> [SCB-2771]fix MicroserviceVersions concurrent access problem (#3637)

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/Discovery.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceInstances.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightDiscovery.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalDiscovery.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterDiscovery.java
=> [SCB-2773]Change mutil dicovery registry instance merge policy

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientDecoder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientEncoder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSenderFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContextFactory.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportRestClientConfiguration.java, transports/transport-rest/transport-rest-client/src/main/resources/META-INF/spring.factories
=> [SCB-2785]support spring boot auto configure and remove component scan

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/q---a.md
=> add issue template

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceInstance.java
=> [SCB-2789]available zone configuration default value should remains for null

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientOptionsSPI.java
=> [SCB-2791]Http2 client keepAliveTimeout is not properly set

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestQueryParamWithListSchema.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, dependencies/default/pom.xml, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceInstance.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientOptionsSPI.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseUriTemplateHandler.java, providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestCseUriTemplateHandler.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/MockHttpServerResponse.java
=> Pick master changes to 2.8.x

clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/model/ConfigurationsRequest.java, clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/model/ConfigurationsRequestFactory.java, demo/demo-cse-v2/README.md, demo/demo-cse-v2/consumer/src/main/resources/application.yml, demo/demo-cse-v2/pom.xml, demo/demo-cse-v2/provider/src/main/resources/application.yml, demo/demo-cse-v2/test-client/src/main/java/org/apache/servicecomb/samples/ConsumerConfigIT.java
=> [SCB-2793]Kie custom label should take the first priority

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/http/HttpUtils.java, foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/http/TestHttpUtils.java
=> [#3784]fix HttpUtils cannot correctly resolve file names

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/fix/TestDoSFix.java, dependencies/default/pom.xml
Bump jackson from 2.14.2 to 2.15.0
=> Bump jackson from 2.14.2 to 2.15.0

solutions/solution-basic/pom.xml
=> [SCB-2800]remove discovery and config implementation from solution-basic

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/schema/SchemaToProtoGenerator.java, common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/utils/ScopedProtobufSchemaManager.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/TestSchemaToProtoGenerator.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/model/CyclicInfo.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/model/DeptInfo.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/model/SchemaService.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/model/UserInfo.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProtoBufferProcessor.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/SwaggerUtils.java
=> [SCB-2803]fix proto-buffer nested list and map problems

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/internal/converter/SwaggerToProtoGenerator.java, common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/schema/SchemaToProtoGenerator.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/TestSchemaCodec.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/TestSchemaToProtoGenerator.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/model/ScoreInfo.java, common/common-protobuf/src/test/resources/ProtoSchema.proto, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/scalar/SInt32ReadSchemas.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/scalar/StringReadSchemas.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/scalar/StringWriteSchemas.java
=> [SCB-2803]map java integer/bigdecimal to proto-buffer

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java, dependencies/default/pom.xml
=> Bump Spring 5.3.29 Spring Boot 2.7.15 Vertx 4.4.4

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/event/MicroserviceInstanceChangedEvent.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/AppManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceVersions.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/AbstractDiscoveryFilter.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/swagger/SwaggerLoader.java, foundations/foundation-registry/src/test/java/org/apache/servicecomb/registry/discovery/TestDiscoveryTree.java, providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestCseClientHttpRequest.java, providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequestTest.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java, service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/TestConsumers.java
=> [SCB-2804]Fix instance not found when instances frequently change

core/src/main/java/org/apache/servicecomb/core/registry/discovery/OperationInstancesDiscoveryFilter.java, demo/demo-edge/consumer/src/main/resources/microservice.yaml, demo/demo-edge/edge-service/src/main/resources/microservice.yaml
=> [SCB-2806]disable OperationInstancesDiscoveryFilter by defalut

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/DiscoveryTree.java, foundations/foundation-registry/src/test/java/org/apache/servicecomb/registry/discovery/TestDiscoveryTree.java
=> [SCB-2808]DiscoveryTree changed to bean and not handler all services

handlers/handler-governance/src/test/java/org/apache/servicecomb/handler/governance/TestInstanceIsolationDiscoveryFilter.java
=> [SCB-2807]add missed test case

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxUtils.java
=> [#3960]fix vertx close may block shutdown

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/locator/ServicePathManager.java, demo/demo-nacos/consumer/pom.xml, demo/demo-nacos/gateway/pom.xml, demo/demo-nacos/pom.xml, demo/demo-nacos/provider/pom.xml, demo/demo-nacos/test-client/pom.xml, demo/demo-nacos/test-client/src/main/java/org/apache/servicecomb/samples/TestClientApplication.java, demo/demo-nacos/test-client/src/main/resources/application.yml, demo/demo-nacos/test-client/src/test/java/org/apache/servicecomb/samples/NocasIT.java, dynamic-config/config-nacos/src/main/java/org/apache/servicecomb/config/nacos/NacosDynamicPropertiesSource.java, foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrap.java, foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrapConfig.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/StatefulDiscoveryInstance.java, foundations/foundation-spi/src/main/java/org/apache/servicecomb/foundation/common/utils/SPIServiceUtils.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosConfiguration.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscovery.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscoveryInstance.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosRegistration.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NamingServiceManager.java
=> [SCB-2813]Nacos implementation not properly handle instance change

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
=> [#3977]fix logs information not clear problem

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/URLPathBuilder.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/locator/MicroservicePaths.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/locator/OperationLocator.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/TestRestOperationMeta.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SchemeInterfaceSpringmvc.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestManagementEndpoint.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/SchemeInterfaceSpringmvc.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/SchemeInterfaceSpringmvcImpl.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/repeated/RepeatedReadSchemas.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxClientRequestToHttpServletRequest.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java
=> [#3698]client url do not remove slash and fix test case problems

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilter.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java
=> [#3727]Fix metrics not correct when timeout/connection timeout

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestProducerInvocationCreator.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/RestProducerInvocationCreatorTest.java, core/src/main/java/org/apache/servicecomb/core/invocation/timeout/ProcessingTimeStrategy.java, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocationCreator.java, edge/edge-core/src/main/resources/META-INF/microservice.yaml, pom.xml
=> [#3979]can configure not decode invocation context

demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/EdgeServiceGovernanceTest.java, demo/demo-edge/edge-service/src/main/resources/microservice.yaml, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/java/org/apache/servicecomb/springboot/springmvc/client/UploadDownloadSchemaTest.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/UploadDownloadSchema.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientRequestParametersImpl.java
=> [#2523]fix problem when client api do not provide file parameter

handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/HttpClientRequestWrapper.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/HttpServeRequestWrapper.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/TracingConfiguration.java
=> [#3966] Add a switch to control the tracing-zipkin to adapt to the path of non CSE frameworks

common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/TestSchemaToProtoGenerator.java, foundations/foundation-config/src/test/java/org/apache/servicecomb/config/BootStrapPropertiesTest.java, foundations/foundation-test-scaffolding/src/main/java/org/apache/servicecomb/foundation/test/scaffolding/log/LogCollector.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpResponse.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightDiscovery.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/AbstractZeroConfigRegistration.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/converter/property/ObjectPropertyConverter.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ModelResolverExt.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/creator/ByteArrayPropertyCreator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/creator/BytePropertyCreator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/creator/InputStreamPropertyCreator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/creator/PartPropertyCreator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/creator/PropertyCreator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/ResponseTypeProcessor.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/response/DefaultResponseTypeProcessor.java, swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/TestArrayType.java, swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/OperationMethodAnnotationProcessorTest.java, swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/property/creator/MultipartFilePropertyCreator.java
=> [SCB-2813]fix some compile warnings

demo/demo-filter/filter-client/src/main/java/org/apache/servicecomb/demo/filter/client/GovernanceConsumerSchema.java, demo/demo-filter/filter-client/src/main/resources/microservice.yaml, demo/demo-filter/filter-edge/src/main/resources/microservice.yaml, demo/demo-filter/filter-server/src/main/java/org/apache/servicecomb/demo/filter/server/GovernanceProviderSchema.java, demo/demo-filter/filter-server/src/main/resources/microservice.yaml, demo/demo-filter/filter-tests/src/main/java/org/apache/servicecomb/demo/filter/tests/TestGovernanceSchemaFromEdge.java, demo/demo-filter/filter-tests/src/main/resources/microservices/filterEdge/GovernanceConsumerSchema.yaml, demo/demo-filter/filter-tests/src/main/resources/registry.yaml, demo/demo-pojo/pojo-server/src/main/resources/microservice.yaml, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/FlowControlQpsConfiguration.java, handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ProviderRateLimitingFilter.java
=> [SCB-2450]provide traffic mark rate limiting to edge service

core/src/main/java/org/apache/servicecomb/core/filter/CoreFilterConfiguration.java, core/src/main/java/org/apache/servicecomb/core/filter/impl/RetryFilter.java, core/src/main/java/org/apache/servicecomb/core/governance/RetryContext.java, core/src/main/java/org/apache/servicecomb/core/governance/ServiceCombCircuitBreakerExtension.java, core/src/main/java/org/apache/servicecomb/core/governance/ServiceCombInstanceIsolationExtension.java, core/src/main/java/org/apache/servicecomb/core/governance/ServiceCombRetryExtension.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, core/src/test/java/org/apache/servicecomb/core/provider/consumer/TestInvokerUtils.java, demo/demo-filter/filter-client/src/main/java/org/apache/servicecomb/demo/filter/client/RetryClientSchema.java, demo/demo-filter/filter-edge/src/main/resources/microservice.yaml, demo/demo-filter/filter-tests/src/main/java/org/apache/servicecomb/demo/filter/tests/TestRetrySchemaFromEdge.java, demo/demo-filter/filter-tests/src/main/resources/microservice.yaml, demo/demo-filter/filter-tests/src/main/resources/microservices/filterEdge/RetryClientSchema.yaml, demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml, governance/src/main/java/org/apache/servicecomb/governance/handler/CircuitBreakerHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/InstanceIsolationHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/RetryHandler.java, governance/src/main/java/org/apache/servicecomb/governance/handler/ext/FailurePredictor.java, governance/src/test/java/org/apache/servicecomb/governance/AbstractFailurePredictorTest.java, governance/src/test/java/org/apache/servicecomb/governance/MockRetryExtension.java, governance/src/test/java/org/apache/servicecomb/governance/RetryHandlerTest.java
=> [SCB-2743]edge service support retry governance

core/src/main/java/org/apache/servicecomb/core/filter/CoreFilterConfiguration.java, core/src/main/java/org/apache/servicecomb/core/filter/impl/ContextMapperFilter.java, core/src/main/java/org/apache/servicecomb/core/governance/MatchType.java, governance/src/main/java/org/apache/servicecomb/governance/marker/GovernanceRequest.java, governance/src/main/java/org/apache/servicecomb/governance/marker/GovernanceRequestExtractor.java, governance/src/main/java/org/apache/servicecomb/governance/marker/Matcher.java, governance/src/main/java/org/apache/servicecomb/governance/marker/RequestProcessor.java, governance/src/test/java/org/apache/servicecomb/governance/MapperTest.java, governance/src/test/java/org/apache/servicecomb/governance/RetryHandlerTest.java, governance/src/test/resources/application.yaml
=> [SCB-2840]add request parameter to context parameter mapper

handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/ZipkinConsumerDelegate.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/ZipkinProviderDelegate.java
=> [#4035] fix invocation context loss issue

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java, core/src/main/java/org/apache/servicecomb/core/filter/AbstractFilter.java, core/src/main/java/org/apache/servicecomb/core/filter/FilterNode.java, core/src/main/java/org/apache/servicecomb/core/filter/impl/ParameterValidatorFilter.java, core/src/main/java/org/apache/servicecomb/core/invocation/InvocationStageTrace.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/StatefulDiscoveryInstance.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/BufferInputStream.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/SlowInvocationLogger.java, solutions/solution-basic/src/main/java/org/apache/servicecomb/solution/basic/integration/InstanceOpenAPIRegistry.java
=> [SCB-2813]first time invoke performance tuning

ci/spotbugs/exclude.xml, demo/demo-spring-boot-transport/demo-spring-boot-pojo-client/src/main/java/org/apache/servicecomb/demo/springboot/pojo/client/PojoClientTest.java, pom.xml
=> com.github.spotbugs:spotbugs-maven-plugin from 4.7.3.5 to 4.8.1.0

ci/spotbugs/exclude.xml, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/AKSKAuthHeaderProvider.java
=> [#4066]fix loaded variable not assigned

.github/dependabot.yml, dependencies/default/pom.xml
=> Bump asciidoctorj from 2.5.3 to 2.5.10

huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/AKSKAuthHeaderProvider.java
=> [#4065] fix loaded variable not assigned

dependencies/default/pom.xml
=> jackson from 2.15.3 to 2.16.0

dependencies/default/pom.xml
=> Bump jersey from 3.1.2 to 3.1.4

dependencies/default/pom.xml
=> Remove unused rxnetty dependency

demo/demo-cse-v1/gateway/src/main/resources/application.yml, demo/demo-cse-v1/test-client/src/main/java/org/apache/servicecomb/samples/ConsumerConfigIT.java, demo/demo-cse-v1/test-client/src/main/java/org/apache/servicecomb/samples/HelloWorldIT.java, demo/demo-cse-v2/README.md, demo/demo-cse-v2/pom.xml, demo/demo-cse-v2/test-client/src/main/java/org/apache/servicecomb/samples/ConsumerConfigIT.java, demo/demo-multi-service-center/demo-multi-service-center-client/src/main/java/org/apache/servicecomb/demo/multiServiceCenterClient/SC2Configuration.java, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/AKSKAuthHeaderProvider.java, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/RBACBootStrapService.java, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/ServiceStageConfiguration.java, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/TokenAuthHeaderProvider.java, huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/TokenCacheManager.java, huawei-cloud/servicestage/src/main/resources/META-INF/services/org.apache.servicecomb.foundation.auth.AuthHeaderProvider, huawei-cloud/servicestage/src/main/resources/META-INF/services/org.apache.servicecomb.foundation.bootstrap.BootStrapService, huawei-cloud/servicestage/src/test/java/org/apache/servicecomb/huaweicloud/servicestage/TestAKSKAuthHeaderProvider.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/registry/sc/SCClientUtils.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/registry/sc/SCConfiguration.java
=> [SCB-2813]fix ak/sk and rbac problems

dependencies/default/pom.xml
=> Remove unused rxjava dependency

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
=> [#4049]fix shutdown in progress exception problem

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/ZoneAwareDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filterext/TestZoneAwareDiscoveryFilter.java
=> [SCB-2841]zone-aware filter support configure group size ratio

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java, core/src/main/java/org/apache/servicecomb/core/bootup/ConfigurationProblemsAlarmEvent.java, core/src/main/java/org/apache/servicecomb/core/bootup/ConfigurationProblemsCollector.java, core/src/main/resources/META-INF/services/org.apache.servicecomb.core.bootup.BootUpInformationCollector, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ConfigurationProblemsCollectorTest.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
=> [SCB-2843]detect known configuration problems and send warning message

.github/dependabot.yml, demo/demo-nacos/pom.xml, dependencies/default/pom.xml, foundations/foundation-test-scaffolding/pom.xml, parents/default/pom.xml, tracing/pom.xml, tracing/tracing-zipkin/pom.xml
=> change dependabot frequency and remove some unused dependency

dependencies/default/pom.xml, governance/pom.xml
=> remove unused dependency

core/src/main/java/org/apache/servicecomb/core/governance/GovernanceConfiguration.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
=> [SCB-2844] Adding a configuration that controls the retry interval for load balance

dependencies/default/pom.xml, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosMicroserviceHandler.java
=> Bump com.alibaba.nacos:nacos-client from 2.2.4 to 2.3.0

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/utils/ScopedProtobufSchemaManager.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessorManager.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java, demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/MultiErrorCodeServiceClient.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/SchemaManager.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/DeserializerSchemaManager.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/MessageWriteSchema.java, foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/SerializerSchemaManager.java
=> [SCB-2847]support configure default encoding for request and response

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java
… to decode response body.
---
=> [SCB-2845] Adding the switch to print response's buffer while failing to decode response body

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
=> [#4129]fix queue time not correct when queue timeout

dependencies/default/pom.xml
=> [#4170]update archaius from 0.7.7 to 0.7.8

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalanceFilter.java
=> [SCB-2846] set the level from info to warn for the log of retry operation

service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscoveryInstance.java
=> [SCB-2851]interoperate with spring cloud using nacos

README.md, README_ZH.md, parents/default/pom.xml
=> update readme and remove duplicated plugins

providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/definition/PojoConsumerMeta.java
=> [SCB-2852]remove swagger generation code for pojo consumer

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/query/AbstractQueryCodec.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDataTypesAnnotationsSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DataTypesAnnotationsSchema.java
=> [SCB-2854]query parameter support primitive array

swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/exception/DefaultExceptionToProducerResponseConverters.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/exception/ExceptionFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/exception/ExceptionToProducerResponseConverters.java, swagger/swagger-invocation/invocation-core/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverters, swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/exception/TestDefaultExceptionToProducerResponseConverters.java
=> [SCB-2855]make ExceptionToProducerResponseConverters extensible

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestApiImplicitParamsSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ApiImplicitParamsSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java
=> [SCB-2856]ApiImplicitParams works in class annotation

metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/vertx/EndpointMeter.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/vertx/HttpClientEndpointMeter.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/vertx/ServerEndpointMeter.java
=> [SCB-2857]Fix endpoint metrics not properly destroy and throw exception

demo/demo-crossapp/crossapp-client/src/main/java/org/apache/servicecomb/demo/crossapp/CrossappClient.java, demo/demo-crossapp/crossapp-server/src/main/resources/microservice.yaml, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java
=> [SCB-2861]able to add multiple origins for CORS configuration

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/FormProcessorCreator.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/query/QueryCodec.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestUploadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/UploadSchema.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientEncoder.java
=> [SCB-2862]able to upload with List form parameters

core/src/main/java/org/apache/servicecomb/core/governance/GovernanceConfiguration.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestMaxHttpUrlLength.java, dependencies/default/pom.xml, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientOptionsSPI.java, pom.xml, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RegistryHttpClientOptionsSPI.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/HttpTransportHttpClientOptionsSPI.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/MockHttpServerResponse.java
=> [SCB-2864]upgrade vertx and fix connection pool problem and enable log activity

demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/java/org/apache/servicecomb/springboot/springmvc/client/TestAnnotationsSchema.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/AnnotationsSchema.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestAnnotationsSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/AnnotationsSchema.java
=> [#4268]add test case for issue

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/BeanUtils.java, spring-boot/spring-boot-starters/java-chassis-spring-boot-starter/src/main/java/org/apache/servicecomb/springboot2/starter/ServiceCombSpringConfiguration.java, transports/transport-rest/transport-rest-servlet/src/test/java/org/apache/servicecomb/transport/rest/servlet/TestCseXmlWebApplicationContext.java
=> [SCB-2868]bean init can specify user defined locations

demo/demo-zookeeper/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerController.java, demo/demo-zookeeper/consumer/src/main/java/org/apache/servicecomb/samples/ProviderService.java, demo/demo-zookeeper/provider/pom.xml, demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/ProviderController.java, demo/demo-zookeeper/provider/src/main/resources/application.yml, demo/demo-zookeeper/test-client/pom.xml, demo/demo-zookeeper/test-client/src/main/java/org/apache/servicecomb/samples/HelloWorldIT.java, dependencies/bom/pom.xml, dependencies/default/pom.xml, dynamic-config/config-zookeeper/pom.xml, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperClient.java, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperConfig.java, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperDynamicPropertiesSource.java, dynamic-config/config-zookeeper/src/main/resources/META-INF/services/org.apache.servicecomb.config.DynamicPropertiesSource, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigEnvironmentPostProcessor.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/Self.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistrationInstance.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosRegistration.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperDiscovery.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperRegistration.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperRegistryProperties.java
=> [SCB-2863]support zookeeper config

dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperClient.java, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperConfig.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperDiscovery.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperRegistration.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperRegistryProperties.java
=> [SCB-2863]support zookeeper authentication

dependencies/default/pom.xml, pom.xml
=> Bump spring boot from 3.0.7 to 3.1.10

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientOptionsSPI.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
=> [SCB-2872]Fix idle timeout for read and write is not properly set problem

dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperConfig.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperRegistryProperties.java
=> [SCB-2873]Fix zookeeper default address is not correct

README.md, README_ZH.md
=> update read me using api first example

demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/ProviderController.java, demo/demo-zookeeper/provider/src/main/resources/application.yml, demo/demo-zookeeper/test-client/src/main/java/org/apache/servicecomb/samples/HelloWorldIT.java, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperClient.java, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperConfig.java
=> [SCB-2874]Fix zookeeper config not read tag value

service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperDiscovery.java
=> [SCB-2877]Fix zookeeper cache instances by application name problem

core/src/main/java/org/apache/servicecomb/core/NonSwaggerInvocation.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/DiscoveryTree.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ExtensionsFactory.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ExtensionsManager.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalanceFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestExtensionsManager.java
=> [SCB-2878]operation based load balancer

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestThirdSvc.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/ThirdSvc.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/consumer/ConsumerArgumentsMapperCreator.java, swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/arguments/consumer/TestJaxrsV2V2.java, swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/arguments/consumer/TestSpringmvcV2V2.java
=> [#4334]fix invocation arguments not same with swagger arguments problem

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/OperationProtobuf.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/internal/converter/TestSchemaMetaCodec.java, common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/internal/converter/TestSchemaMetaCodecRestTemplate.java, core/src/main/java/org/apache/servicecomb/core/Invocation.java, core/src/main/java/org/apache/servicecomb/core/exception/DefaultExceptionProcessor.java, core/src/main/java/org/apache/servicecomb/core/governance/MatchType.java, core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java, core/src/main/java/org/apache/servicecomb/core/tracing/TraceIdLogger.java, core/src/test/java/org/apache/servicecomb/core/invocation/TestInvocationStageTrace.java, demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/CodeFirstPojoClient.java, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocationCreator.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/CustomHttpRequestParser.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/CustomHttpResponseParser.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/HttpClientRequestWrapper.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/HttpClientResponseWrapper.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/HttpServeRequestWrapper.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/TracingConfiguration.java, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/ZipkinTracingFilter.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/InvocationMetersInitializer.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/AbstractInvocationMeters.java, metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/SlowInvocationLogger.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestInvocationMetersInitializer.java, metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestSlowInvocationLogger.java
=> [SCB-2880]able to inherit trace in edge service from web

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationId.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistryConfiguration.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/Discovery.java, foundations/foundation-registry/src/test/java/org/apache/servicecomb/registry/TestDiscoveryManager.java, service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/Self.java, service-registry/registry-lightweight/src/test/java/org/apache/servicecomb/registry/lightweight/StoreServiceTest.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalDiscovery.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistrationInstance.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryConfiguration.java, service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosConfiguration.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscovery.java, service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosRegistration.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/registry/sc/SCDiscovery.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/registry/sc/SCRegistration.java, service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/ZeroConfigDiscovery.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperDiscovery.java, service-registry/registry-zookeeper/src/main/java/org/apache/servicecomb/registry/zookeeper/ZookeeperRegistration.java
=> [SCB-2882]add services discovery api and support global instance id bean

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestProducerInvocationFlow.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java, demo/demo-filter/filter-edge/src/main/resources/microservice.yaml, demo/demo-zookeeper/test-client/src/main/java/org/apache/servicecomb/samples/HelloWorldIT.java, edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeAddHeaderFilter.java
=> [SCB-2883]support trace id header in response

dependencies/default/pom.xml
=> Bump spring, spring boot, netty, vertx versions

demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/Application.java, demo/demo-local-registry/demo-local-registry-client/src/main/java/org/apache/servicecomb/demo/localRegistryClient/LocalRegistryServerTest.java, demo/demo-local-registry/demo-local-registry-client/src/main/resources/applications/demo-local-registry-cross/demo-local-registry-server-cross/ServerEndpoint.yaml, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceVersions.java
=> [#4375] Fix local registry not find cross app name alias

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessor.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestBodyProcessor.java, demo/demo-zookeeper/provider/pom.xml, demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/ReactiveStreamController.java, dependencies/default/pom.xml, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxUtils.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/HttpServletResponseEx.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/StandardHttpServletRequestEx.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/BufferInputStream.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/BufferOutputStream.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/tcp/TcpConnection.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestStream.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestVertxUtils.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/client/tcp/TestTcpClientConnection.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestStandardHttpServletRequestEx.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/stream/TestBufferInputStream.java, swagger/swagger-generator/generator-core/pom.xml, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/SwaggerGeneratorContext.java, swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/response/PublisherProcessor.java, swagger/swagger-generator/generator-core/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.generator.ResponseTypeProcessor, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayProducerInvocationFlow.java
=> [SCB-2885]generate content-type text/event-stream

demo/demo-schema/src/main/java/org/apache/servicecomb/demo/controller/PersonAlias.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestControllerImpl.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ControllerImpl.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseRequestCallback.java, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseRestTemplate.java
=> [#4378]Fix getForObject not properly handle response type

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestProducerInvocationFlow.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilterTest.java, core/src/main/java/org/apache/servicecomb/core/invocation/ProducerInvocationFlow.java, core/src/test/java/org/apache/servicecomb/core/invocation/ProducerInvocationFlowTest.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/AbstractHttpServletResponse.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/HttpServletResponseEx.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/StandardHttpServletResponseEx.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestStandardHttpServletResponseEx.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerResponseToHttpServletResponse.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayProducerInvocationFlow.java
=> [SCB-2885]refactoring buffer reader to support SSE

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceEventStreamProcessor.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessorManager.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java, demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/ReactiveStreamController.java, demo/demo-zookeeper/provider/src/main/resources/application.yml
=> [SCB-2885]support write SSE response

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceEventStreamProcessor.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/java/org/apache/servicecomb/springboot/springmvc/client/ReactiveStreamIT.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/java/org/apache/servicecomb/springboot/springmvc/client/ThirdSvcConfiguration.java, demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/ReactiveStreamController.java, demo/demo-zookeeper/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerReactiveStreamController.java, demo/demo-zookeeper/test-client/src/main/java/org/apache/servicecomb/samples/ReactiveStreamIT.java, demo/demo-zookeeper/test-client/src/main/java/org/apache/servicecomb/samples/ThirdSvcConfiguration.java, dependencies/default/pom.xml, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/AbstractHttpServletResponse.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestAbstractHttpServletResponse.java, transports/transport-rest/transport-rest-client/pom.xml, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientDecoder.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java, transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientTransportContext.java
=> [SCB-2885]support SSE from edge and servlet container

dependencies/default/pom.xml, foundations/foundation-test-scaffolding/src/main/java/io/vertx/core/impl/SyncContext.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpServer.java, foundations/foundation-vertx/src/test/java/io/vertx/ext/web/impl/TestHttpServerRequestUtils.java, foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/stream/TestPumpFromPart.java, transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java
=> Bump vertx.version from 4.4.8 to 4.5.8

dependencies/default/pom.xml, swagger/swagger-generator/generator-core/src/test/resources/schemas/ParameterAnnotation.yaml, swagger/swagger-generator/generator-core/src/test/resources/schemas/Schema.yaml, swagger/swagger-generator/generator-core/src/test/resources/schemas/pojoExample1.yaml, swagger/swagger-generator/generator-jaxrs/src/test/resources/schemas/ClassAnnotation.yaml, swagger/swagger-generator/generator-jaxrs/src/test/resources/schemas/echo.yaml, swagger/swagger-generator/generator-spring-data/src/test/resources/pageSchema.yaml, swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/TestTwoSameNameModels.java, swagger/swagger-generator/generator-springmvc/src/test/resources/schemas/DefaultParameterSchema.yaml, swagger/swagger-generator/generator-springmvc/src/test/resources/schemas/mixupAnnotations.yaml, swagger/swagger-generator/generator-springmvc/src/test/resources/schemas/responseEntity.yaml
=> Bump com.fasterxml.jackson:jackson-bom from 2.16.1 to 2.17.1

dependencies/default/pom.xml, handlers/handler-tracing-zipkin/pom.xml, handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/TracingConfiguration.java, pom.xml, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
=> Bump spring from 6.0.9 to 6.1.10 and spring boot from 3.1.10 to 3.3.1

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodec.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecCsv.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecMulti.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecPipes.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecSimple.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecSsv.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecTsv.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecWithDelimiter.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecsUtils.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java, common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestHeaderProcessor.java, common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestRestClientRequestImpl.java, demo/demo-schema/src/main/java/org/apache/servicecomb/demo/api/IHeaderParamWithListSchema.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/ConsumerHeaderParamWithListSchema.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-edge/src/main/resources/application.yml, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-server/src/main/java/org/apache/servicecomb/demo/zeroconfig/server/HeaderParamWithListSchema.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/HeaderParamWithListSchemaIT.java, demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/ServerTest.java
=> [#4405]header parameter support array type

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java
=> [SCB-2887]able to set max RST_STREAM per window

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/ZoneAwareDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceFilter2.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/TestZoneAwareDiscoveryFilter.java
=> [#4427]able to disable both consumer and provider zone-aware

core/src/main/java/org/apache/servicecomb/core/bootup/ConfigurationProblemsCollector.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ConfigurationProblemsCollectorTest.java, demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
=> [#4412]add alarms for using old deprecated configuration

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestFactoryBean.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/factory/ServiceBean.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/factory/ServiceFactoryBean.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/factory/ServiceWithReference.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/factory/ServiceWithReferenceImpl.java, demo/demo-springmvc/springmvc-client/src/test/java/org/apache/servicecomb/demo/springmvc/SpringMvcIT.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/FoundationConfigConfiguration.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/ProviderPojoConfiguration.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/RpcReferenceBeanDefinitionRegistry.java, providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/reference/RpcReferenceProcessor.java, providers/provider-pojo/src/test/java/org/apache/servicecomb/provider/pojo/reference/TestRpcReferenceProcessor.java, providers/provider-rest-common/src/main/java/org/apache/servicecomb/provider/rest/common/ProviderRestCommonConfiguration.java
=> [#2740]support factory bean eager injection of RpcReference

demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ConfigurationProblemsCollectorTest.java
=> [SCB-2889]fix service name can not have dot character

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/HttpUtils.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestControllerImpl.java
=> [#3008]add tests and documents that header should encoded when not ASCII

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/TestFormRequestSchema.java, demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/FormRequestSchema.java, demo/demo-jaxrs/jaxrs-server/src/main/resources/microservice.yaml, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java
=> [#4461]For netty changed add maxFormBufferedBytes & maxFormFields

LICENSE, common/common-protobuf/pom.xml, demo/demo-zookeeper/test-client/src/test/java/org/apache/servicecomb/samples/ZookeeperIT.java, dependencies/default/pom.xml, foundations/foundation-protobuf/pom.xml, foundations/foundation-protobuf/src/main/resources/google/protobuf/any.proto, foundations/foundation-protobuf/src/main/resources/google/protobuf/empty.proto, pom.xml
=> Exclude protobuf-java dependencies and keep only for test

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/LambdaUtils.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java
[#4471]shutdown nacos client when discovery destroy
=> [#4471]catch exception when Discovery and Registration service destroy

README.md, README_ZH.md, doap_servicecomb-java-chassis.rdf, solutions/solution-basic/src/main/java/org/apache/servicecomb/solution/basic/integration/ManagementEndpointImpl.java
=> update readme and minor fix

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDownloadSchema.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestUploadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/part/FilePart.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/FileUploadPart.java
=> [#4476]use more stable apis to create InputStream

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDownloadSchema.java, demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestUploadSchema.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/part/FilePart.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/FileUploadPart.java
=> [#4476]use more stable apis to create InputStream (#4478)

clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java
=> [#4510] fixed kie config center can not record fail state when connect exception problem

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java, clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/AbstractAddressManager.java, clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/event/EngineConnectChangedEvent.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/RBACBootStrapService.java, service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/TokenCacheManager.java
=> [#4517] fixed for cross engine authentication failed at dual-az servicecomb engine

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/ZoneAwareDiscoveryFilter.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceFilter2.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/TestZoneAwareDiscoveryFilter.java
=> [#4520]ratioCeiling defaults to 100-ratio

core/src/main/java/org/apache/servicecomb/core/provider/consumer/SyncResponseExecutor.java
=> [#4516]guard wait at least 30 seconds

common/common-access-log/src/main/java/org/apache/servicecomb/common/accessLog/core/element/impl/DurationMillisecondAccessItem.java, common/common-access-log/src/main/java/org/apache/servicecomb/common/accessLog/core/element/impl/DurationSecondAccessItem.java, common/common-access-log/src/test/java/org/apache/servicecomb/common/accessLog/core/element/impl/DurationMillisecondItemTest.java
=> [#4515]fix access log not correct when guard timeout

dependencies/default/pom.xml
=> Bump netty from 4.1.112.Final to 4.1.113.Final and vert.x from 4.5.9 to 4.5.10

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/resource/TestClassPathStaticResourceHandler.java
fix test case of :https://github.com/apache/servicecomb-java-chassis/pull/4555/files
=> ci: fix test of adapt linelint

NOTICE, distribution/src/release/NOTICE
=> Updated Notice file to 2024

dynamic-config/config-apollo/src/main/java/org/apache/servicecomb/config/apollo/ApolloDynamicPropertiesSource.java, dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/cc/ConfigCenterDynamicPropertiesSource.java, dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/KieDynamicPropertiesSource.java, dynamic-config/config-nacos/src/main/java/org/apache/servicecomb/config/nacos/NacosDynamicPropertiesSource.java, dynamic-config/config-zookeeper/src/main/java/org/apache/servicecomb/config/zookeeper/ZookeeperDynamicPropertiesSource.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/DynamicPropertiesSource.java, foundations/foundation-config/src/main/java/org/apache/servicecomb/config/InMemoryDynamicPropertiesSource.java
=> [#4560]change return type of create method in DynamicPropertiesSource

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/NamedThreadFactory.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java
=> Optimize discoveryManager to achieve code separation of concerns

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/InputStreamToReadStream.java, handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/FixedWindowStrategy.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerEnvironment.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/AbstractArgumentsMapperCreator.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/consumer/ConsumerArgumentsMapperCreator.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/producer/ProducerArgumentsMapperCreator.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/ResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/consumer/CompletableFutureConsumerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/consumer/CseResponseConsumerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/consumer/DefaultConsumerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/consumer/OptionalConsumerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/producer/CompletableFutureProducerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/producer/CseResponseProducerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/producer/DefaultProducerResponseMapperFactory.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/producer/OptionalProducerResponseMapperFactory.java, swagger/swagger-invocation/invocation-jaxrs/src/main/java/org/apache/servicecomb/swagger/invocation/jaxrs/response/JaxrsConsumerResponseMapperFactory.java, swagger/swagger-invocation/invocation-jaxrs/src/main/java/org/apache/servicecomb/swagger/invocation/jaxrs/response/JaxrsProducerResponseMapperFactory.java, swagger/swagger-invocation/invocation-springmvc/src/main/java/org/apache/servicecomb/swagger/invocation/springmvc/response/SpringmvcConsumerResponseMapperFactory.java, swagger/swagger-invocation/invocation-springmvc/src/main/java/org/apache/servicecomb/swagger/invocation/springmvc/response/SpringmvcProducerResponseMapperFactory.java, swagger/swagger-invocation/invocation-springmvc/src/test/java/org/apache/servicecomb/swagger/invocation/springmvc/response/TestSpringmvcProducerResponseMapper.java, swagger/swagger-invocation/invocation-springmvc/src/test/java/org/apache/servicecomb/swagger/invocation/springmvc/response/TestSpringmvcProducerResponseMapperFactory.java
- Modify the names of factories variables in multiple classes to factories to unify the naming style
- Update the factories parameter in the method signature to factories to maintain consistency
- Fixed typos in some variables and methods
=> refactor(invocation): Refactor response mapping factory method

service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscovery.java
=> [#4643]fix: Nacos can't discover instances

swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/ws/AbstractBaseWebSocket.java, swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/ws/WebSocket.java, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/ws/VertxWebSocketAdaptor.java
=> [SCB-2894] optimize the WebSocket closing scene race condition

.github/workflows/maven.yml
=> [#4690] fixed mixin-maven-plugin not work with maven 3.9.9+ and 4.0.0+ problem

demo/demo-consul/test-client/pom.xml, demo/demo-etcd/test-client/pom.xml, demo/demo-filter/filter-tests/pom.xml, demo/demo-nacos/test-client/pom.xml, demo/demo-zookeeper/test-client/pom.xml
=> [#4690]remove not updated mixin-maven-plugin

foundations/foundation-test-scaffolding/src/main/java/io/vertx/core/impl/SyncContext.java, foundations/foundation-vertx/src/test/java/io/vertx/ext/web/impl/TestHttpServerRequestUtils.java
=> [#4717]Bump vertx from 4.5.10 to 4.5.13

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceVersions.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java, handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java
[perf]When a microservice instance is isolated and taken offline, reduce unnecessary network communication
---
=> [perf]When a microservice instance is isolated and taken offline, reduce unnecessary network communication

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java
=> [#4779] add filter by SPIEnabled

core/src/main/java/org/apache/servicecomb/core/BootListener.java
the current version no longer has the Handler mechanism, so the related interfaces are deleted.
---
=> delete the expired interfaces

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java
when the update of service properties fails, change the prompt message from `update service instance status fails` to `update service properties fails`.
---
=> modify the prompt message

README.md, README_ZH.md
=> add core dependencies

README.md, README_ZH.md
=> remove duplicate info

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/AbstractAddressManager.java, clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterWatch.java, core/src/main/java/org/apache/servicecomb/core/Invocation.java, core/src/main/java/org/apache/servicecomb/core/executor/GroupExecutor.java, demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/cache/VersionedCache.java, foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/IpPort.java, foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/discovery/DiscoveryTreeNode.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/tcp/AbstractTcpClientPackage.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultClientEndpointMetric.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/InputStreamToReadStream.java, foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/OutputStreamToWriteStream.java, handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/SessionStickinessRule.java, pom.xml, transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java
=> spot bugs repair

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/CodeFirstRestTemplateJaxrs.java, dependencies/default/pom.xml, pom.xml, providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
=> Bump spring boot from 3.3.5 to 3.4.5

core/src/test/java/org/apache/servicecomb/core/filter/impl/ProducerOperationFilterTest.java, dependencies/default/pom.xml, foundations/foundation-ssl/src/test/java/org/apache/servicecomb/foundation/ssl/KeyStoreUtilTest.java
=> remove okhttp3 dependency management

dependencies/default/pom.xml, transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/MockHttpServerResponse.java
=> [#4930] upgrade vertx to 4.5.21, netty version to 4.1.127.Final

pom.xml
=> Bump com.github.spotbugs:spotbugs-maven-plugin from 4.9.3.2 to 4.9.4.0
