demo/demo-spring-boot-discovery/demo-spring-boot-discovery-client/src/test/resources/microservice.yaml
demo/demo-spring-boot-discovery/demo-spring-boot-discovery-server/src/main/resources/microservice.yaml
demo/demo-spring-boot-discovery/demo-spring-boot-zuul-proxy/src/test/resources/application.yml
demo/demo-spring-boot-discovery/demo-spring-boot-zuul-proxy/src/test/resources/microservice.yaml

cse service port among all demos except demo-spring-boot-discovery is 9980, is it a good idea to keep it the same among all demos?

changed service port to 9980

---

foundation-common/src/main/java/io/servicecomb/foundation/common/utils/FileUtils.java
foundation-common/src/test/java/io/servicecomb/foundation/common/utils/TestFileUtils.java
foundation-config/src/main/java/io/servicecomb/config/archaius/sources/AbstractConfigLoader.java
foundation-config/src/test/java/io/servicecomb/config/TestConfigUtil.java
service-registry/src/main/java/io/servicecomb/serviceregistry/api/registry/Microservice.java
service-registry/src/main/java/io/servicecomb/serviceregistry/definition/MicroserviceDefinition.java
service-registry/src/test/java/io/servicecomb/serviceregistry/definition/TestMicroserviceDefinitionManager.java

if a microservice.yaml path is : file:/....../target/classes/microservice.yaml
then root path is : ....../target/classes
if a class (io.servicecomb.demo.jaxrs.server.ComputeImpl) is in file:/....../target/classes/io/servicecomb/demo/jaxrs/server/
then root path is : ....../target/classes
when resource is in a jar, then the root is the jar path.
file:/....../repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar!/org/apache/commons/lang/
root path is : ....../repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar

JAV-102 find resource root path

---

core/src/main/java/io/servicecomb/core/executor/FixedThreadExecutor.java
core/src/main/java/io/servicecomb/core/provider/consumer/SyncResponseExecutor.java
demo/demo-perf-client/src/main/java/io/servicecomb/demo/client/perf/ClientThread.java
demo/demo-perf-client/src/main/java/io/servicecomb/demo/client/perf/PerfClient.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/server/TcpServerConnection.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/tcp/TcpConnection.java
foundations/foundation-vertx/src/main/java/io/vertx/core/net/impl/VertxHelper.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/TestTcp.java
integration-tests/tracing-tests/src/test/java/io/servicecomb/tests/tracing/TracedJaxrsController.java
transports/transport-highway/src/main/java/io/servicecomb/transport/highway/HighwayServerConnection.java
transports/transport-highway/src/main/java/io/servicecomb/transport/highway/HighwayServerInvoke.java
transports/transport-highway/src/test/java/io/servicecomb/transport/highway/TestHighwayServerConnection.java
transports/transport-highway/src/test/java/io/servicecomb/transport/highway/TestHighwayServerInvoke.java

use CAS queue to:
1.avoid vertx socket write lock
2.reduce netty io task count
add config for default executor

Highway performance

---

service-registry/src/main/java/io/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
service-registry/src/test/java/io/servicecomb/serviceregistry/task/TestMicroserviceRegisterTask.java

avoid NullPointerException in register task.

JAV-214 avoid NullPointerException in register task, let it try to register again

---

service-registry/src/main/java/io/servicecomb/serviceregistry/config/AbstractPropertiesLoader.java
service-registry/src/test/java/io/servicecomb/serviceregistry/config/TestPropertiesLoader.java

read new correct config item first
if value is empty, then read old wrong config item.

JAV-141 resolve spelling mistake for configuration item problem

---

foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/VertxUtils.java
foundations/foundation-vertx/src/main/java/io/vertx/core/impl/VertxImplEx.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/TestClient.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/TestTcp.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/TestVertex.java

previous name is "vert.x-eventloop-thread-{number}"
new name is "{name}-vert.x-eventloop-thread-{number}"

JAV-221 make vertx eventloop thread name related to vertx name

---

core/src/main/java/io/servicecomb/core/definition/schema/ConsumerSchemaFactory.java

if SDK cann't connect to SC successfully at the fist time when SDK initialize ConsumerProviderManager , without throw exception at first time the retry thread never try to connect to SC any more, because some properties have been initialized.

【JAV-281】cann't reconnect to SC at retry thread.

---

samples/bmi/calculator/pom.xml
samples/bmi/calculator/src/main/java/io/servicecomb/samples/bmi/HalfCalculatorServiceImpl.java
samples/bmi/webapp/pom.xml
samples/bmi/webapp/src/main/java/io/servicecomb/samples/bmi/filters/CseHeaderFilter.java
samples/bmi/webapp/src/main/resources/static/index.html

1. added profiles for different dependencies
2. added profiles to switch different implementation of calculator
3. added zuul filter to enable the flow control capability
Configurations in `microservice.yaml` can not be declared as profiles in `application.yaml`. We have to use the very very long program arguments as the application startup parameters.

added profiles for samples

---

common/common-rest/src/main/java/io/servicecomb/common/rest/codec/param/BodyProcessorCreator.java

Media type which is not application/json, like text/plain and some self defined media types, can not be processed as JSON.

[Body Type]Take non-JSON body as plain text

---

foundations/foundation-common/pom.xml
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/event/EventManager.java
foundations/foundation-common/src/test/java/io/servicecomb/foundation/common/event/TestEventManager.java
service-registry/pom.xml
service-registry/src/main/java/io/servicecomb/serviceregistry/RegistryUtils.java
service-registry/src/main/java/io/servicecomb/serviceregistry/task/MicroserviceInstanceHeartbeatTask.java
service-registry/src/main/java/io/servicecomb/serviceregistry/task/event/HeartbeatFailEvent.java

added event manager to subscribe and publish events in java chassis

JAV-408 Event manager added for chassis events

---

demo/docker-build-config/pom.xml
demo/docker-run-config/pom.xml
tracing/tracing-common/src/main/java/io/servicecomb/tracing/Span.java
tracing/tracing-zipkin/src/main/java/io/servicecomb/tracing/zipkin/ZipkinSpanAspect.java
tracing/tracing-zipkin/src/test/java/io/servicecomb/tracing/zipkin/ZipkinSpanAspectTest.java
tracing/tracing-zipkin/src/test/java/io/servicecomb/tracing/zipkin/app/ZipkinSpanTestApplication.java

Just let the user to override the default setting of span name and callPath.

JAV-389 Add spanName and callPath attribute in the span annoation.

---

swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/SwaggerGenerator.java
swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/TestApiOperation.java
swagger/swagger-generator/generator-jaxrs/src/test/java/io/servicecomb/swagger/generator/jaxrs/Echo.java
swagger/swagger-generator/generator-jaxrs/src/test/java/io/servicecomb/swagger/generator/jaxrs/TestJaxrs.java
swagger/swagger-generator/generator-jaxrs/src/test/resources/schemas/emptyContract.yaml
swagger/swagger-generator/generator-springmvc/src/test/java/io/servicecomb/swagger/generator/springmvc/MethodEmptyPath.java

This issue turns out to be a bug. When the apiOperation is neither null nor hidden, methods annotates with ApiOperation will publish as a service.

JAV-403 ignored non-rest style interfaces using @RestSchema

---

integration-tests/springmvc-tests/src/test/java/io/servicecomb/demo/springmvc/tests/endpoints/CodeFirstSpringmvcSimplifiedMappingAnnotation.java
integration-tests/springmvc-tests/src/test/java/io/servicecomb/demo/springmvc/tests/endpoints/ControllerSimplifiedMappingAnnotationImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/RegistryUtils.java
service-registry/src/main/java/io/servicecomb/serviceregistry/ServiceRegistry.java
service-registry/src/main/java/io/servicecomb/serviceregistry/api/registry/MicroserviceFactory.java
service-registry/src/main/java/io/servicecomb/serviceregistry/definition/DefinitionConst.java
service-registry/src/main/java/io/servicecomb/serviceregistry/definition/MicroserviceDefinition.java
service-registry/src/main/java/io/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java
service-registry/src/test/java/io/servicecomb/serviceregistry/registry/TestLocalServiceRegistry.java
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/SwaggerGenerator.java
transports/transport-rest/transport-rest-servlet/src/test/java/io/servicecomb/transport/rest/servlet/TestServletRestTransport.java

fixed typos and removed unnecessary imports

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/net/NetUtils.java

Signed-off-by: MabinGo bin.ma@huawei.com

Report error instead of warning if rest/highway address format is invalid

---

spring-boot-starter/spring-cloud-zuul-zipkin/src/main/java/io/servicecomb/spring/cloud/zuul/tracing/SpringTracingConfiguration.java

There was no public class in this module because of which JavaDoc gives error in Deployment Process.

JAV-409 Fix JavaDoc Error for Spring-Cloud-Zuul-Zipkin

---

service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/AppManager.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/DefaultMicroserviceVersionFactory.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceManager.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersion.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersionFactory.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersionRule.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersions.java
service-registry/src/main/java/io/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java
service-registry/src/main/java/io/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java
service-registry/src/main/java/io/servicecomb/serviceregistry/task/MicroserviceWatchTask.java
service-registry/src/main/java/io/servicecomb/serviceregistry/task/event/PeriodicPullEvent.java
service-registry/src/main/java/io/servicecomb/serviceregistry/task/event/PullMicroserviceVersionsInstancesEvent.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersionTestUtils.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/TestAppManager.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/TestDefaultMicroserviceVersionFactory.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/TestMicroserviceManager.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/TestMicroserviceVersion.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/TestMicroserviceVersionRule.java
service-registry/src/test/java/io/servicecomb/serviceregistry/consumer/TestMicroserviceVersions.java
service-registry/src/test/java/io/servicecomb/serviceregistry/registry/TestRemoteServiceRegistry.java

1.support multiple versionRules for one microservice
2.can get latest microservice information inside a versionRule
3.can get latest instances inside a versionRule, and can determined if intances changed.
4.work with pull mode.
5.trigger pull when serviceRegistry connection recovery

JAV-454 enhanced cache manager

---

common/common-rest/src/main/java/io/servicecomb/common/rest/RestConst.java
common/common-rest/src/main/java/io/servicecomb/common/rest/RestProducerInvocation.java
common/common-rest/src/test/java/io/servicecomb/common/rest/TestRestProducerInvocation.java
demo/demo-perf-client/src/main/resources/microservice.yaml
transports/transport-rest/transport-rest-servlet/src/main/java/io/servicecomb/transport/rest/servlet/RestAsyncListener.java
transports/transport-rest/transport-rest-servlet/src/test/java/io/servicecomb/transport/rest/servlet/TestRestAsyncListener.java

1.receive a servlet request, start async and dispatch to executor
2.if business is slow, then web container will call async timeout and recycled resources
　　but in this time, resources maybe in executor's queue or executing
　　that will cause many strange problems, like request not support async or some NullException

JAV-474 fix servlet timeout concurrent problems

---

common/common-rest/src/main/java/io/servicecomb/common/rest/AbstractRestInvocation.java

if return the content-lengh from server, can't change the body, so remove this header

JAV-489 resolve Edge service return Cotent-Length error

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/net/NetUtils.java

If user specified the rest address as 0.0.0.0, NetUtils will choose an available address as the registry rest address.

[JAV-490]Fix the rest address binding logic.

---

foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/http/VertxClientRequestToHttpServletRequest.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/http/TestVertxClientRequestToHttpServletRequest.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/http/TestVertxServerRequestToHttpServletRequest.java
providers/provider-rest-common/src/main/java/io/servicecomb/provider/rest/common/InvocationToHttpServletRequest.java
providers/provider-rest-common/src/test/java/io/servicecomb/provider/rest/common/TestInvocationToHttpServletRequest.java

return "", not throw a exception

JAV-505 HttpServletReqeust.getContextPath returns the default value ""

---

common/common-rest/src/main/java/io/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/main/java/io/servicecomb/common/rest/RestProducerInvocation.java
common/common-rest/src/test/java/io/servicecomb/common/rest/TestAbstractRestInvocation.java
common/common-rest/src/test/java/io/servicecomb/common/rest/TestRestProducerInvocation.java
demo/demo-edge/edge-service/src/main/java/io/servicecomb/demo/edge/service/EdgeDispatcher.java
edge/edge-core/src/main/java/io/servicecomb/edge/core/EdgeInvocation.java
edge/edge-core/src/test/java/io/servicecomb/edge/core/TestEdgeInvocation.java
foundations/foundation-metrics/src/test/java/io/servicecomb/foundation/metrics/TestMetricsServoRegistry.java
service-registry/src/test/java/io/servicecomb/serviceregistry/api/TestConst.java
transports/transport-rest/transport-rest-servlet/src/main/java/io/servicecomb/transport/rest/servlet/RestServletProducerInvocation.java
transports/transport-rest/transport-rest-servlet/src/test/java/io/servicecomb/transport/rest/servlet/TestRestServletProducerInvocation.java

use the same mechanism of normal microservice producer
before optimize, edge's decode and filter run in net thread.

JAV-524 Optimize edge executor

---

transports/transport-rest/transport-rest-client/src/main/java/io/servicecomb/transport/rest/client/RestTransportClient.java
transports/transport-rest/transport-rest-client/src/main/java/io/servicecomb/transport/rest/client/TransportClientConfig.java
transports/transport-rest/transport-rest-client/src/test/java/io/servicecomb/transport/rest/client/TestRestTransportClient.java
transports/transport-rest/transport-rest-vertx/src/main/java/io/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/io/servicecomb/transport/rest/vertx/TransportConfig.java

keepalive, idle timeout and poolsize give configuration support and add default timeout values to http client and server

[JAV-527]keepalive, idle timeout and poolsize give configuration support

---

handlers/handler-loadbalance/src/main/java/io/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/io/servicecomb/loadbalance/CseServer.java
handlers/handler-loadbalance/src/main/java/io/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/main/java/io/servicecomb/loadbalance/filter/IsolationServerListFilter.java
handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/TestCseServer.java
handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/TestLoadbalanceHandler.java
handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/filter/TestIsolationServerListFilter.java

add a continuous failure threshold configuration

JAV-503 optimize logic of load balance isolation

---

core/src/main/java/io/servicecomb/core/handler/ShutdownHookHandler.java

`responseCounter.incrementAndGet()` can be executed in finally block instead of being called twice in the try block.

used finally to execute common codes

---

.gitignore
common/common-javassist/src/test/java/io/servicecomb/common/javassist/TestJavassistUtils.java

* remove unused method definition.
* add IDEA project to gitignore file
* make it readable about {}

remove unused code of TestJavassistUtils and make it readable 

---

common/common-rest/src/main/java/io/servicecomb/common/rest/definition/RestOperationMeta.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/MetricsServoRegistry.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/output/servo/SimpleMetricsContentConvertor.java
foundations/foundation-metrics/src/test/java/io/servicecomb/foundation/metrics/TestFileOutputMetricObserverAndContentConvertor.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/AsyncResultCallback.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/server/TcpParser.java
foundations/foundation-vertx/src/main/java/io/vertx/ext/web/impl/MimeTypesUtils.java
foundations/foundation-vertx/src/test/java/io/servicecomb/foundation/vertx/TestTcp.java
foundations/foundation-vertx/src/test/java/io/vertx/ext/web/impl/TestMimeTypesUtils.java
java-chassis-dependencies/pom.xml

it's netty's bug.
latest vertx had upgrade netty dependence.
we can upgrade to latest vertx 3.5.0

JAV-543 Fix dns resolve

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/base/ServiceCombConstants.java
foundations/foundation-config/src/main/java/io/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/test/java/io/servicecomb/config/TestConfigUtil.java

check https://servicecomb.atlassian.net/browse/jav-550 for details.. I also submit a discussion topic in google group for this issue

JAV-550 support use _ to represent system environment variable config levels

---

core/src/main/java/io/servicecomb/core/CseApplicationListener.java
core/src/test/java/io/servicecomb/core/TestCseApplicationListener.java

I've thought about several solutions on this issue.
- move sending AFTER_REGISTRY logic into ServiceCenterTask. But this means ServiceCenterTask need to get the instance of CseApplicationListener, and triggerEvent() of CseApplicationListener has to be changed to public.
- move sending AFTER_REGISTRY logic into a call-back function and pass it to ServiceCenterTask. When instance registry is completed, this function should be called. But this will change several Class from RegistryUtils to ServiceCenterTask.
I think both of them are not good. So I choose to write an anonymous subscriber and let it to listen to MicroserviceInstanceRegisterTask. Maybe this is the solution with the minimum change of code.

JAV-546 register an anonymous subscriber to listen to instance registry event and trigger AFTER_REGISTRY event

---

foundations/foundation-ssl/src/main/java/io/servicecomb/foundation/ssl/SSLOption.java
foundations/foundation-ssl/src/test/java/io/servicecomb/foundation/ssl/SSLOptionTest.java

[JAV-554]Fix bug that when booting use java system properties for ssl configuration

---

common/common-rest/src/main/java/io/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java
common/common-rest/src/test/java/io/servicecomb/common/rest/codec/param/TestHeaderProcessor.java
providers/provider-springmvc/src/main/java/io/servicecomb/provider/springmvc/reference/RestTemplateCopyHeaderFilter.java
providers/provider-springmvc/src/test/java/io/servicecomb/provider/springmvc/reference/TestRestTemplateCopyHeaderFilter.java

---
see details in [https://servicecomb.atlassian.net/browse/JAV-560]
Check null arguments in invocation and do not copy them into requests to avoid NullPointerException in Netty.
My test demo is here: [https://github.com/yhs0092/javachassis-demo-header-transport]

[JAV-560] fix null header process logic on consumer side

---

service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/RequestParam.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/RestUtils.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/test/java/io/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java

场景：挂起一个服务中心实例，心跳超时。在域名的情况下，下次心跳还可能访问到该实例，从而导致心跳过期，实例被移除。
需要优化的措施：心跳单独设置超时时间，比如3s，和其他请求使用不一样的超时时间。

[JAV-567] Change the timeout of heartbeat request

---

handlers/handler-loadbalance/src/main/java/io/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/TestLoadbalanceHandler.java

[JAV-585]Loadbalance rule dynamic configuration is not work at some time

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/MicroserviceFactory.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestMicroserviceFactory.java

---
See details in [https://issues.apache.org/jira/browse/SCB-264](https://issues.apache.org/jira/browse/SCB-264).
If the item `service_description.description` in microservice.yaml contains `,`, it will be split into an array and only the first part will be registered to ServiceCenter. 
To avoid this problem, the array should be combined into the raw description.

[SCB-264] fix microservice description register problem

---

integration-tests/test-common/src/test/java/org/apache/servicecomb/tests/tracing/TracingTestBase.java

The zipkin reporter is asynchronous, and there is no gurarantee when
the metrics will be reported to the server. Just sleep for 5 seconds
before quering should be enough for our simple test case scenario.
---

SCB-293 sleep before quering in tracing test

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterConfig.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConnFailEvent.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConnSuccEvent.java
dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/client/TestConfigCenterClient.java

---
merge modification of config center client from commercial edition to open source edition

[SCB-322] merge config center modification

---

NOTICE
foundations/foundation-vertx/src/main/java/io/vertx/ext/web/impl/MimeTypesUtils.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/InputStreamToReadStream.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/property/AbstractBaseIntegerProperty.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java

Some files are forked from third parties. Modified those files' headers
to clarify the license and copyright information. Also updated NOTICE
to show their copyright information and origin.
---

[SCB-260] Clarify original copyright of some files

---

NOTICE
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/HystrixCommandPropertiesExt.java

The majority of the HystrixCommandPropertiesExt class is forked
from the base class. Thus we need to keep the original copyright.
---

SCB-260 Clarify copyright of HystrixCommandPropertiesExt

---

samples/metrics-write-file-sample/metrics-write-file/src/main/java/org/apache/servicecomb/samples/mwf/SimpleFileContentConvertor.java

---
Add status code to metrics output file name for better effect
before :
mwf.mwf-log4j-springboot.mwf-log4j-springboot.demoServiceEndpoint.fun.producer.execution.latency.dat
now :
mwf.mwf-log4j-springboot.mwf-log4j-springboot.demoServiceEndpoint.fun.producer.execution.latency.*(status code like 200)*.dat

[SCB-356] update metrics write file samples : add status code to file name

---

foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/event/TestEventBus.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/publish/Metric.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/health/TestHealthCheckerManager.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/TestMetric.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/TestMetricNode.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/TestMetricsLoader.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/MonitorManager.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestHealthCheckerPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestMonitorManager.java

---
User can register monitor only name without any tags like :
*MonitorManager.getInstance().getCounter("MonitorWithoutAnyTag");*
In this case output metric id will be **MonitorWithoutAnyTag)** , correct output metric id is **MonitorWithoutAnyTag** ,not include a **')'**
Also fix MetricsLoader load this style of metric id.

[SCB-358] fix bug for monitor output id that register only name without any tags

---

core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/AccessLogGenerator.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/AccessLogItemFactory.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/creator/AccessLogItemCreator.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/creator/PercentagePrefixConfigurableItemCreator.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/creator/SimpleAccessLogItemCreator.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/DatetimeConfigurableItem.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/DurationMillisecondItem.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/DurationSecondItem.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/PlainTextItem.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/AccessLogGeneratorTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/AccessLogItemFactoryTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/creator/PercentagePrefixConfigurableItemCreatorTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/DatetimeConfigurableItemTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/DurationMillisecondItemTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/DurationSecondItemTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/parser/impl/DefaultAccessLogPatternParserTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/parser/matcher/SimpleItemMatcherTest.java

---
fix compilation warning in access log module.
warning in EventBus.java and MonitorManager.java will be fixed by zhengyangyong.

SCB-361 fix access log compilation warning

---

metrics/metrics-integration/metrics-prometheus/src/main/java/org/apache/servicecomb/metrics/prometheus/MetricsHttpPublisher.java
metrics/metrics-integration/metrics-prometheus/src/test/java/org/apache/servicecomb/metrics/prometheus/TestMetricsHttpPublisher.java

---
Before:
```yaml
servicecomb:
metrics:
prometheus:
port: 9696
```
Now:
```yaml
servicecomb:
metrics:
prometheus:
address: localhost:9696
```

[SCB-372] support user set metrics prometheus exporter address not only port

---

samples/config-apollo-sample/README.md

[SCB-29] add README document for config-apollo

---

foundations/foundation-vertx/pom.xml

Vertx uses some static fields which will cause problems if resued.
Disabled surefire fork for foundation-vertx to avoid this issue.
---

[SCB-381] Fix foundation-vertx UT failure

---

java-chassis-distribution/src/release/LICENSE
java-chassis-distribution/src/release/NOTICE
java-chassis-distribution/src/release/licenses/NOTICE-apache-commons-codec
java-chassis-distribution/src/release/licenses/NOTICE-netty
java-chassis-distribution/src/release/licenses/NOTICE-prometheus
java-chassis-distribution/src/release/licenses/NOTICE-protostuff
java-chassis-distribution/src/release/licenses/NOTICE-tomcat

[SCB-260] Add third party notice

---

samples/metrics-extend-healthcheck/README.md
samples/metrics-write-file-sample/README.md

---
add how to run metrics samples and fix output path of metrics write file sample

[SCB-386] fix metrics samples readme

---

spring-boot-starter/spring-boot-starter-discovery/src/main/java/org/apache/servicecomb/springboot/starter/discovery/CseDiscoveryClientConfiguration.java

Now user can disable the discovery client with below configuration:
```
servicecomb:
discoveryClient:
enabled: false
```

SCB-405 support to disable the discovery client with configuration

---

foundations/foundation-common/src/main/java/com/google/common/eventbus/SimpleEventBus.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/event/EventManager.java
foundations/foundation-common/src/test/java/com/google/common/eventbus/TestSimpleEventBus.java

[SCB-360] write simpler eventBus to optimize performance

---

samples/codefirst-sample/codefirst-consumer/src/main/resources/META-INF/spring/codefirst.consumer.bean.xml
samples/codefirst-sample/codefirst-provider/src/main/resources/META-INF/spring/codefirst.provider.bean.xml
samples/custom-handler-sample/custom-handler-consumer/src/main/resources/META-INF/spring/customhandler.consumer.bean.xml
samples/custom-handler-sample/custom-handler-provider/src/main/resources/META-INF/spring/customhandler.provider.bean.xml
samples/jaxrs-sample/jaxrs-consumer/src/main/resources/META-INF/spring/jaxrs.consumer.bean.xml
samples/jaxrs-sample/jaxrs-provider/src/main/resources/META-INF/spring/jaxrs.provider.bean.xml
samples/pojo-sample/pojo-consumer/src/main/resources/META-INF/spring/pojo.consumer.bean.xml
samples/pojo-sample/pojo-provider/src/main/resources/META-INF/spring/pojo.provider.bean.xml
samples/springmvc-sample/springmvc-consumer/src/main/resources/META-INF/spring/springmvc.consumer.bean.xml
samples/springmvc-sample/springmvc-provider/src/main/resources/META-INF/spring/springmvc.provider.bean.xml

---
**most of them named "pojo.xxx",seems copy & paste and may make confusion**

[SCB-399] fix incorrect file name of spring bean xml in samples

---

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/SPIServiceUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/SPIServiceDef0Impl.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/TestSPIServiceUtils.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrap.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceManager.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/CompositeSwaggerGeneratorContext.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/ResponseMapperFactorys.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/VertxHttpMethod.java
transports/transport-rest/transport-rest-servlet/src/test/java/org/apache/servicecomb/transport/rest/servlet/TestRestServletProducerInvocation.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/AbstractVertxHttpDispatcher.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java

1.cache SPI service instances, avoid create new instance every time
2.support find special IPML instance

[SCB-447] Optimize SPIServiceUtils

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/IpPortManager.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RequestContext.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java

---
This PR is intend to optimize autoDiscovery function. as we know ,now we use retry at the first time sdk fail to register sc . when deployed in multi sc ( more than one sc instance ) enviroment , one sc instance breakup, this stategy exhausts lot of time to switch ip to next one , so i think it better to retry all the loop-ips in enviroment so that sdk can meet the health sc intance.
@liubao68 @wujimin @WillemJiang

[SCB-444]try to optimize autoDiscovery function

---

.gitignore
samples/bmi/README.md
samples/bmi/build.gradle
samples/bmi/calculator/build.gradle
samples/bmi/settings.gradle
samples/bmi/webapp/build.gradle
samples/codefirst-sample/README.md
samples/codefirst-sample/build.gradle
samples/codefirst-sample/codefirst-consumer/build.gradle
samples/codefirst-sample/codefirst-provider/build.gradle
samples/codefirst-sample/settings.gradle

Signed-off-by: Eric Lee <dagang.li@huawei.com>
---

SCB-457 demostrate how to run spring boot/non spring boot application with gradle

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigurationSpringInitializer.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigUtil.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigurationSpringInitializer.java
integration-tests/spring-jaxrs-tests/src/test/java/org/apache/servicecomb/demo/jaxrs/tests/JaxrsSpringIntegrationTest.java
integration-tests/spring-jaxrs-tests/src/test/resources/application-dev.yaml
integration-tests/spring-jaxrs-tests/src/test/resources/application-prod.yaml
integration-tests/spring-jaxrs-tests/src/test/resources/application.properties
integration-tests/spring-jaxrs-tests/src/test/resources/application.yaml
integration-tests/spring-jaxrs-tests/src/test/resources/application.yml
integration-tests/spring-jaxrs-tests/src/test/resources/microservice.yaml
integration-tests/spring-zuul-tracing-tests/src/test/java/org/apache/servicecomb/spring/cloud/zuul/tracing/SpringCloudZuulTracingTest.java
integration-tests/spring-zuul-tracing-tests/src/test/java/org/apache/servicecomb/spring/cloud/zuul/tracing/TracedController.java
integration-tests/spring-zuul-tracing-tests/src/test/resources/application-dev.yaml
integration-tests/spring-zuul-tracing-tests/src/test/resources/application-prod.yaml
integration-tests/spring-zuul-tracing-tests/src/test/resources/application.yaml
integration-tests/spring-zuul-tracing-tests/src/test/resources/application.yml
integration-tests/spring-zuul-tracing-tests/src/test/resources/microservice.yaml

---
Support reading ServiceComb configurations from application.yaml/application.properties
See [SCB-453](https://issues.apache.org/jira/browse/SCB-453)

[SCB-453] Read config from application yaml properties

---

core/src/main/java/org/apache/servicecomb/core/tracing/BraveTraceIdGenerator.java
core/src/test/java/org/apache/servicecomb/core/tracing/BraveTraceIdGeneratorTest.java
handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/ZipkinProviderDelegate.java
handlers/handler-tracing-zipkin/src/test/java/org/apache/servicecomb/tracing/zipkin/ZipkinProviderDelegateTest.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/TraceIdItem.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/impl/AccessLogHandler.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/trace/TracePrepareHandler.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/TraceIdItemTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/trace/TracePrepareHandlerTest.java

---
See details in [SCB-516](https://issues.apache.org/jira/browse/SCB-516).
- add a TracePrepareHandler to set traceId
- make TraceIdItem can get traceId from request headers

[SCB-516] fix accessLog traceId printing problem in EdgeService

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigUtil.java
foundations/foundation-config/src/test/resources/microservice.yaml
integration-tests/spring-jaxrs-tests/src/test/resources/application.properties
integration-tests/spring-jaxrs-tests/src/test/resources/microservice.yaml
integration-tests/spring-zuul-tracing-tests/src/test/resources/application.properties
integration-tests/spring-zuul-tracing-tests/src/test/resources/microservice.yaml

---
See [SCB-521](https://issues.apache.org/jira/browse/SCB-521)
Config of SpringBoot should takes higher priority than microservice.yaml, so that the users converting SpringBoot project to ServiceComb don't have to add microservice.yaml to override the default config.
They can just write config in application.properties/yaml

[SCB-521] Config of Spring Boot should takes higher priority than microservice.yaml

---

java-chassis-dependencies/pom.xml

---
It's a mistake that is unnecessary for add archetypes into java-chassis-dependencies, we need delete them.
```xml
<dependency>
<groupId>org.apache.servicecomb.archetypes</groupId>
<artifactId>business-service-jaxrs-archetype</artifactId>
<version>1.0.0-m2-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>org.apache.servicecomb.archetypes</groupId>
<artifactId>business-service-pojo-archetype</artifactId>
<version>1.0.0-m2-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>org.apache.servicecomb.archetypes</groupId>
<artifactId>business-service-springmvc-archetype</artifactId>
<version>1.0.0-m2-SNAPSHOT</version>
</dependency>
<dependency> …
```

[SCB-540] delete archetypes in java-chassis-dependencies pom

---

archetypes/README.md

---
update generate from snapshot repo command

[SCB-587] Fix archetypes readme

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java

---
huawei's huangyun set up an agent to modify the special characters '#'，which led to the governance inoperative

 [SCB-591] configcenter need to do encode

---

demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/Consumer.java
demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/ConsumerMain.java
demo/demo-edge/edge-service/src/main/resources/microservice.yaml
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/DefaultEdgeDispatcher.java
edge/edge-core/src/main/resources/META-INF/services/org.apache.servicecomb.transport.rest.vertx.VertxHttpDispatcher
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestServiceAndVersionDispatcher.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxHttpDispatcher.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestDispatcher.java

[SCB-611]Provide a default Dispatcher to make user using edge service easier

---

core/src/main/java/org/apache/servicecomb/core/transport/AbstractTransport.java
core/src/test/java/org/apache/servicecomb/core/transport/TestAbstractTransport.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java
demo/demo-jaxrs/jaxrs-client/src/main/resources/microservice.yaml
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/RequestClientTimeOut.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayClient.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-627] Client Request Timeout support for operation/schema/service level

---

edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestURLMappedEdgeDispatcher.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/ServiceCombConstants.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigMapping.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/YAMLUtil.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/archaius/sources/MicroserviceConfigurationSource.java
foundations/foundation-config/src/main/resources/mapping.yaml
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigMapping.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigUtil.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/archaius/sources/TestYAMLConfigurationSource.java
foundations/foundation-config/src/test/resources/mapping.yaml
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/TestSwaggerUtils.java

[SCB-636] change config mapping machanism

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/ServiceCombConstants.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/MicroserviceInstance.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/ServiceRegistryClient.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/Holder.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImplTest.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/task/TestMicroserviceRegisterTask.java

---
See details in [SCB-652](https://issues.apache.org/jira/browse/SCB-652)
- change environment config item from "instance_description.environment" to "service_description.environment"
- improve schema compare and register logic

[SCB-652] Fix schema register logic

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/cache/VersionedCache.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/cache/TestVersionedCache.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/discovery/DiscoveryTree.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/discovery/DiscoveryTreeNode.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/discovery/TestDiscoveryTree.java

1.did not assign tmpRoot inside lock again
2.because of version overflow, root newer than input can not express by: tmpRoot.cacheVersion() > inputCache.cacheVersion()

[SCB-654] bug fix: DiscoveryTree concurrency problems

---

demo/demo-schema/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java

[SCB-662]Using cse/servicecomb duplicate key will get list of values

---

core/src/main/resources/META-INF/spring/cse.bean.xml
demo/demo-crossapp/crossapp-client/src/main/java/org/apache/servicecomb/demo/crossapp/CrossappClient.java
demo/demo-crossapp/crossapp-server/src/main/resources/microservice.yaml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestTransportConfig.java

---
See details in [SCB-679](https://issues.apache.org/jira/browse/SCB-679)

[SCB-679] Support Cross-Origin Resource Sharing (CORS)

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/AbstractParamProcessor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/CookieProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/FormProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/PathProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/QueryProcessorCreator.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestCookieProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestFormProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestHeaderProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestPathProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestQueryProcessor.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DefaultValues.java
samples/springmvc-sample/springmvc-consumer/src/main/java/org/apache/servicecomb/samples/springmvc/consumer/SpringmvcConsumerMain.java
samples/springmvc-sample/springmvc-provider/src/main/java/org/apache/servicecomb/samples/springmvc/provider/SpringmvcHelloImpl.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/parameter/AbstractParameterProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/CookieValueAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestHeaderAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestParamAnnotationProcessor.java

[SCB-685] Service comb chassis must support default values in query parameters

---

core/src/main/java/org/apache/servicecomb/core/provider/consumer/ConsumerProviderManager.java
core/src/test/java/org/apache/servicecomb/core/provider/consumer/TestConsumerProviderManager.java

So that consumer can re-query provider from the service-center. And when the provider is registered, the invocation can be executed successfully.
---
See details in [SCB-705](https://issues.apache.org/jira/browse/SCB-705)

[SCB-705] consumer don't cache ReferenceConfig of an unregistered provider

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapper.java
demo/demo-edge/authentication/src/main/java/org/apache/servicecomb/demo/edge/authentication/encrypt/EncryptImpl.java
demo/demo-edge/authentication/src/main/java/org/apache/servicecomb/demo/edge/authentication/encrypt/Hcr.java
demo/demo-edge/business-2.0.0/src/main/java/org/apache/servicecomb/demo/edge/business/Impl.java
demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/Consumer.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/authentication/encrypt/Hcr.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/EdgeConst.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/Encrypt.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/EncryptContext.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/EncryptEdgeDispatcher.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/EncryptEdgeInvocation.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/filter/DecodeBodyFilter.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/filter/EdgeSignatureRequestFilter.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/filter/EdgeSignatureResponseFilter.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/filter/UserIdFilter.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/handler/Auth.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/handler/AuthHandler.java
demo/demo-edge/edge-service/src/main/resources/META-INF/services/org.apache.servicecomb.common.rest.filter.HttpServerFilter
demo/demo-edge/edge-service/src/main/resources/microservice.yaml
demo/demo-edge/model/src/main/java/org/apache/servicecomb/demo/edge/model/User.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/HttpServletRequestEx.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/StandardHttpServletRequestEx.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestStandardHttpServletRequestEx.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerRequestToHttpServletRequest.java

1.add "decrypt“ logic, decrypt field named "body" in form,  generate new multiple fields to form by "body"
2.move "signature" to edge, and only signature for one operation
3.request with form-data or x-www-form-urlencoded, edge convert to json automatically
4.query userId by serviceToken, and put userId back to form
5.calc signature from response buffer,  and add "signature" field to response body, eg:
before: {"k":"v"}
after:    {"k":"v","signature":"xxxxx"}

[SCB-728] Decrypt/signature and adjust form in edge

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/CodeFirstRestTemplateJaxrs.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/JaxrsDemoHttpServerFilter.java
demo/demo-jaxrs/jaxrs-server/src/main/resources/META-INF/services/org.apache.servicecomb.common.rest.filter.HttpServerFilter

---
See details in [SCB-754](https://issues.apache.org/jira/browse/SCB-754)

[SCB-754] add null pointer check on AbstractRestInvocation.invocation

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapper.java
core/src/test/java/org/apache/servicecomb/core/TestExecutors.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/provider/AccessController.java
handlers/handler-publickey-auth/src/test/java/org/apache/servicecomb/authentication/TestAccessController.java
samples/trust-sample/store/src/main/resources/microservice.yaml

[SCB-788] public key black/white add feature: choose server by version

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestCodec.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestCodec.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/produce/TestProduceJsonProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/produce/TestProduceTextPlainProcessor.java

[SCB-828]In some tomcat implementation inputstream available is null

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/DefaultHttpClientMetrics.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/DefaultHttpServerMetrics.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/DefaultVertxMetrics.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/DefaultVertxMetricsFactory.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/MetricsOptionsEx.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultClientEndpointMetric.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultClientEndpointMetricManager.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultEndpointMetric.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/metrics/metric/DefaultHttpSocketMetric.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/metrics/TestDefaultHttpClientMetrics.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/metrics/TestDefaultHttpServerMetrics.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/metrics/TestDefaultVertxMetricsFactory.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/metrics/TestMetricsOptionsEx.java

- http server endpoint for each listen address
- summary of connect count
- summary of disconnect count
- current connection count: connect - disconnect
- summary of bytes read
- summary of bytes written
- http server socket
- connected flag
- connected nano time
- http client endpoint for each remote address
- same to http server endpoint
- expired check after connection pool closed
- http client socket
- same to http server socket
- nano time of got a connection from pool, by this we can know how long did it take to got a connection
- nano time of written request to netty queue
DefaultVertxMetricsFactory create DefaultVertxMetrics  
DefaultVertxMetrics create DefaultHttpClientMetrics 
DefaultVertxMetrics create DefaultHttpServerMetrics

[SCB-894] measure httpServer and httpClient

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDataTypePrimitive.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultValue.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypePojoSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeSpringmvcSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultValueJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultValueSpringmvcSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/TransportPojoSchema.java

[SCB-841] move string type test case from demo to integration-test

---

providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/schema/PojoProducers.java
providers/provider-rest-common/src/main/java/org/apache/servicecomb/provider/rest/common/RestProducers.java

[SCB-737]Avoid null point exception

---

common/common-rest/src/main/java/com/fasterxml/jackson/core/base/DoSFix.java
common/common-rest/src/main/java/com/fasterxml/jackson/core/base/DoSParserFixed.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/AbstractRestObjectMapper.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapper.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapperFactory.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessorManager.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/fix/TestDoSFix.java

after jackson fix the problem: https://github.com/FasterXML/jackson-databind/issues/2157
we need to remove these codes, but keep the test case.

[SCB-965] Fix jackson DoS problem

---

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java

[SCB-992] Synchronous open source code from Vert.x 3.5.3 version

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/CompositeSwaggerGeneratorContext.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/pojo/PojoSwaggerGeneratorContext.java

---
See details in [SCB-979](https://issues.apache.org/jira/browse/SCB-979)

[SCB-979] add reminder log on the selection of SwaggerGeneratorContext

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/DefaultRetryExtensionsFactory.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestDefaultRetryhandler.java

[SCB-1012] add NoRouteToHostException in retry's exception

---

core/src/main/java/org/apache/servicecomb/core/definition/schema/ConsumerSchemaFactory.java
core/src/test/java/org/apache/servicecomb/core/definition/TestMicroserviceVersionMeta.java
core/src/test/java/org/apache/servicecomb/core/definition/TestMicroserviceVersionMetaFactory.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/ServiceRegistry.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/cache/MicroserviceInstanceCache.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/ServiceRegistryClient.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/consumer/MicroserviceVersion.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/cache/TestMicroserviceInstanceCache.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/MicroserviceVersionTestUtils.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestDefaultMicroserviceVersionFactory.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceVersion.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceVersionRule.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceVersions.java

[SCB-1039]Add interface to compatible with ServiceCenter Aggregator

---

foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/ProtoMapper.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/ProtoConst.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/RootPropertyWrapDeserializer.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/bean/PropertyWrapper.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/PropertyWrapMessageAsFieldSchema.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/PropertyWrapMessageSchema.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/SchemaManager.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/DeserializerSchemaManager.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/SerializerSchemaManager.java
foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/internal/TestModelWrap.java
foundations/foundation-protobuf/src/test/resources/model.proto

protobuf idl can not describe List<List<X>>/List<Map<X, Y>>/Map<X, List<Y>>/Map<X, Map<Y, Z>>
wrap them to standard proto message when serialize
and unwrap when deserialize

[SCB-946] serialize/deseriaze List<List<X>>/List<Map<X, Y>>/Map<X, List<Y>>/Map<X, Map<Y, Z>>

---

integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/PreLoadBootListener.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestClientHttp.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java

[SCB-1079]allow consumer-id to be empty when query instance

---

metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/CpuMeter.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/cpu/AbstractCpuUsage.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/cpu/CpuUtils.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/cpu/OsCpuUsage.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/os/cpu/ProcessCpuUsage.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/DefaultLogPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestOsMeterInitializer.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/meter/os/TestCpuMeter.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/meter/os/TestOsMeter.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestDefaultLogPublisher.java

[SCB-1096]change the method calculate process cpu rate to same with top

---

tracing/README.md

In README, we should describe the steps of use in more detailed. I'd prefer to add "import package" message in README, because it may be helpful for new hand.

Add "import package" message in README.

---

core/src/test/resources/microservice.yaml
coverage-reports/pom.xml
demo/demo-edge/authentication/src/main/resources/microservice.yaml
demo/demo-edge/business-1-1-0/src/main/resources/microservice.yaml
demo/demo-edge/business-1.0.0/src/main/resources/microservice.yaml
demo/demo-edge/business-2.0.0/src/main/resources/microservice.yaml
demo/demo-edge/edge-service/src/main/resources/microservice.yaml
demo/perf/src/main/resources/microservice.yaml
foundations/foundation-test-scaffolding/src/main/java/org/apache/servicecomb/foundation/test/scaffolding/log/LogCollector.java
integration-tests/it-common/src/main/resources/microservice.yaml
java-chassis-dependencies/pom.xml
transports/transport-common/pom.xml
transports/transport-common/src/main/java/org/apache/servicecomb/transport/common/TransportConfigUtils.java
transports/transport-common/src/test/java/org/apache/servicecomb/transport/common/TestTransportConfigUtils.java
transports/transport-highway/pom.xml
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayConfig.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayConfig.java
transports/transport-rest/transport-rest-client/pom.xml
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestTransportClientConfig.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestTransportConfig.java

include:
- servicecomb.rest.server.thread-count
- servicecomb.rest.client.thread-count
- servicecomb.highway.server.thread-count
- servicecomb. highway.client.thread-count
change to:
- all thread-count change to verticle-count
- if use thread-count, print log to suggest to use new name
- if not present configuration, then will use default setting
- if cpu count less than 8, then verticle-count set to cpu count
- if cpu count equals or big than 8, then verticle-count set to 8

[SCB-1134] change default verticle instance count

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/ConfigObjectFactory.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/InjectProperties.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/InjectProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/PlaceholderResolver.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/PriorityProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/BooleanPriorityProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/DoublePriorityProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/FloatPriorityProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/IntPriorityProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/LongPriorityProperty.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/PropertyGetter.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/priority/impl/StringPriorityProperty.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/inject/TestConfigObjectFactory.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/inject/TestPlaceholderResolver.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/priority/TestPriorityProperty.java

support get config value by priority or inject priority value to model
```
@InjectProperties(prefix = "root")
public static class ConfigWithAnnotation {
@InjectProperty(prefix = "override", keys = {"high", "low"})
public String strValue;
@InjectProperty(keys = "${key}.value")
public int intValue;
@InjectProperty(keys = "${list-1}.a.${list-2}.b")
public long longValue;
@InjectProperty(keys = "${full-list}")
public float floatValue;
}
```

[SCB-638] Config model mechanism

---

core/src/main/java/org/apache/servicecomb/core/executor/GroupExecutor.java
core/src/test/java/org/apache/servicecomb/core/executor/TestGroupExecutor.java

expect to work like tomcat thread pool
but jdk standard thread pool's behavior is different:
```
JDK standard thread pool rules:
1.use core threads.
2.if all core threads are busy, then queue the request.
3.if queue is full, then create new thread util reach the limit of max threads.
4.if queue is full, and threads count is max, then reject the request.
```
to do what we want, need to lock the executor several times for one task, that's too bad
so only make compatible to old version temporary

[SCB-1232] make GroupExecutor configuration compatible to old version

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/deploy/Deploys.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/DefaultJsonValueResponse.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestAsyncInvoke.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeAsyncJaxrsSchema.java

---
- add IT
- limit memory consumption of IT

[SCB-1184] add IT for the case that provider's response type is CompletableFuture<ResponseEntity>

---

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
core/src/main/java/org/apache/servicecomb/core/tracing/ScbMarker.java
foundations/foundation-common/pom.xml
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/log/AbstractMarker.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/log/LogMarkerLeakFixUtils.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/log/NoCacheLog4j2Marker.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/log/NoCacheLog4jMarkerFactory.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/log/NoCacheMarker.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/ReflectUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/log/TestLogMarkerLeakFixUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/log/TestNoCacheLog4jMarkerFactory.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/utils/ClassUtils.java

ScbMarker.getName() is relate to traceId and invocationId, it's dynamic
log4j2 always convert slf4j marker to log4j marker type, and cache the instance by name, that will cause a memory leak problem.
log4j1 not support marker feature, no problem
logback use slf4j marker instance directly, no problem

[SCB-1266] Log4j2 marker leak

---

samples/bmi/pom.xml

The issue is caused by bmi example is base on the spring-boot parent pom. 
I just put the java-chassis BOM and spring-boot BOM together to address the validate API version issue.

SCB-1275 Fixed the starting error of bmi example

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/MockedFallbackExample.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/FallbackPolicy.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/FallbackPolicyManager.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/FromCacheFallbackPolicy.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/ReturnNullFallbackPolicy.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/ThrowExceptionFallbackPolicy.java
handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/TestBizkeeperHandler.java
handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/TestFallbackPolicyManager.java

[SCB-1304]FallbackPolicy#getFallbackResponse add Throwable

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/AbstractClientPool.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/HttpClientPool.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/WebsocketClientPool.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java

[SCB-1450] Microservice instance may get stuck when watch connection to sc is recovered and pulling instance action is executed in eventloop thread

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/DefaultModelResolveObjectMapperProvider.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ModelResolveObjectMapperProvider.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ModelResolverExt.java

- Add an extension interface `ModelResolveObjectMapperProvider` for customization
- Move current logic into `DefaultModelResolveObjectMapperProvider` as default logic

[SCB-1492] add ModelResolveObjectMapperProvider

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/ServiceRegistryClient.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java

[SCB-1610] add updateInstanceStatus to ServiceRegistryClient.java

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/MultiErrorCodeServiceClient.java
demo/demo-spring-boot-provider/pom.xml
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerProducerOperation.java

The demo module `demo-spring-boot-jaxrs-client` upgrade the SpringBoot modules to version 2.x, and the `io.micrometer:micrometer-core` introduced by `spring-boot-starter-actuator` registers HystrixPropertiesStrategy before the biz-keeper module of Java-Chassis, which causes NPE in demo test.

[SCB-1637] fix demo test NPE caused by HystrixPropertiesStrategy registration

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/concurrency/SuppressedRunnableWrapper.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/concurrency/RunnableWrapperTest.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java

https://issues.apache.org/jira/browse/SCB-1710
solution:
- add a wrapper class `SuppressedRunnableWrapper` to decorate the scheduled tasks, to ensure that no `Throwable` is thrown out of the tasks. This wrapper can be reused later.
- wrap the `org.apache.servicecomb.serviceregistry.consumer.AppManager#pullInstances` scheduled task by `SuppressedRunnableWrapper`

[SCB-1710] catch the throwable from the scheduled pulling task

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/LambdaMetafactoryUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/TestLambdaMetafactoryUtils.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/objectparams/FluentSetterBeanParamRequest.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/objectparams/FluentSetterFlattenObjectRequest.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/objectparams/FluentSetterFlattenObjectResponse.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/objectparams/ObjectParamTypeSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultJsonValueJaxrsSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestExceptionConvertEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestGenericEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodecEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestController.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestServerConfigEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestTraceEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestJAXRSObjectParamType.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestRPCObjectParamType.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestSpringMVCObjectParamType.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestSpringMVCObjectParamTypeRestOnly.java
integration-tests/it-edge/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/objectparams/JAXRSObjectParamTypeSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/objectparams/RPCObjectParamTypeSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/objectparams/SpringMVCObjectParamTypeSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/objectparams/SpringMVCObjectRestSchemaRestOnly.java

[SCB-1795] when use query object, sdk don't support fluent setter

---

demo/perf/src/main/resources/microservice.yaml
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/MetricsBootListener.java

some product only allow provide business endpoints.

[SCB-1990] allow disable metrics endpoints by configuration

---

demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/pom.xml
service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ServerUtil.java

[SCB-1995]Fix incorrect message issue identifed through testing

---

service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/server/ServerUtil.java

[SCB-1997] Small improvement when Muticastscoket receive data

---

demo/demo-edge/edge-service/src/main/resources/microservice.yaml
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeAddHeaderClientFilter.java

[SCB-1832] Edge will lose public request headers:old request maybe null

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestUpload.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/UploadJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/UploadSpringmvcSchema.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestPartAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/property/creator/MultipartFilePropertyCreator.java
swagger/swagger-generator/generator-springmvc/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.extend.property.creator.PropertyCreator
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestPartAnnotationProcessorTest.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/property/creator/MultipartFilePropertyCreatorTest.java

- add MultipartFilePropertyCreator to enable ModelConverters resolving MultipartFile param
- make RequestPartAnnotationProcessor recognize non-file-type RequestPart param
See details in https://github.com/apache/servicecomb-java-chassis/issues/1902

[SCB-2058] fix SpringMVC provider not support non-file-type RequestPart problem

---

metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/HealthBootListener.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/MetricsBootListener.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestHealthBootListener.java

- add config item `servicecomb.health.endpoint.enabled` as the switch of healthEndpoint
- add config item `servicecomb.metrics.endpoint.enabled` as the switch of metricsEndpoint
- the default value of these two item is `true`

[SCB-2082] add separated switches for metricsEndpoint and healthEndpoint

---

dependencies/bom/pom.xml
distribution/pom.xml
huawei-cloud/dtm/pom.xml
huawei-cloud/dtm/src/main/java/org/apache/servicecomb/huaweicloud/dtm/DtmConfig.java
huawei-cloud/dtm/src/main/java/org/apache/servicecomb/huaweicloud/dtm/DtmConsumerHandler.java
huawei-cloud/dtm/src/main/java/org/apache/servicecomb/huaweicloud/dtm/DtmProviderHandler.java
huawei-cloud/dtm/src/main/resources/config/cse.handler.xml
huawei-cloud/dtm/src/test/java/com/huawei/middleware/dtm/client/context/DTMContext.java
huawei-cloud/dtm/src/test/java/org/apache/servicecomb/huaweicloud/dtm/TestConsumerHandler.java
huawei-cloud/dtm/src/test/java/org/apache/servicecomb/huaweicloud/dtm/TestDtmProviderHandler.java
huawei-cloud/dtm/src/test/resources/log4j.properties

[SCB-2084] ServiceComb support dtm

---

integration-tests/it-common/src/main/resources/microservice.yaml
integration-tests/it-producer-deploy-springboot2-servlet/pom.xml
integration-tests/it-producer-deploy-springboot2-standalone/pom.xml
integration-tests/it-producer-deploy-springboot2-standalone/src/main/java/org/apache/servicecomb/it/SpringBoot2StandaloneApplication.java
integration-tests/it-producer/src/main/resources/microservice.yaml
pom.xml
scripts/build.sh

release 1.3.1

---

core/src/main/java/org/apache/servicecomb/core/definition/MicroserviceConfig.java
core/src/main/java/org/apache/servicecomb/core/registry/discovery/OperationInstancesDiscoveryFilter.java
demo/demo-edge/business-1-1-0/src/main/java/org/apache/servicecomb/demo/edge/business/Impl.java
demo/demo-edge/business-1.0.0/src/main/java/org/apache/servicecomb/demo/edge/business/Impl.java
demo/demo-edge/business-2.0.0/src/main/java/org/apache/servicecomb/demo/edge/business/Impl.java
demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/Consumer.java
demo/demo-edge/consumer/src/main/resources/microservice.yaml

[SCB-2118]servicecomb.references.version-rule not work

---

foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLManager.java
foundations/foundation-ssl/src/test/java/org/apache/servicecomb/foundation/ssl/SSLManagerTest.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java

fix typo and test case assert not correct in higher version of JDK

---

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestSameService.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/same/pk1/SameInterface.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/same/pk1/SameInterfaceImpl.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/same/pk1/SameService.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/same/pk2/SameInterface.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/same/pk2/SameInterfaceImpl.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/same/pk2/SameService.java

add an example and test case for same class/interface name

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/BeanUtils.java
foundations/foundation-common/src/test/java/TestNoPackageMain.java

[SCB-2070]when main is default package(empty), start up will fail

---

core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
core/src/test/java/org/apache/servicecomb/core/TestConfig.java
handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/TestBizkeeperHandler.java
providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequest.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/Response.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/core/TestResponse.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientDecoder.java

[SCB-2154] fix Response.isSuccessed typo

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/SwaggerDefinitionProcessor.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/SwaggerDefinitionProcessorTest.java
swagger/swagger-generator/generator-core/src/test/resources/schemas/security-apikey.yaml
swagger/swagger-generator/generator-core/src/test/resources/schemas/security-basic.yaml
swagger/swagger-generator/generator-core/src/test/resources/schemas/security-oauth2.yaml

[SCB-2166] swagger generator support securityDefinition

---

core/src/main/java/org/apache/servicecomb/core/exception/converter/TimeoutExceptionConverter.java
core/src/test/java/org/apache/servicecomb/core/exception/converter/TimeoutExceptionConverterTest.java

[SCB-2171] avoid leak server ip when process TimeoutException

---

dependencies/default/pom.xml

SCB-2182 upgrade jackson from 2.12.0 to 2.12.1

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestProducerInvocationCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestVertxProducerInvocationCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/RestProducerInvocationCreatorTest.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilterTest.java
core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/main/java/org/apache/servicecomb/core/invocation/InvocationCreator.java
core/src/main/java/org/apache/servicecomb/core/invocation/ProducerInvocationFlow.java
core/src/test/java/org/apache/servicecomb/core/invocation/ProducerInvocationFlowTest.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/CompatiblePathVersionMapper.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/DefaultEdgeDispatcher.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeAddHeaderClientFilter.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeAddHeaderFilter.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocationCreator.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeRestTransportClient.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeServerCodecFilter.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestDefaultEdgeDispatcher.java
integration-tests/it-edge/src/main/resources/microservice.yaml
service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/Self.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerConnection.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxHttpDispatcher.java

[SCB-2218] allow edge invocation process by filter

---

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/BootStrapProperties.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/BootStrapPropertiesTest.java
foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/RegistrationManager.java
foundations/foundation-test-scaffolding/pom.xml
foundations/foundation-test-scaffolding/src/main/java/org/apache/servicecomb/foundation/test/scaffolding/AssertUtils.java
service-registry/registry-zero-config/src/main/java/org/apache/servicecomb/zeroconfig/Config.java

[SCB-2234] configuration for instance properties should support placeholder

---

core/src/main/java/org/apache/servicecomb/core/definition/OperationConfig.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/GovernanceEndpoint.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/resources/application.yml
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-server/src/main/java/org/apache/servicecomb/demo/zeroconfig/server/GovernanceEndpoint.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/GovernanceTest.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/resources/application.yml
handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ConsumerGovernanceHandler.java
handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/MatchType.java
handlers/handler-governance/src/main/java/org/apache/servicecomb/handler/governance/ProviderGovernanceHandler.java

[SCB-2257][SCB-2258]governance support http based match

---

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/AddressManager.java
clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java
clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java
clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/model/KieAddressManager.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/AddressManager.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRawClient.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterWatch.java
demo/demo-cse-v1/pom.xml
huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/AddressManager.java
huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/DefaultMonitorDataPublisher.java

[SCB-2274]change connecting config/dashboard services rule to round robbin

---

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestNotRecommendedService.java
demo/demo-pojo/pojo-client/src/main/resources/microservice.yaml
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/NotRecommendedService.java
demo/demo-pojo/pojo-server/src/main/resources/microservice.yaml
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/AbstractModel.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/DefaultAbstractModel.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/NotRecommendedServiceInf.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/SecondAbstractModel.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/WrappedAbstractModel.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ModelResolverExt.java

[SCB-2289]support disable swagger data type check and use generics

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/TransportUtils.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/TransportUtils.java
foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/ClientAuth.java
foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLManager.java
foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLOption.java
foundations/foundation-ssl/src/test/java/org/apache/servicecomb/foundation/ssl/SSLManagerTest.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/auth/RBACBootStrapService.java

[SCB-2288]add a configuration for ssl client auth type

---

clients/service-center-client/README.md

# SCB-2322 remove service center client wrong readme

---

providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseHttpMessageConverter.java

Current Java-chassis version consumer sends a request to provider without any Accept header field, Accept header of provider receiving is empty string.

[SCB-2329] when consumer sends a request without setting any Accept header, default set Accept header */*

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/validation/ValidationServiceClient.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/ApiOperationProcessorTest.java

Current swagger version is 1.6.2, this version do not recognize  NotBlank and NotEmpty annotations. In some cases, it is misunderstand that some fields Using  NotBlank and NotEmpty annotations are not equired.

[SCB-2331] swagger generator support NotBlank and NotEmpty annotations

---

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RegistryWatchHttpClientOptionsSPI.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfigBuilder.java
service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java
service-registry/registry-service-center/src/test/resources/microservice.yaml

2.x delete watch idle timeout accidentally, re-add it. 
More info about see issue https://github.com/apache/servicecomb-java-chassis/issues/2571

[SCB-2336] re-add watch idle timeout configuration

---

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/CodeFirstPojoClient.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClient.java
demo/demo-pojo/pojo-client/src/main/resources/META-INF/spring/pojo.client.bean.xml
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/CodeFirstPojo.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CodeFirstPojoIntf.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/AuthHandlerBoot.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/RSAAuthenticationToken.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/provider/RSAProviderTokenManager.java
handlers/handler-publickey-auth/src/test/java/org/apache/servicecomb/authentication/TestAuthHandlerBoot.java
handlers/handler-publickey-auth/src/test/java/org/apache/servicecomb/authentication/provider/TestRSAProviderTokenManager.java
integration-tests/pojo-test/src/test/java/org/apache/servicecomb/demo/pojo/test/endpoints/CodeFirstPojo.java

[SCB-2318]revert PR[#2350] and add test case for map null value

---

huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/AddressManager.java

[SCB-2335]data monitor throw IndexOutOfBoundsException if no address configured

---

demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/CodeFirstPojoClient.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClient.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/CodeFirstPojo.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CodeFirstPojoIntf.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/mapnull/ParseRequest.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/mapnull/ParseResponse.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
foundations/foundation-protobuf/src/main/java/io/protostuff/ProtobufOutputEx.java
integration-tests/pojo-test/src/test/java/org/apache/servicecomb/demo/pojo/test/endpoints/CodeFirstPojo.java

[SCB-2343]fix highway empty string serialization problem

---

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/SimpleMicroserviceInstancePing.java
service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestSimpleMicroserviceInstancePing.java

When there are multiple endpoints, ping only the first one may cause the available services to be defined as unavailable
#2624

[SCB-2351] Optimize the ping method

---

demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/SpringmvcServer.java
demo/demo-springmvc/springmvc-client/pom.xml
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcClient.java
demo/demo-springmvc/springmvc-client/src/test/java/org/apache/servicecomb/demo/springmvc/SpringMvcIT.java
demo/demo-springmvc/springmvc-server/pom.xml
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/SpringmvcServer.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/third/EarlyConsumer.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/third/HealthSchema.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/third/HeartBeatService.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/third/NormalConsumer.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/third/Register.java

[#2534]test case for 3rd registry invoke issue

---

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java
core/src/main/java/org/apache/servicecomb/core/Const.java
core/src/main/java/org/apache/servicecomb/core/handler/impl/ProducerOperationHandler.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/BizkeeperCommand.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/provider/AccessController.java

SCB-2360 Provides a unified switch to control exception stack printing

---

dependencies/default/pom.xml

[SCB-2346]upgrate netty version

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/UploadConfig.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestUploadConfig.java
transports/transport-rest/transport-rest-servlet/src/main/java/org/apache/servicecomb/transport/rest/servlet/ServletUtils.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestAbstractVertxHttpDispatcher.java

[SCB-2381] support upload to default directory

---

clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/AbstractAddressManager.java
clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/URLEndPoint.java
clients/http-client-common/src/test/java/org/apache/servicecomb/http/client/common/AbstractAddressManagerTest.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/refresh/ClassificationAddress.java

[SCB-2361] Solve URL conversion problem

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
java-chassis-dependencies/default/pom.xml

[SCB-2385]fix IsolationDiscoveryFilter create many temporary objects

---

foundations/foundation-config/pom.xml

java later version has removed `javax.annotation` dependency. If we need to support multi java versions, we need to add `jakarta` dependecy

[SCB-2428] add jakarta dependency in foundation-config

---

clients/config-common/src/main/java/org/apache/servicecomb/config/common/ConfigConverter.java
common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/internal/converter/TestSwaggerToProtoGenerator.java
foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLOption.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpParser.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/stream/TestBufferInputStream.java
huawei-cloud/darklaunch/src/main/java/org/apache/servicecomb/darklaunch/DarklaunchRule.java

Since we support java version is java1.8+, we can use StandardCharsets insteadof `Charset.Forname`

[SCB-2431] use StandardCharsets instead of Charset Forname

---

README.md
README_ZH.md

[SCB-2366] fix link error in READ_CN.md

---

dependencies/default/pom.xml

upgrade springboot version to 2.6.2
springboot version 2.6.2 depends on spring version 5.3.14, also updates

[SCB-2426] upgrade springboot version to 2.6.6

---

core/pom.xml

we don't need to mark junit to scope `provide`,  we only need to mark junit to scope `test`. Sine it's already done on parent pom, we just need to delete the `provider` dep.

[SCB-2445] make junit only test dependency

---

governance/src/main/java/org/apache/servicecomb/router/cache/RouterRuleCache.java

The new constructor makes the original constructor invalid.Combine the two constructors so that the class is loaded correctly.

[#2795]Fixed the issue that the dynamic modification configuration of gray release is invalid. 

---

demo/demo-schema/pom.xml
dependencies/default/pom.xml
integration-tests/it-consumer/pom.xml

- add jaxb-api dependency allow demo run on jdk17
- extract `maven-demo` dependency on parent pom
- fix some sort dependency version order(by alpha beta)

[SCB-2473] Add jaxb-api dependency allow demo run on jdk17

---

.github/workflows/unit-test-jdk11.yml
foundations/foundation-spi/src/test/java/org/apache/servicecomb/foundation/common/utils/TestSPIServiceUtils.java
pom.xml
swagger/swagger-generator/generator-jaxrs/pom.xml
swagger/swagger-generator/generator-springmvc/pom.xml

- make test paas on jdk11
- add jdk11 check
I think now we don't need run integrates-tests on all java version, it costs time and little effect

[SCB-2481] Make test paas on jdk11

---

.github/dependabot.yml

many frameworks still use jersey 2.x and okhttp 3.x, we should not update so quick to avoid conflict
- add jersey-common 3.x ignore
- add okhttp 4.x ignore

[SCB-2489] Add dependeny bot ignore list

---

.github/dependabot.yml
dependencies/default/pom.xml

many frameworks still use jakarta.activation 2.x, we should not update so quick to avoid conflict
- add jakarta.activation 2.x ignore
- bump  jakarta.activation to 1.2.2

[SCB-2489] Add dependeny bot ignore jakarta.activation

---

.github/dependabot.yml

swagger2markup new version needs java11 now

[SCB-2489] Add dependeny bot ignore swagger2markup

---

.github/dependabot.yml

many frameworks still use jakarta.ws.rs-api 2.x, we should not update so quick to avoid conflict
- add jakarta.ws.rs-api 3.x ignore

[SCB-2489] Add dependeny bot ignore rs-api

---

.github/dependabot.yml
dependencies/default/pom.xml

many frameworks still use jakarta.servlet-api 4.x, we should not update so quick to avoid conflict
- add jakarta.activation 5.x ignore
- bump  jakarta.activation to 4.0.4

[SCB-2489] Add dependeny bot ignore jakarta.servlet-api

---

.github/dependabot.yml
dependencies/default/pom.xml

- Since https://github.com/dependabot/dependabot-core/issues/222 is merged, we don't need to specify all the version location in the project
- `mockito-all` is on longer release since mockito 2.x, now we are using mockit 3.x

[SCB-2489] optimize dependabot config

---

dependencies/default/pom.xml
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestDefaultRegistryInitializer.java

By the servo v0.13.2, the default way of  monitor registry return a abstract class, and its size is 0. 
By the servo v0.12.25,the default way of  monitor registry return a class, and its size is 1. old version's test is suitable for new version.

[SCB-2531] Bump servo version from 0.12.25 to 0.13.2

---

.github/dependabot.yml
dependencies/default/pom.xml

Sine okhttp3 3.x is not maintained, update to 4.x

[SCB-2538] Bump okhttp version from 3.14.2 to 4.9.3

---

dependencies/default/pom.xml

bump guice version from 4.2.0 to 5.1.0
1. `io.protostuff-parser` [2.2.27](https://mvnrepository.com/artifact/io.protostuff/protostuff-parser/2.2.27) is not compatible with `guice 5.1.0` because of depending on an older version of `guice-multibindings` and `guice-assistedinject`.
2. It's was decided to upgrade `guice-multibindings` and `guice-assistedinject` instead of directly upgrading `io.protostuff-parser` since newer version of  `io.protostuff-parser` requires java 11.
4. `guice-multibindings` is excluded explicitly because it was removed(and not needed) since [guice 4.2](https://github.com/google/guice/wiki/Multibindings).
5. manually set `guice-assistedinject` version in order to make it consistent with guice(5.1.0)

[SCB-2542]bump guice version from 4.2.0 to 5.1.0

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/JsonUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/JsonUtilsTest.java
java-chassis-dependencies/default/pom.xml
transports/transport-rest/transport-rest-client/pom.xml
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java

fix issus #3008
add writeUnicodeValueAsString to JsonUtils to support unicode encoding
encode invocation context before add to http header

[SCB-2533] [1.3.x] encode invocation context before add to http header

---

pom.xml

the variable `${maven-jxr-plugin.version}` is not defined, no need to delete

[SCB-2557] Remove unused plugin maven-jxr-plugin

---

dependencies/default/pom.xml

It's already defined in netty-bom, and should be keep consistent with netty.

[SCB-2566] Remove unused tcnative dependency version define

---

integration-tests/test-common/src/test/java/org/apache/servicecomb/tests/tracing/TracingTestBase.java

[SCB-2589] fix spans is null sometimes

---

clients/http-client-common/src/test/java/org/apache/servicecomb/http/client/common/AbstractAddressManagerTest.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/VertxRestInvocationTest.java
dynamic-config/config-apollo/src/test/java/org/apache/servicecomb/config/client/ApolloClientTest.java
dynamic-config/config-nacos/src/test/java/org/apache/servicecomb/config/nacos/client/NacosClientTest.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocation.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/client/tcp/TestTcpClientConnection.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/SessionStickinessRule.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestSessionSticknessRule.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilterTest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestUrlWithProviderPrefixClientHttpRequestFactory.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestUrlWithServiceNameClientHttpRequestFactory.java
service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayClient.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java

We are doing a job that's upgrade jmockit to newest version, and this's method in jmockit `mockit.Deencapsulation#invoke` has bean Deprecated. So replace it to invoke directly

[SCB-2611]Replace jmokit Deencapsulation.invoke to invoke directly

---

clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/model/KieConfiguration.java
governance/src/main/java/org/apache/servicecomb/governance/GovernanceConfiguration.java
governance/src/main/java/org/apache/servicecomb/governance/handler/LoadBalanceHandler.java
governance/src/main/java/org/apache/servicecomb/governance/policy/LoadBalancerPolicy.java
governance/src/main/java/org/apache/servicecomb/governance/properties/LoadBalanceProperties.java
governance/src/main/java/org/apache/servicecomb/loadbanlance/LoadBalance.java
governance/src/main/java/org/apache/servicecomb/loadbanlance/LoadBalanceImpl.java
governance/src/test/java/org/apache/servicecomb/governance/GovernancePropertiesTest.java
governance/src/test/java/org/apache/servicecomb/governance/LoadBalancerTest.java
governance/src/test/resources/application.yaml

[SCB-2665]Add the load balance governance 

---

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterOperation.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRegistration.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/UpdatePropertiesRequest.java
clients/service-center-client/src/test/java/org/apache/servicecomb/service/center/client/ServiceCenterClientTest.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
service-registry/registry-service-center/src/test/java/org/apache/servicecomb/serviceregistry/task/TestMicroserviceRegisterTask.java

[SCB-2663]Support to update microservice properties to the registration center.

---

demo/demo-cse-v2/README.md
demo/demo-cse-v2/gateway/src/main/resources/application.yml
demo/demo-cse-v2/test-client/src/main/resources/application.yml
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java

[SCB-2689] fix rate limiting configuration changed cause NPE problem

---

handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ConsumerQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/FixedWindowStrategy.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/strategy/LeakyBucketStrategy.java

[SCB-2689]fix rate limiting configuration changed cause NPE problem

---

foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestAbstractHttpServletRequest.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestStandardHttpServletRequestEx.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerRequestToHttpServletRequest.java

The order in which the values are returned from `request.getAttributeNames()` and `requestEx.getParameterNames()` is non deterministic because of the use of HashMap(which doesn't guarantee the order of the elements). To make sure the assert handles these cases as well, I have used `containsInAnyOrder` instead of `contains` to make sure the tests are not flaky
Bug - https://issues.apache.org/jira/projects/SCB/issues/SCB-2692?filter=allopenissues
---

[SCB-2692] fixing flaky tests in foundations

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java
core/src/main/java/org/apache/servicecomb/core/governance/MatchType.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/java/org/apache/servicecomb/demo/zeroconfig/client/GovernanceEndpoint.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-client/src/main/resources/application.yml
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-server/src/main/java/org/apache/servicecomb/demo/zeroconfig/server/GovernanceNoPrefixEndpoint.java
demo/demo-zeroconfig-schemadiscovery-registry/demo-zeroconfig-schemadiscovery-registry-tests/src/main/java/org/apache/servicecomb/demo/zeroconfig/tests/GovernanceTest.java

[SCB-2710]servicecomb.governance apiPath match problem

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/TestOperationGenerator.java

- This PR fixes the flaky test `org.apache.servicecomb.swagger.generator.core.TestOperationGenerator.apiOperationThenResponse`
- The mentioned test may fail or pass without changes made to the source code when it is run in different JVMs due to the non-deterministic order of the returned array from `getDeclaredAnnotations`. Because there is no assumption on the order of the returned array from this method in [Java documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AccessibleObject.html#getDeclaredAnnotations--).
- When processing the annotations of a method in `AbstractOperationGenerator#scanMethodAnnotations()`, the result of `method.getAnnotations()` is used which uses `AccessibleObject.getDeclaredAnnotations()` which does not guarantee a deterministic result …

[SCB-2718]  Fix flaky test failure in TestOperationGenerator#apiOperationThenResponse

---

clients/service-center-client/src/test/java/org/apache/servicecomb/service/center/client/ServiceCenterClientTest.java

The function `writeValueAsString` returns the order of elements in no fix order and can hamper the functionality of `mock` function. 
For the test `#TestSendHeartBeats` , these are 2 values I received from the function `writeValueAsString`
We are only changing the code to take any string value for the 3rd parameter and the first 2 parameter will be checked.
Similar code is present in other test functions - `TestGetServiceInstanceMessage`, `TestDeleteServiceInstance` , where all the parameters are mocked for any value.
---

[SCB-2739] fix flaky tests in clients

---

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/RestProducerInvocationCreatorTest.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestRestClientRequestImpl.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/inner/RestServerCodecFilterTest.java
core/src/test/java/org/apache/servicecomb/core/TestInvocation.java

1. `TestInvocation#traceIdGeneratorInit`
- Using `containsInAnyOrder` so that the junit test passing every order of the values 
<hr />
2. `TestRestClientRequestImpl#testForm`
-  Checking all possible values so that the test does not fail
<hr />
3. `TestRestClientRequestImpl#testCookie`
- Mocking for both cases `"region=china-north; sessionid=abcdefghijklmnopqrstuvwxyz; "` and `"sessionid=abcdefghijklmnopqrstuvwxyz; region=china-north; "`, So that the mock function works for both the cases
<hr />
4. `RestServerCodecFilterTest#should_convert_exception_to_response_when_decode_request_failed`
- `Json.encode` can return the json string in different order. We need to check for all the possible values so that the test does not fail for some cases.
<hr />
5. …

[SCB-2731] fix flaky junit tests in common and core

---

core/src/main/java/org/apache/servicecomb/core/ConfigurationSpringInitializer.java

[SCB-2752] Filter out configurations with empty values

---

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/consumer/MicroserviceVersions.java

[SCB-2771]fix MicroserviceVersions concurrent access problem

---

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java
foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/Discovery.java
foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/api/registry/MicroserviceInstances.java
service-registry/registry-lightweight/src/main/java/org/apache/servicecomb/registry/lightweight/AbstractLightweightDiscovery.java
service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalDiscovery.java
service-registry/registry-local/src/main/java/org/apache/servicecomb/localregistry/LocalRegistryStore.java
service-registry/registry-schema-discovery/src/main/java/org/apache/servicecomb/schemadiscovery/SchemaDiscovery.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/ServiceCenterDiscovery.java

[SCB-2773]Change mutil dicovery registry instance merge policy (#3650)

---

pom.xml

Since we will only support jdk17 in master branch, it's time to delete the stable profile.
There are still some compile warning to be fixed. Let's fix it in other PR.

Remove unused stale profile

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDownloadSchema.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/DownloadUtils.java

[#3850] Fix the problem when setting content-type by ResponseEntity.header() does not take effect

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDownloadSchema.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/DownloadUtils.java

(cherry picked from commit c57f5cf4e19fb1b6573feed48e78da80b8165799)
---

[Backport 2.8.x][#3850] Fix the problem when setting content-type by ResponseEntity.header() does not take effect

---

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceInstanceRegisterTask.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestDefaultHttpClientFilter.java

[#3893]fix client decode error message

---

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientCodecFilter.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientSender.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java

[#3727]Fix metrics not correct when timeout/connection timeout

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestRestClientRequestImpl.java
demo/demo-spring-boot-transport/demo-spring-boot-springmvc-client/src/main/java/org/apache/servicecomb/springboot/springmvc/client/UploadDownloadSchemaTest.java
demo/demo-spring-boot-transport/demo-spring-boot-springmvc-server/src/main/java/org/apache/servicecomb/springboot/springmvc/server/UploadDownloadSchema.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestClientRequestParametersImpl.java

[#2523]fix problem when client api do not provide file parameter

---

metrics/metrics-core/pom.xml
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestInvocationMetersInitializer.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestOsMeterInitializer.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/meter/os/TestNetMeter.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/meter/os/TestSystemMeter.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestInvocationPublishModelFactory.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestPublishUtils.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestSlowInvocationLogger.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestThreadPoolPublishModelFactory.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/model/invocation/TestOperationPerf.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/model/invocation/TestOperationPerfGroup.java

TestDefaultLogPublisher and TestThreadPoolMetersInitializer need further analysis.

Migrate parts of metrics module to junit5

---

dependencies/default/pom.xml
governance/src/test/java/org/apache/servicecomb/governance/InstanceIsolationTest.java
governance/src/test/java/org/apache/servicecomb/governance/MockConfiguration.java

Bump io.micrometer:micrometer-bom from 1.12.4 to 1.13.1

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodec.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecCsv.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecMulti.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecPipes.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecSimple.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecSsv.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecWithDelimiter.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/header/HeaderCodecsUtils.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java
demo/demo-nacos/README.md
demo/demo-nacos/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerHeaderParamWithListSchema.java
demo/demo-nacos/pom.xml
demo/demo-nacos/provider/src/main/java/org/apache/servicecomb/samples/HeaderParamWithListSchema.java
demo/demo-nacos/test-client/src/main/java/org/apache/servicecomb/samples/HeaderParamWithListSchemaIT.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/api/IHeaderParamWithListSchema.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/api/IHeaderParamWithListSchemaSpringMvc.java
demo/demo-zookeeper/README.md
demo/demo-zookeeper/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerHeaderParamWithListSchema.java
demo/demo-zookeeper/pom.xml
demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/HeaderParamWithListSchema.java
demo/demo-zookeeper/test-client/src/main/java/org/apache/servicecomb/samples/HeaderParamWithListSchemaIT.java

[#4405]header parameter support array type

---

core/pom.xml
core/src/main/java/org/apache/servicecomb/core/CoreConst.java
core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/main/java/org/apache/servicecomb/core/annotation/Transport.java
core/src/main/java/org/apache/servicecomb/core/filter/impl/ProviderOperationFilter.java
core/src/main/java/org/apache/servicecomb/core/transport/TransportClassAnnotationProcessor.java
core/src/main/java/org/apache/servicecomb/core/transport/TransportMethodAnnotationProcessor.java
core/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.generator.ClassAnnotationProcessor
core/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.generator.MethodAnnotationProcessor
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDateTimeSchema.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestMaxHttpUrlLength.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestTransportSchema.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestWeakSpringmvc.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/TransportSchema.java
demo/demo-zookeeper/consumer/src/main/java/org/apache/servicecomb/samples/ConsumerReactiveStreamController.java
demo/demo-zookeeper/consumer/src/main/resources/application.yml
demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/ReactiveStreamController.java
demo/demo-zookeeper/provider/src/main/resources/application.yml
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceFilter2.java

[SCB-2888]support configuring operation transport

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filterext/ZoneAwareDiscoveryFilter.java

[#4427]able to disable both consumer and provider zone-aware

---

core/src/test/java/org/apache/servicecomb/core/transport/TestAbstractTransport.java
dependencies/default/pom.xml
foundations/foundation-test-scaffolding/src/main/java/io/vertx/core/impl/SyncContext.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpServer.java
foundations/foundation-vertx/src/test/java/io/vertx/ext/web/impl/TestHttpServerRequestUtils.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/stream/TestPumpFromPart.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java

Bump netty from 4.1.110.Final to 4.1.112.Final vertx from 4.4.9 4.5.9

---

service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosDiscovery.java
service-registry/registry-nacos/src/main/java/org/apache/servicecomb/registry/nacos/NacosRegistration.java

[ISSUE #4470] Shutdown nacos client properly.

fix: shutdown nacos client when discovery destroy

---

dependencies/default/pom.xml

The 0.5.1 version is unintentionally released to the Maven repository version. The corresponding tag cannot be found in the community.
For [issue4479](https://github.com/apache/servicecomb-java-chassis/issues/4479)
---

[#4479]Bump io.reactivex.rxnetty from 0.5.1 to 0.4.20

---

common/common-access-log/src/main/java/org/apache/servicecomb/common/accessLog/core/element/impl/HttpStatusAccessItem.java
core/src/main/java/org/apache/servicecomb/core/invocation/ProducerInvocationFlow.java
demo/demo-zookeeper/provider/src/main/java/org/apache/servicecomb/samples/WebsocketController.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java

[#4477]Fix GoAway issue in Http2 after many requests timeout

---

clients/config-center-client/src/main/java/org/apache/servicecomb/config/center/client/ConfigCenterClient.java
clients/config-kie-client/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java
clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/AbstractAddressManager.java
clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/event/EngineConnectChangedEvent.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java
huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/RBACBootStrapService.java
huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/TokenCacheManager.java

[#4517] fixed for cross engine authentication failed at dual-az servicecomb engine

---

pom.xml

[#4449] Bump org.apache:apache from 31 to 33 
fix https://github.com/apache/servicecomb-java-chassis/pull/4449

chore(deps): Bump org.apache:apache from 31 to 33 

---

foundations/foundation-registry/src/main/java/org/apache/servicecomb/registry/DiscoveryManager.java

[#4593]Fix when API change edge service not load latest schema problem

---

.typos.toml
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/cc/TransportUtils.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/TransportUtils.java
foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLOption.java
foundations/foundation-ssl/src/test/java/org/apache/servicecomb/foundation/ssl/SSLOptionTest.java
foundations/foundation-ssl/src/test/resources/client.ssl.properties
foundations/foundation-ssl/src/test/resources/microservice.yaml
foundations/foundation-ssl/src/test/resources/server.ssl.properties
foundations/foundation-ssl/src/test/resources/server.ssl.resource.properties
handlers/handler-fault-injection/src/main/java/org/apache/servicecomb/faultinjection/FaultInjectionUtil.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalanceConfiguration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/RuleNameExtensionsFactory.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestExtensionsManager.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceFilter.java
huawei-cloud/dashboard/src/main/java/org/apache/servicecomb/huaweicloud/dashboard/monitor/TransportUtils.java
huawei-cloud/servicestage/src/main/java/org/apache/servicecomb/huaweicloud/servicestage/RBACBootStrapService.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/AbstractArgumentsMapperCreator.java

refactor(loadbalance): Modify load balancing configuration and naming
- Fix typos in Configuration file
-Rename RuleNameExtentionsFactory to RuleNameExtensionsFactory
- Update references in relevant test files
- Added Verticle as an allowed word in .typos.toml
- Fixed typo in AbstractArgumentsMapperCreator file
- Fixed typo in FaultInjectionUtil file

update spell's error

---

.typos.toml
clients/http-client-common/src/main/java/org/apache/servicecomb/http/client/common/URLEndPoint.java
common/common-access-log/src/main/java/org/apache/servicecomb/common/accessLog/core/element/impl/ConfigurableDatetimeAccessItem.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/RequestRootSerializer.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/ResponseRootSerializer.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/fix/TestDoSFix.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/URIEndpointObject.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/net/TestURIEndpointObject.java
swagger/swagger-generator/generator-jaxrs/src/test/java/org/apache/servicecomb/swagger/generator/jaxrs/Echo.java
swagger/swagger-generator/generator-jaxrs/src/test/resources/schemas/echo.yaml
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/TestSpringmvc.java

- 修正 .typos.toml 中的拼写错误
- 修改 ConfigurableDatetimeAccessItem 中的 setConfigruations 方法
- 更新 Echo 类中的 queryComplex 方法参数名
- 调整 echo.yaml 中的参数定义- 修正 RequestRootSerializer 和 ResponseRootSerializer 中的 isWrapp 字段
- 更新 RestConst 中的常量名
- 修改 TestDoSFix 中的断言信息- 更新 TestRestObjectMapper 中的测试方法名
- 修正 TestSpringmvc 中的测试方法名- 更新 URIEndpointObject 和 URLEndPoint 中的 queries 相关代码

refactor: 修正拼写错误并优化代码

---

core/src/test/java/org/apache/servicecomb/core/exception/ExceptionsTest.java

Hello, I apologize for not creating and linking a JIRA issue for this PR yet, though I did request for a JIRA account on the self-serve page if needed. This PR is fairly trivial though and does not change much code. 
This PR fixes the flaky tests:
* [`org.apache.servicecomb.core.exception.ExceptionsTest.should_convert_unknown_client_exception_to_invocation_exception`](https://github.com/apache/servicecomb-java-chassis/blob/fc7c01668fbb992e015458a86bc4366a00dc5878/core/src/test/java/org/apache/servicecomb/core/exception/ExceptionsTest.java#L46)
* [`org.apache.servicecomb.core.exception.ExceptionsTest.should_convert_unknown_server_exception_to_invocation_exception`](https://github.com/apache/servicecomb-java-chassis/blob/fc7c01668fbb992e015458a86bc4366a00dc5878/core/src/test/java/org/apache/ …

Fixed flaky tests in ExceptionsTest.java with ObjectMapper

---

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/schema/SchemaToProtoGenerator.java
common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/schema/TestSchemaToProtoGenerator.java

This PR fixes the flaky tests:
`org.apache.servicecomb.codec.protobuf.schema.TestSchemaToProtoGenerator.testListMapTypeCorrect`
`org.apache.servicecomb.codec.protobuf.schema.TestSchemaToProtoGenerator.test_springmvc_model_schema_correct`
The mentioned tests may non-deterministically pass or fail without changes made to the source code when it is run in different JVMs due to the inherent unordered nature of the fields within the message part of the schema being tested.
The first test expects part of the schema to be:
`
message DeptInfo {
string name = 1;
string code = 2;
repeated ScoreInfo scores = 3;
}
`
But it will sometimes return part of the schema as:
```
message DeptInfo {
string name = 1;
repeated ScoreInfo scores = 2;
string code = 3;
}
```
or 
```
message DeptInfo {
string code = …
```

[SCB-2893]-Fixes flaky tests in TestSchemaToProtoGenerator

---

service-registry/registry-consul/src/main/java/org/apache/servicecomb/registry/consul/ConsulDiscovery.java

The findServices should return a list of service names, but it actually returns a list of service IDs

[SCB-2895]The findServices method returns data errors

---

dependencies/default/pom.xml

- 将 vertx 版本从 4.5.12 升级到4.5.13
- 此次升级可能包含安全性更新和 bug 修复

[#4717]Bump vertx from 4.5.12 to 4.5.13

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/RandomRuleExt.java

-增加对 servers 列表的空值检查，避免空指针异常
- 使用 ThreadLocalRandom.current().nextInt(servers.size()) 替代 Math.abs(ThreadLocalRandom.current().nextInt()) % servers.size() 生成随机索引，提高性能

[#4716]Fix load balance rule may not properly handle integer overflow

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java
core/src/main/java/org/apache/servicecomb/core/governance/MatchType.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/provider/ProviderAuthFilter.java
handlers/handler-publickey-auth/src/test/java/org/apache/servicecomb/authentication/provider/TestPathCheckUtils.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/SwaggerUtils.java

1. Fix problem that `ProviderAuthFilter` not use absolute path.
2. Same logic has come up twice, move it to `SwaggerUtils`.
3. Add tests for `excludePathPatterns`/`includePathPatterns` feature in`handler-publickey-auth`
---

[#4722] Fix bug in `ProviderAuthFilter` where `requestPath` not absolute problem

---

service-registry/registry-service-center/src/main/java/org/apache/servicecomb/registry/sc/SCAddressManager.java
service-registry/registry-service-center/src/main/java/org/apache/servicecomb/registry/sc/SCRegistration.java

Subscribing to the `HeartBeatEvent` and publishing the `HeartBeatEvent` are handled by two different event buses. Therefore, the `SCAddressManager` will never receive the `HeartBeatEvent`. As a result, even if `servicecomb.registry.sc.autodiscovery: true` is configured, the system will not automatically refresh the SC address.
Fixes #4806 
---

[#4806] Fix the bug that the SC address is configured for automatic discovery but cannot be automatically refreshed
