cse-swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/SwaggerGenerator.java
cse-swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/schema/Schema.java
foundation-common/src/test/java/io/servicecomb/foundation/common/utils/TestFortifyUtils.java
serviceregistry/src/main/java/io/servicecomb/serviceregistry/RegistryUtils.java
serviceregistry/src/test/java/io/servicecomb/serviceregistry/TestRegistryWithEnvVar.java

[java-chassis #64] 支持容器部署功能：监听IP地址和注册中心注册的IP地址需要分别支持配置

---

foundation-common/src/main/resources/config/log4j.properties

with current logger pattern, docker maven plugin has trouble grabbing the expected log

JAV-38 changed log timestamp format

---

demo/demo-crossapp/crossapp-client/pom.xml
demo/demo-crossapp/crossapp-server/pom.xml
demo/demo-crossapp/pom.xml
demo/demo-jaxrs/jaxrs-client/pom.xml
demo/demo-jaxrs/jaxrs-server/pom.xml
demo/demo-jaxrs/pom.xml
demo/demo-local/pom.xml
demo/demo-perf-client/pom.xml
demo/demo-pojo/pojo-client/pom.xml
demo/demo-pojo/pojo-server/pom.xml
demo/demo-pojo/pom.xml
demo/demo-schema/pom.xml
demo/demo-server-servlet/pom.xml
demo/demo-spring-boot-discovery/demo-spring-boot-discovery-client/pom.xml
demo/demo-spring-boot-discovery/demo-spring-boot-zuul-proxy/pom.xml
demo/demo-spring-boot-discovery/pom.xml
demo/demo-spring-boot-transport/demo-spring-boot-pojo-client/pom.xml
demo/demo-spring-boot-transport/demo-spring-boot-pojo-server/pom.xml
demo/demo-spring-boot-transport/pom.xml
demo/demo-spring-boot/demo-spring-boot-jaxrs-client/pom.xml
demo/demo-spring-boot/demo-spring-boot-jaxrs-server/pom.xml
demo/demo-spring-boot/demo-spring-boot-springmvc-client/pom.xml
demo/demo-spring-boot/demo-spring-boot-springmvc-server/pom.xml
demo/demo-spring-boot/pom.xml
demo/demo-springmvc/pom.xml
demo/demo-springmvc/springmvc-client/pom.xml
demo/demo-springmvc/springmvc-server/pom.xml
demo/docker-build-config/pom.xml
demo/docker-run-config/pom.xml
demo/pom.xml

Just Renamed the group id to demo artifacts, also avoid the lib jar coping.

JAV-66 Renamed the group id of demo artifacts.

---

demo/docker-run-config/pom.xml

Update servicecenter iamges to the latest  version(made by the service-center latest code ).

Update servicecenter iamges

---

service-registry/src/test/java/io/servicecomb/serviceregistry/TestRegistry.java

(cherry picked from commit 0b1fe37)

JAV-98 attempted to fix failing test

---

demo/demo-pojo/pojo-client/src/main/java/io/servicecomb/demo/pojo/client/PojoClient.java
demo/demo-pojo/pojo-tests/src/test/resources/microservice.yaml
demo/demo-springmvc/springmvc-client/src/main/java/io/servicecomb/demo/springmvc/client/SpringmvcClient.java
foundation-common/src/main/java/io/servicecomb/foundation/common/base/RetryableRunnable.java
provider-pojo/src/main/java/io/servicecomb/provider/pojo/PojoConfig.java
provider-pojo/src/main/java/io/servicecomb/provider/pojo/PojoConsumerProvider.java
provider-pojo/src/test/java/io/servicecomb/provider/pojo/TestPojoConsumerProvider.java

Jav 107 configurable loading mode

---

java-chassis-distribution/src/assembly/assembly.xml
samples/codefirst-sample/pom.xml
samples/codefirst-sample/src/main/resources/META-INF.spring/pojo.server.bean.xml
samples/codefirst-sample/src/main/resources/client.microservice.yaml
samples/codefirst-sample/src/main/resources/config/log4j.demo.properties
samples/codefirst-sample/src/main/resources/server.microservice.yaml
samples/custom-handler-sample/pom.xml
samples/custom-handler-sample/src/main/java/io/servicecomb/samples/customerhandler/handlers/MyHandler.java
samples/custom-handler-sample/src/main/resources/client.microservice.yaml
samples/custom-handler-sample/src/main/resources/config/log4j.demo.properties
samples/custom-handler-sample/src/main/resources/server.microservice.yaml
samples/jaxrs-sample/pom.xml
samples/jaxrs-sample/src/main/resources/client.microservice.yaml
samples/jaxrs-sample/src/main/resources/config/log4j.demo.properties
samples/jaxrs-sample/src/main/resources/server.microservice.yaml
samples/pojo-sample/pom.xml
samples/pojo-sample/src/main/resources/client.microservice.yaml
samples/pojo-sample/src/main/resources/config/log4j.demo.properties
samples/pojo-sample/src/main/resources/server.microservice.yaml
samples/pom.xml
samples/springmvc-sample/pom.xml
samples/springmvc-sample/src/main/resources/client.microservice.yaml
samples/springmvc-sample/src/main/resources/config/log4j.demo.properties
samples/springmvc-sample/src/main/resources/server.microservice.yaml

Clean up log setting and fix some server startup issue.
TODO
Added the examples into distribution kit.

[WIP] Polish the Samples

---

integration-tests/pojo-test/pom.xml
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/PojoIntegrationTestBase.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/PojoService.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/PojoTestMain.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/RawPojoIntegrationTest.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/SomePojoConfig.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/endpoints/CodeFirstPojo.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/endpoints/HelloImpl.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/endpoints/SmartCareImpl.java
integration-tests/pojo-test/src/test/java/io/servicecomb/demo/pojo/test/endpoints/TestImpl.java
integration-tests/pojo-test/src/test/resources/log4j.properties
integration-tests/pojo-test/src/test/resources/microservice.yaml
integration-tests/pojo-test/src/test/resources/registry.yaml
integration-tests/pom.xml

added pojo tests to verify highway endpoints only

JAV-88 added pojo tests

---

samples/pojo-sample/pojo-consumer/src/main/java/io/servicecomb/samples/pojo/consumer/PojoConsumerMain.java

Signed-off-by: Lin Zhinan <linzhinan@huawei.com>

Fix output of pojo consumer.

---

java-chassis-dependencies/pom.xml

Signed-off-by: MabinGo <bin.ma@huawei.com>

JAV-415 Update Spring dependency from 4.3.4.RELEASE to 4.3.5.RELEASE

---

common/common-rest/src/test/java/io/servicecomb/common/rest/definition/UnitTestRestUtils.java
common/common-rest/src/test/java/io/servicecomb/common/rest/locator/TestMicroservicePaths.java
common/common-rest/src/test/java/io/servicecomb/common/rest/locator/TestOperationLocator.java
core/src/main/java/io/servicecomb/core/definition/CommonService.java

Signed-off-by: MabinGo <bin.ma@huawei.com>

JAV-401 fix typo

---

demo/docker-build-config/pom.xml
demo/docker-run-config/pom.xml

Just add the license and log wait for the service-center.

JAV-427 Fixed the demo docker run issue on Mac

---

demo/docker-build-config/pom.xml
demo/docker-run-config/pom.xml
java-chassis-dependencies/pom.xml

Removed the dependencies of narayana and jersey.

JAV-426 Clean up the third party dependenices

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/base/ServiceCombConstants.java
handlers/handler-tracing-zipkin/src/main/java/io/servicecomb/tracing/zipkin/TracingConfiguration.java
service-registry/src/main/java/io/servicecomb/serviceregistry/api/registry/MicroserviceFactory.java
service-registry/src/main/java/io/servicecomb/serviceregistry/api/registry/MicroserviceInstance.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/config/MicroservicePropertiesLoader.java
service-registry/src/main/java/io/servicecomb/serviceregistry/definition/DefinitionConst.java
service-registry/src/main/java/io/servicecomb/serviceregistry/definition/MicroserviceDefinition.java
service-registry/src/test/java/io/servicecomb/serviceregistry/api/registry/TestMicroserviceFactory.java
service-registry/src/test/java/io/servicecomb/serviceregistry/config/TestPropertiesLoader.java

JAV-430 standarized constants naming

---

java-chassis-dependencies/pom.xml

JAV-434 Upgrade jackson from 2.8.1 to 2.8.10

---

common/common-rest/src/main/java/io/servicecomb/common/rest/codec/RestObjectMapper.java
common/common-rest/src/test/java/io/servicecomb/common/rest/codec/TestRestObjectMapper.java

Signed-off-by: MabinGo <bin.ma@huawei.com>

[JAV-423] RESTful deserialization should ignore unknown properties automatically

---

demo/demo-jaxrs/jaxrs-server/src/main/java/io/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java
demo/demo-schema/src/main/java/io/servicecomb/demo/CodeFirstRestTemplate.java
demo/demo-schema/src/main/java/io/servicecomb/demo/ignore/IgnoreInterface.java
demo/demo-schema/src/main/java/io/servicecomb/demo/ignore/InputModelForTestIgnore.java
demo/demo-schema/src/main/java/io/servicecomb/demo/ignore/OutputModelForTestIgnore.java
demo/demo-springmvc/springmvc-server/src/main/java/io/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java

增加了Model Field @JsonIgnore的test case

JAV-402 add model field json ignore test

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/base/ServiceCombConstants.java
spring-boot-starter/spring-cloud-zuul-zipkin/src/main/java/io/servicecomb/spring/cloud/zuul/tracing/SpringTracingConfiguration.java
spring-boot-starter/spring-cloud-zuul-zipkin/src/test/java/io/servicecomb/spring/cloud/zuul/tracing/SpringTracingConfigurationTest.java

Signed-off-by: Eric Lee <lidagang1@huawei.com>

JAV-318 added switch for tracing

---

java-chassis-dependencies/pom.xml
samples/bmi/webapp/pom.xml
spring-boot-starter/pom.xml
spring-boot-starter/spring-cloud-zuul/pom.xml
spring-boot-starter/spring-cloud-zuul/src/main/java/io/servicecomb/spring/cloud/zuul/ContextHeaderZuulFilter.java

[JAV-459]added header for qps to work with zuul

---

demo/demo-jaxrs/jaxrs-server/src/main/java/io/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java
demo/demo-springmvc/springmvc-server/src/main/java/io/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/TestCseServer.java
java-chassis-dependencies/pom.xml
service-registry/src/main/java/io/servicecomb/serviceregistry/api/Const.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/RestUtils.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/test/java/io/servicecomb/serviceregistry/api/TestConst.java

include some compile warning fix

[JAV-461]service center API change

---

common/common-rest/src/main/java/io/servicecomb/common/rest/definition/RestOperationMeta.java
common/common-rest/src/test/java/io/servicecomb/common/rest/definition/TestRestOperationMeta.java

operation declared to produce text/plain
consumer use accept widecard to send request
but producer produced json format response

JAV-472 fix rest produce select bug

---

common/common-rest/src/main/java/io/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/io/servicecomb/common/rest/TestAbstractRestInvocation.java
edge/edge-core/src/main/java/io/servicecomb/edge/core/EdgeInvocation.java
edge/edge-core/src/test/java/io/servicecomb/edge/core/TestEdgeInvocation.java

when HttpServerFilter.afterReceiceRequest return none null, do not call into business operation

JAV-473 fix usage of HttpServerFilter.afterReceiceRequest result

---

samples/README.md

modify to http://servicecomb.io/cn/users/setup-environment/

udpate setup environment url

---

samples/bmi/calculator/src/main/java/io/servicecomb/samples/bmi/BMIViewObject.java
samples/bmi/calculator/src/main/java/io/servicecomb/samples/bmi/CalculatorRestEndpoint.java
samples/bmi/calculator/src/main/java/io/servicecomb/samples/bmi/CalculatorServiceImpl.java
samples/bmi/calculator/src/main/java/io/servicecomb/samples/bmi/InstanceInfoService.java
samples/bmi/calculator/src/main/java/io/servicecomb/samples/bmi/InstanceInfoServiceImpl.java
samples/bmi/webapp/src/main/resources/application.yaml
samples/bmi/webapp/src/main/resources/microservice.yaml
samples/bmi/webapp/src/main/resources/static/index.html

minor changes of service interface in bmi

---

demo/demo-schema/src/main/resources/microservices/springmvc/controller.yaml
demo/demo-springmvc/springmvc-client/src/main/java/io/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-server/src/main/java/io/servicecomb/demo/springmvc/server/ControllerImpl.java
integration-tests/springmvc-tests/src/test/java/io/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
integration-tests/springmvc-tests/src/test/java/io/servicecomb/demo/springmvc/tests/endpoints/ControllerImpl.java
integration-tests/springmvc-tests/src/test/java/io/servicecomb/demo/springmvc/tests/endpoints/ControllerSimplifiedMappingAnnotationImpl.java
providers/provider-springmvc/src/main/java/io/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/main/java/io/servicecomb/provider/springmvc/reference/UrlWithServiceNameClientHttpRequestFactory.java
providers/provider-springmvc/src/test/java/io/servicecomb/provider/springmvc/reference/TestUrlWithServiceNameClientHttpRequestFactory.java

```
RestTemplate template = new CseRestTemplate();
template.setRequestFactory(new UrlWithServiceNameClientHttpRequestFactory());
```
and then use template instance to work in this mode.

JAV-491 Url with servicename

---

handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/TestSessionSticknessRule.java
samples/bmi/README.md
samples/bmi/webapp/src/main/resources/application.yaml

#270 修改sample模块端口为8889

---

common/common-rest/src/main/java/io/servicecomb/common/rest/RestProducerInvocation.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/MetricsServoRegistry.java
foundations/foundation-metrics/src/test/java/io/servicecomb/foundation/metrics/TestMetricsServoRegistry.java

Rebase to latest master, process Conflicts:RestProducerInvocation and fix unit test

JAV-416 expose and publish metrics using servo

---

service-registry/src/main/java/io/servicecomb/serviceregistry/api/registry/MicroserviceInstance.java

Rename function name to camel style

Rename function name

---

core/src/main/java/io/servicecomb/core/Transport.java
core/src/main/java/io/servicecomb/core/executor/FixedThreadExecutor.java
core/src/test/java/io/servicecomb/core/TestExecutors.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/net/URIEndpointObject.java

Signed-off-by: smilemusic <185735018@qq.com>

fix world spell error in comments and variable

---

foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/MetricsConfig.java

about issue #327 ,url as below
https://github.com/ServiceComb/ServiceComb-Java-Chassis/issues/327

fix #327 turnoff Metrics log func

---

.travis.yml

Split Travis Build to Different Stages

---

.github/PULL_REQUEST_TEMPLATE.md

Just added the PR template for the contributor to use as reference.

JAV-514 Added the PULL-REQUEST for the contributor of java-chassis

---

core/src/test/java/io/servicecomb/core/TestDefinition.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/RegisterManager.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/client/tcp/TcpClientConnection.java
providers/provider-pojo/src/main/java/io/servicecomb/provider/pojo/PojoProducerProvider.java
providers/provider-pojo/src/main/java/io/servicecomb/provider/pojo/schema/PojoProducers.java
providers/provider-pojo/src/test/java/io/servicecomb/provider/pojo/TestPojoProducerProvider.java
providers/provider-pojo/src/test/java/io/servicecomb/provider/pojo/schema/TestPojoProducers.java

fixed typos of regsiter and PojoProducer.getProcucers

---

swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/extend/ModelResolverExt.java

fix typo error

---

swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/extend/ModelResolverExt.java

more accurate log with error type information

---

common/common-protobuf/src/test/java/io/protostuff/runtime/model/ModelProtobuf.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/MetricsServoRegistry.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/client/tcp/AbstractTcpClientConnectionPool.java
service-registry/src/main/java/io/servicecomb/serviceregistry/cache/InstanceCache.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersions.java
swagger/swagger-invocation/invocation-core/src/main/java/io/servicecomb/swagger/invocation/converter/ConverterMgr.java
swagger/swagger-invocation/invocation-core/src/main/java/io/servicecomb/swagger/invocation/response/Headers.java
swagger/swagger-invocation/invocation-core/src/main/java/io/servicecomb/swagger/invocation/response/ResponsesMeta.java

simplify usage of map method

---

core/src/main/java/io/servicecomb/core/transport/TransportManager.java
demo/demo-signature/src/main/java/io/servicecomb/demo/signature/SignatureUtils.java
edge/edge-core/src/main/java/io/servicecomb/edge/core/OperationInstancesDiscoveryFilter.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/utils/SPIServiceUtils.java
service-registry/src/main/java/io/servicecomb/serviceregistry/discovery/DiscoveryTree.java

replace compare method with java8 Comparator way

---

core/src/main/java/io/servicecomb/core/Endpoint.java
core/src/main/java/io/servicecomb/core/Invocation.java
transports/transport-rest/transport-rest-client/src/main/java/io/servicecomb/transport/rest/client/http/VertxHttpMethod.java

typo error fix

---

foundations/foundation-config-cc/pom.xml
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/archaius/sources/ConfigCenterConfigurationSourceImpl.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/ConfigCenterClient.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/ConfigCenterConfig.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/MemberDiscovery.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/ParseConfigUtils.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/URIConst.java
foundations/foundation-config-cc/src/main/resources/META-INF/services/io.servicecomb.config.spi.ConfigCenterConfigurationSource
foundations/foundation-config-cc/src/test/java/io/servicecomb/config/archaius/sources/TestConfigCenterConfigurationSource.java
foundations/foundation-config-cc/src/test/java/io/servicecomb/config/client/TestConfigCenterClient.java
foundations/foundation-config-cc/src/test/java/io/servicecomb/config/client/TestConfigCenterConfig.java
foundations/foundation-config-cc/src/test/java/io/servicecomb/config/client/TestMemberDiscovery.java
foundations/foundation-config-cc/src/test/java/io/servicecomb/config/client/TestParseConfigUtils.java
foundations/foundation-config-cc/src/test/java/io/servicecomb/config/client/TestURIConst.java
foundations/foundation-config-cc/src/test/resources/microservice.yaml
foundations/pom.xml

1. several integration starters to spring cloud depends on this
2. modified license and package name
3. modified some code dependent on authentication
5. format code
The logic of original code remains untouched

[JAV-553]Added config center configuration client 

---

.travis.yml

Just skip the deploy work in travis PR build
---

Avoid deploying stage during the PR

---

common/common-protobuf/src/test/java/io/servicecomb/codec/protobuf/jackson/TestParamSerializer.java
common/common-protobuf/src/test/java/io/servicecomb/codec/protobuf/jackson/TestResultSerializer.java
common/common-protobuf/src/test/java/io/servicecomb/codec/protobuf/jackson/TestStandardObjectWriter.java
core/src/test/java/io/servicecomb/core/TestConsumer.java
providers/provider-springmvc/src/test/java/org/springframework/web/client/TestCseHttpMessageConverter.java
transports/transport-rest/transport-rest-servlet/src/test/java/io/servicecomb/transport/rest/servlet/TestRestServletContextListener.java

removed redundant catch block in try statement

---

foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/performance/MetricsDataMonitor.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/performance/QueueMetricsData.java

removed unnecessary boxing

---

common/common-protobuf/src/main/java/io/protostuff/runtime/ProtobufCompatibleUtils.java
common/common-protobuf/src/test/java/io/servicecomb/codec/protobuf/jackson/TestAbstractDeserializer.java
common/common-rest/src/main/java/io/servicecomb/common/rest/definition/path/PathRegExp.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/archaius/sources/ConfigCenterConfigurationSourceImpl.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/ConfigCenterClient.java
handlers/handler-loadbalance/src/test/java/io/servicecomb/loadbalance/TestLoadBalancer.java
service-registry/src/test/java/io/servicecomb/serviceregistry/client/TestIpPortManager.java
service-registry/src/test/java/io/servicecomb/serviceregistry/registry/TestRemoteServiceRegistry.java
transports/transport-highway/src/test/java/io/servicecomb/transport/highway/TestHighwayTransport.java

replace explicit type with <> #379

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/utils/FilePerm.java
foundations/foundation-config-cc/src/main/java/io/servicecomb/config/client/ConfigCenterConfig.java
spring-boot-starter/spring-boot-starter-configuration/src/main/java/io/servicecomb/springboot/starter/configuration/ConfigurableEnvironmentConfiguration.java
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/unittest/SwaggerGeneratorForTest.java
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/pojo/PojoSwaggerGeneratorContext.java
swagger/swagger-invocation/invocation-core/src/main/java/io/servicecomb/swagger/invocation/converter/impl/SameElementArrayToSet.java

replace iteration with bulk operation

---

samples/pom.xml

remove non-exist module name

---

common/common-rest/src/main/java/io/servicecomb/common/rest/definition/path/URLPathBuilder.java

Use StringBuilder instead of String in loops for concatenation

---

service-registry/src/main/java/io/servicecomb/serviceregistry/version/Version.java
service-registry/src/main/java/io/servicecomb/serviceregistry/version/VersionRuleUtils.java
service-registry/src/main/java/io/servicecomb/serviceregistry/version/VersionUtils.java

minor standard implementation detail of version

---

common/common-protobuf/src/main/java/io/servicecomb/codec/protobuf/jackson/ParamSerializer.java
common/common-protobuf/src/test/java/io/protostuff/runtime/model/ModelProtobuf.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/utils/SPIServiceUtils.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/performance/PerfStatImpl.java
foundations/foundation-ssl/src/main/java/io/servicecomb/foundation/ssl/CertificateUtil.java
service-registry/src/main/java/io/servicecomb/serviceregistry/config/ServiceRegistryConfig.java

simplify loops with foreach

---

foundations/foundation-config-cc/src/test/java/io/servicecomb/config/client/TestURIConst.java
foundations/foundation-ssl/src/test/java/io/servicecomb/foundation/ssl/SSLOptionTest.java

delete unnecessary import

---

service-registry/src/main/java/io/servicecomb/serviceregistry/config/AbstractPropertiesLoader.java

add warning log if developers use the deprecated properties

---

handlers/handler-bizkeeper/src/main/java/io/servicecomb/bizkeeper/Configuration.java
handlers/handler-bizkeeper/src/test/java/io/servicecomb/bizkeeper/TestConfiguration.java

adjust the DEFAULT_MAX_CONCURRENT_REQUESTS

JAV-557-adjust the DEFAULT_MAX_CONCURRENT_REQUESTS

---

service-registry/src/main/java/io/servicecomb/serviceregistry/config/ServiceRegistryConfig.java

log a warning when user uses an illegal workerPoolSize

---

integration-tests/spring-springmvc-tests/pom.xml
integration-tests/springmvc-tests/pom.xml

Jav 547 springmvc test fix

---

demo/demo-springmvc/springmvc-client/src/main/java/io/servicecomb/demo/springmvc/client/SpringmvcClient.java

---
Fix https://github.com/ServiceComb/ServiceComb-Java-Chassis/issues/415

Comment fix

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/token/RSAKeypair4Auth.java
foundations/foundation-vertx/src/main/java/io/servicecomb/foundation/vertx/http/HttpServletRequestEx.java
handlers/handler-bizkeeper/src/main/java/io/servicecomb/bizkeeper/FallbackPolicy.java
service-registry/src/test/java/io/servicecomb/serviceregistry/discovery/TestAbstractDiscoveryFilter.java
transports/transport-rest/transport-rest-servlet/src/test/java/io/servicecomb/transport/rest/servlet/TestRestAsyncListener.java
transports/transport-rest/transport-rest-vertx/src/test/java/io/servicecomb/transport/rest/vertx/TestAbstractVertxHttpDispatcher.java

removed unnecessary semicolons

---

service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/HttpClientPool.java
service-registry/src/main/java/io/servicecomb/serviceregistry/config/ServiceRegistryConfig.java

connect to servicecenter by config proxy

JAV-570 connect to servicecenter by config proxy

---

common/common-rest/src/test/java/io/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/main/java/io/servicecomb/core/provider/consumer/InvokerUtils.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/http/HttpStatusManager.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/utils/SPIServiceUtils.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/performance/PerfStatMonitorMgr.java
foundations/foundation-metrics/src/test/java/io/servicecomb/foundation/metrics/performance/TestPerfStatMonitorMgr.java
foundations/foundation-test-scaffolding/src/main/java/io/servicecomb/foundation/test/scaffolding/spring/SpringUtils.java

replace lambda with method reference

---

service-registry/src/main/java/io/servicecomb/serviceregistry/task/MicroserviceInstanceHeartbeatTask.java
service-registry/src/main/java/io/servicecomb/serviceregistry/task/event/HeartbeatSuccEvent.java

service center miss heartbeat success event, so can't deal wth failure alarm

JAV-577 service center miss heartbeat success event

---

common/common-rest/src/main/java/io/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/main/java/io/servicecomb/common/rest/definition/RestOperationMeta.java
common/common-rest/src/test/java/io/servicecomb/common/rest/TestAbstractRestInvocation.java
common/common-rest/src/test/java/io/servicecomb/common/rest/definition/TestRestOperationMeta.java
integration-tests/springmvc-tests/src/test/java/io/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
samples/auth-sample/auth-consumer/pom.xml
samples/auth-sample/auth-provider/pom.xml
samples/codefirst-sample/codefirst-consumer/pom.xml
samples/codefirst-sample/codefirst-provider/pom.xml
samples/custom-handler-sample/custom-handler-consumer/pom.xml
samples/custom-handler-sample/custom-handler-provider/pom.xml
samples/jaxrs-sample/jaxrs-consumer/pom.xml
samples/jaxrs-sample/jaxrs-provider/pom.xml
samples/pojo-sample/pojo-consumer/pom.xml
samples/pojo-sample/pojo-provider/pom.xml
samples/pom.xml
samples/springmvc-sample/springmvc-consumer/pom.xml
samples/springmvc-sample/springmvc-provider/pom.xml

fix bug:
declare only produce text, and consume by json,javascript,*.*,  but produced json

[JAV-571] Produce mediatype determine

---

handlers/handler-loadbalance/src/main/java/io/servicecomb/loadbalance/LoadbalanceHandler.java

[JAVA-961] Dynamic configuration is not valid at some time

---

handlers/handler-bizkeeper/src/main/java/io/servicecomb/bizkeeper/BizkeeperCommand.java

[JAV-584]fallback logic optimize

---

foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/output/servo/RollingMetricsFileOutput.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/output/servo/SimpleMetricsContentFormatter.java
samples/bmi/calculator/pom.xml
samples/bmi/calculator/src/main/resources/log4j2.xml
samples/bmi/calculator/src/main/resources/microservice.yaml

(cherry picked from commit 26667d42d4077a3e2270e80731942ebd54be0b1d)
Apply 0.5.x metrics patch to 0.6.0-SNAPSHOT
---
Apply 0.5.x metrics patch to 0.6.0-SNAPSHOT

Apply 0.5.x metrics patch to 0.6.0-SNAPSHOT

---

common/common-rest/src/main/java/io/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/io/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/main/java/io/servicecomb/core/Invocation.java
foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/MetricsServoRegistry.java
handlers/handler-bizkeeper/src/main/java/io/servicecomb/bizkeeper/BizkeeperHandler.java
samples/springmvc-sample/springmvc-consumer/src/main/java/io/servicecomb/samples/springmvc/consumer/SpringmvcConsumerMain.java
samples/springmvc-sample/springmvc-consumer/src/main/resources/microservice.yaml
samples/springmvc-sample/springmvc-provider/src/main/java/io/servicecomb/samples/springmvc/provider/SpringmvcHelloImpl.java
samples/springmvc-sample/springmvc-provider/src/main/resources/microservice.yaml
transports/transport-highway/src/main/java/io/servicecomb/transport/highway/HighwayServerInvoke.java

---
Fix 0.5.x version metrics merge patch no data bug 
https://github.com/apache/incubator-servicecomb-java-chassis/pull/459

[SCB-124] Fix 0.5.x metrics update patch bug

---

README.md

---
include ASP disclaimer in readme file. repo description may also need to be update.
fix SCB-123 for chassis repo.

include ASF disclaimer

---

.github/PULL_REQUEST_TEMPLATE.md

SCB-130 Updated the Github PR template

---

foundations/foundation-metrics/src/main/java/io/servicecomb/foundation/metrics/output/servo/RollingMetricsFileOutput.java
samples/bmi/calculator/src/main/resources/log4j2.xml

---
metrics 0.5.0 output level for write file change from error to trace because this LogEvent is not a "log"

[SCB-148] change write file log level

---

.github/PULL_REQUEST_TEMPLATE.md
java-chassis-dependencies/pom.xml
tracing/tracing-zipkin/src/test/java/io/servicecomb/tracing/zipkin/ZipkinSpanAspectTest.java
tracing/tracing-zipkin/src/test/java/io/servicecomb/tracing/zipkin/ZipkinTracingAdviserTest.java

[SCB-146] Upgrade Zipkin-brave to 4.13.1

---

core/src/main/java/io/servicecomb/core/Invocation.java
core/src/main/java/io/servicecomb/core/metrics/InvocationFinishedEvent.java
core/src/main/java/io/servicecomb/core/metrics/InvocationStartProcessingEvent.java
core/src/main/java/io/servicecomb/core/provider/consumer/InvokerUtils.java
metrics/metrics-core/src/test/java/io/servicecomb/metrics/core/TestEventAndRunner.java
metrics/pom.xml
transports/transport-highway/src/main/java/io/servicecomb/transport/highway/HighwayClient.java
transports/transport-rest/transport-rest-client/src/main/java/io/servicecomb/transport/rest/client/http/VertxHttpMethod.java

---
Add event trigger for InvocationType.CONSUMER in HighwayClient.java and VertxHttpMethod.java
please check if anything is missing

[SCB-126] Add Consumer side event trigger for collect metrics data

---

core/src/main/java/io/servicecomb/core/provider/consumer/InvokerUtils.java
demo/demo-springmvc/springmvc-client/src/main/java/io/servicecomb/demo/springmvc/client/SpringmvcClient.java

[SCB-156] Improvement SpringMVC Integration Test and InvokeUtils

---

handlers/handler-bizkeeper/src/main/java/io/servicecomb/bizkeeper/BizkeeperHandler.java
handlers/handler-bizkeeper/src/main/java/io/servicecomb/bizkeeper/HystrixCommandPropertiesExt.java
handlers/handler-bizkeeper/src/test/java/io/servicecomb/bizkeeper/TestBizkeeperHandler.java
handlers/handler-bizkeeper/src/test/java/io/servicecomb/bizkeeper/TestConfiguration.java
handlers/handler-bizkeeper/src/test/java/io/servicecomb/bizkeeper/TestHystrixPropertiesStrategyExt.java

[SCB-180] Hystrixcommand setter not set by dynamic configuration

---

swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/AbstractSwaggerGeneratorContext.java
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/OperationGenerator.java
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/SwaggerGenerator.java
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/processor/annotation/ApiProcessor.java
swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/TestOperationGenerator.java
swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/TestSwaggerGenerator.java
swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/processor/annotation/ApiOperationProcessorTest.java
swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/processor/annotation/ApiProcessorTest.java
swagger/swagger-generator/generator-core/src/test/java/io/servicecomb/swagger/generator/core/processor/annotation/SwaggerDefinitionProcessorTest.java

---
See details in [https://issues.apache.org/jira/browse/SCB-195](https://issues.apache.org/jira/browse/SCB-195).
- users can specify default tags to operations by using `@Api`, the default tags can be overwritten by `@ApiOperation` in operation level
- improve empty value filter logic of `@SwaggerDefinition`

[SCB-195] Support swagger @Api annotation to specify default tags

---

core/src/main/java/io/servicecomb/core/definition/loader/DynamicSchemaLoader.java
foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/net/IpPort.java
foundations/foundation-common/src/test/java/io/servicecomb/foundation/common/net/TestIpPort.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/IpPortManager.java
service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/consumer/MicroserviceVersions.java
service-registry/src/main/java/io/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java
service-registry/src/main/java/io/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java
service-registry/src/test/java/io/servicecomb/serviceregistry/client/TestIpPortManager.java
service-registry/src/test/java/io/servicecomb/serviceregistry/client/http/TestClientHttp.java

[SCB-165] Service registry not given proper instances

---

foundations/foundation-common/src/main/java/io/servicecomb/foundation/common/base/ServiceCombConstants.java
handlers/handler-tracing-zipkin/pom.xml
handlers/handler-tracing-zipkin/src/main/java/io/servicecomb/tracing/zipkin/ConsumerInvocationAdapter.java
handlers/handler-tracing-zipkin/src/main/java/io/servicecomb/tracing/zipkin/ProviderInvocationAdapter.java
handlers/handler-tracing-zipkin/src/main/java/io/servicecomb/tracing/zipkin/TracingConfiguration.java
integration-tests/pom.xml
integration-tests/test-common/pom.xml
integration-tests/test-common/src/test/java/io/servicecomb/tests/tracing/TracingTestBase.java
java-chassis-dependencies/pom.xml
tracing/tracing-zipkin/pom.xml
tracing/tracing-zipkin/src/test/java/io/servicecomb/tracing/zipkin/ZipkinSpanAspectTest.java
tracing/tracing-zipkin/src/test/java/io/servicecomb/tracing/zipkin/ZipkinTracingAdviserTest.java

Upgraded zipkin to zipkin2:2.4.2 and zipkin-reporter to zipkin-reporter2:2.2.2.
The zipkin2.Span changed a lot from the old zipkin.Span and the tests are modified accordingly.
---

[SCB-172] upgrade zipkin libraries to zipkin2

---

metrics/metrics-integration/pom.xml

[SCB-118] fix modules missing in pom

---

service-registry/src/main/java/io/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/io/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java

---
AbstractServiceRegistry findServiceInstance process null return value, not print too much exception

[SCB-214] AbstractServiceRegistry findServiceInstance process null return value, not print too much exception

---

samples/bmi/calculator/src/main/resources/microservice.yaml

---
recovery delete misoperation

[SCB-222] recovery microservice.yaml in bmi Calculator

---

common/common-protobuf/src/main/java/io/servicecomb/codec/protobuf/utils/ProtobufSchemaUtils.java
integration-tests/jaxrs-tests/src/test/java/io/servicecomb/demo/jaxrs/tests/JaxrsIntegrationTestBase.java
integration-tests/jaxrs-tests/src/test/java/io/servicecomb/demo/jaxrs/tests/endpoints/SchemaFirstJaxrs.java
integration-tests/jaxrs-tests/src/test/java/io/servicecomb/demo/jaxrs/tests/endpoints/SomeAbstractJaxrsRestEndpoint.java
integration-tests/jaxrs-tests/src/test/resources/microservices/jaxrs/schemaFirst.yaml
swagger/swagger-generator/generator-core/src/main/java/io/servicecomb/swagger/generator/core/utils/ClassUtils.java

SCB-179 support -(identifiers) as parameter name with RequestParam

---

java-chassis-dependencies/pom.xml

findbugs:annotaions is licenced under lgpl which is prohibited by apache policy
---

[SCB-238] Remove dependency on findbugs:annotaions

---

java-chassis-dependencies/pom.xml

SCB-250 Update netty's version to 4.1.17 and jackson's version to 2.9.2

---

integration-tests/dynamic-config-tests/pom.xml
integration-tests/dynamic-config-tests/src/test/java/org/apache/dynamicconfig/test/DynamicConfigurationIT.java
integration-tests/dynamic-config-tests/src/test/resources/log4j.properties
integration-tests/dynamic-config-tests/src/test/resources/microservice.yaml
integration-tests/pom.xml

SCB-29 integration tests for dynamic configuration

---

NOTICE
java-chassis-distribution/src/assembly/assembly.xml

Include none apache 2.0 licensed third parties to NOTICE and
add NOTICE and LICENSE files to zip archive for releasing
---

[SCB-260] update project NOTICE file

---

integration-tests/dynamic-config-tests/pom.xml
integration-tests/dynamic-config-tests/src/test/java/org/apache/dynamicconfig/test/DynamicConfigurationIT.java

remove unused import 
add name for module pom 
---

SCB-29 remove unused import

---

foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsServoRegistry.java
metrics/metrics-common/src/main/java/org/apache/servicecomb/metrics/common/RegistryMetric.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/CounterService.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/DefaultCounterService.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/DefaultGaugeService.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/DefaultWindowCounterService.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/GaugeService.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/WindowCounter.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/custom/WindowCounterService.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/monitor/RegistryMonitor.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestCustomMetrics.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestEventAndRunner.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestHealthCheckerManager.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestHealthCheckerPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestStatusDimension.java
metrics/metrics-integration/metrics-prometheus/src/main/java/org/apache/servicecomb/metrics/prometheus/MetricsCollector.java
samples/custom-business-metrics/pom.xml
samples/custom-business-metrics/src/main/java/org/apache/servicecomb/samples/metrics/custom/CustomMetricsApplication.java
samples/custom-business-metrics/src/main/java/org/apache/servicecomb/samples/metrics/custom/ShopDemoService.java
samples/custom-business-metrics/src/main/resources/microservice.yaml
samples/metrics-write-file-sample/metrics-write-file/src/test/java/org/apache/servicecomb/samples/mwf/TestWriteFile.java
samples/pom.xml

---
Add custom metrics interface for user define his/her own business metrics,also a sample in "custom-business-metrics"
```java
@Component
public class ShopDemoService {
private final CounterService counterService;
private final GaugeService gaugeService;
private final WindowCounterService windowCounterService;
//autowire metrics service
@Autowired
public ShopDemoService(CounterService counterService, GaugeService gaugeService,
WindowCounterService windowCounterService) {
this.counterService = counterService;
this.gaugeService = gaugeService;
this.windowCounterService = windowCounterService;
login(null,null);
}
public void login(String name, String …
```

[SCB-12] Support Custom Metrics

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/ClientPoolManager.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/client/TestClientPoolManager.java

ClientPoolManager save thread binding information to map, will cause memory leak when using dynamic thread pool

[SCB-299] bug fix: ClientPoolManager thread binding memory leak.

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/ServiceCombConstants.java
pom.xml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/Versions.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/FrameworkVersions.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/MicroserviceFactory.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/ServiceCombVersion.java
service-registry/src/main/resources/META-INF/services/org.apache.servicecomb.serviceregistry.api.Versions
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestFrameworkVersions.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestServiceCombVersion.java

---
after mvn package,MicroserviceFactory.class.getPackage().getImplementationVersion() will read version from MANIFEST.MF, it also been tested in tomcat

[SCB-325] report sdk version when register to SC

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/AddressResolverConfig.java

[SCB-315] Resolve the Registry-Service UT test fail

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestTransportClientConfig.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestTransportConfig.java

[SCB-314] Support custom rest transport server compress and max header size

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/consumer/MicroserviceManager.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/consumer/MicroserviceVersions.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceManager.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceVersions.java

[SCB-294]when send a request to a not exist microservice, edge will always try to find instances of it

---

java-chassis-dependencies/pom.xml

---
See details in https://issues.apache.org/jira/browse/SCB-351

[SCB-351] upgrade Jackson to 2.9.4 to avoid security risk

---

dynamic-config/config-apollo/src/main/java/org/apache/servicecomb/config/archaius/sources/ApolloConfigurationSourceImpl.java
dynamic-config/config-apollo/src/test/resources/microservice.yaml
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/archaius/sources/ConfigCenterConfigurationSourceImpl.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/spi/ConfigCenterConfigurationSource.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/MapBasedConfigurationSource.java
samples/config-apollo-sample/src/main/resources/microservice.yaml

---
Use apollo.config.serverUri to note address of Apollo configuration.
Remove cse.config.client.serverUri which is useless.

SCB-210 remove extra useless config item

---

foundations/foundation-ssl/pom.xml
foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLOption.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestVertxTLSBuilder.java
java-chassis-dependencies/pom.xml

[SCB-368] supports openssl engine for ssl communication

---

samples/README.md
samples/metrics-extend-healthcheck/README.md
samples/metrics-write-file-sample/README.md

---
Add README.md for metrics health check sample and write metrics to file sample

[SCB-6] add metrics samples readme

---

samples/auth-sample/README.md
samples/bmi/README.md
samples/codefirst-sample/README.md
samples/custom-handler-sample/README.md
samples/jaxrs-sample/README.md
samples/pojo-sample/README.md
samples/springmvc-sample/README.md

[SCB-378] add readme document for samples

---

samples/auth-sample/README.md
samples/auth-sample/auth-consumer/src/main/java/org/apache/servicecomb/samples/springmvc/consumer/AuthConsumerMain.java
samples/auth-sample/auth-provider/src/main/resources/microservice.yaml
samples/codefirst-sample/README.md
samples/custom-handler-sample/README.md
samples/jaxrs-sample/README.md
samples/metrics-extend-healthcheck/pom.xml
samples/metrics-write-file-sample/metrics-write-file-log4j2-springboot/pom.xml
samples/pojo-sample/README.md
samples/springmvc-sample/README.md
samples/springmvc-sample/springmvc-consumer/src/main/java/org/apache/servicecomb/samples/springmvc/consumer/SpringmvcConsumerMain.java

---
1.Update all java chassis samples ReadMe file add "how to verify" chapter
2.fix small mistakes

[SCB-386] Update all java chassis samples ReadMe file add "how to verify" chapter and fix small mistakes

---

demo/docker-run-config/pom.xml
integration-tests/dynamic-config-tests/pom.xml

…s-on setting
---
More detail can be found : https://dmp.fabric8.io/#start-depends-on

[SCB-382] upgrade io.fabric8 docker-maven-plugin version and fix depends-on setting

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java

---
we keep pull stategy always work ,no matter watch switch open or not
@liubao68 @wujimin @weichao666 @WillemJiang

[SCB-401]keep pull strategy always alive whatever watch strategy state

---

java-chassis-distribution/src/assembly/bin.xml
java-chassis-distribution/src/assembly/src.xml

[SCB-404] Use different base folder for source/binary package

---

common/common-protobuf/src/test/java/io/protostuff/runtime/model/ModelProtobuf.proto
demo/demo-schema/src/main/resources/microservices/no-use/cse.basic.Basic/main.idl
demo/demo-schema/src/main/resources/microservices/no-use/hello/main.idl
demo/demo-schema/src/main/resources/microservices/no-use/helloworld.Greeter/main.idl
demo/demo-schema/src/main/resources/microservices/no-use/helloworld.Standard/main.idl
demo/demo-schema/src/main/resources/microservices/no-use/server/main.idl

[SCB-403] Add missing ASF headers

---

samples/config-apollo-sample/README.md

[SCB-378] fix apllo readme

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/ClientVerticle.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java

[SCB-365]when configured ssl certificates not exists, startup will hang and no error messages

---

demo/demo-springmvc/springmvc-server/pom.xml
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/MemberDiscovery.java
dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/client/TestMemberDiscovery.java

when configured multiple cc addresses and error happens, will not change an available one

[SCB-398]fix config cc do not select other instances when error happens

---

foundations/foundation-metrics/pom.xml
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/publish/spectator/DefaultTagFinder.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/publish/spectator/MeasurementGroupConfig.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/publish/spectator/MeasurementNode.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/publish/spectator/MeasurementTree.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/publish/spectator/TagFinder.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/spectator/TestDefaultTagFinder.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/spectator/TestMeasurementGroupConfig.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/spectator/TestMeasurementNode.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/spectator/TestMeasurementTree.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/publish/spectator/TestTagFinder.java
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-369] Extract info from spectator measurement

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestProducerInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/main/java/org/apache/servicecomb/core/event/InvocationFinishEvent.java
core/src/main/java/org/apache/servicecomb/core/event/InvocationStartEvent.java
core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
core/src/test/java/org/apache/servicecomb/core/TestInvocation.java
core/src/test/java/org/apache/servicecomb/core/event/TestInvocationFinishEvent.java
core/src/test/java/org/apache/servicecomb/core/event/TestInvocationStartEvent.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocation.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestEdgeInvocation.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayCodec.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServer.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerConnection.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerInvoke.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerVerticle.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayTransport.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayCodec.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayServerConnection.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayServerInvoke.java

invocation publish start and finish event, and event subscribers can get startTime/startExecutionTime/finishTime from invocation or event.

[SCB-374] Invocation publish life event

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/base/ServiceCombConstants.java
foundations/foundation-config/src/main/resources/mapping.yaml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/Microservice.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/MicroserviceFactory.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestMicroService.java

[SCB-396] java-sdk needs to distinguish the services belongs to the devops stage(environment)

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java

[SCB-374] fix NPE when 404 not found

---

etc/releaseNotes.md

[SCB-414] fix releaseNotes

---

samples/config-apollo-sample/src/main/resources/microservice.yaml

[SCB-415] change cluster value from "test-cluster" to "default"

---

samples/auth-sample/README.md
samples/auth-sample/auth-consumer/src/main/java/org/apache/servicecomb/samples/auth/consumer/AuthConsumerMain.java
samples/auth-sample/auth-provider/src/main/java/org/apache/servicecomb/samples/auth/provider/AuthProviderMain.java
samples/auth-sample/auth-provider/src/main/java/org/apache/servicecomb/samples/auth/provider/SpringmvcHelloImpl.java
samples/auth-sample/auth-provider/src/main/resources/META-INF/spring/auth.provider.bean.xml
samples/pojo-sample/pojo-consumer/src/main/resources/META-INF/spring/pojo.consumer.bean.xml
samples/springmvc-sample/springmvc-consumer/src/main/resources/META-INF/spring/springmvc.consumer.bean.xml

[SCB-413] fix pojo consumer sample bean xml

---

samples/README.md

[SCB-417] delete useless lines in readme

---

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java

---
Jira issue: [https://issues.apache.org/jira/browse/SCB-420](https://issues.apache.org/jira/browse/SCB-420)

[SCB-420] change default HTTP header size limitation to 32K

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterConfig.java
dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/client/TestConfigCenterConfig.java
dynamic-config/config-cc/src/test/resources/microservice.yaml

---
Get configuration interface to add header x-environment: development|testing|acceptance|production, the default is "" (empty)
links to:
[java-sdk needs to distinguish the services belongs to the devops stage(environment)](https://github.com/apache/incubator-servicecomb-java-chassis/pull/591)

[SCB-424] get configuration interface to add header:x-environment

---

etc/eclipse-java-google-style.xml
etc/intellij-java-google-style.xml
java-chassis-distribution/src/assembly/src.xml

Exclude the style file from the release kit.

SCB-427 Excluded the google style file from src release kit

---

demo/perf/src/main/java/org/apache/servicecomb/demo/perf/RedisSession.java
pom.xml
samples/bmi/webapp/src/main/resources/application.yaml
scripts/travis.sh

Clean up the old License header
Add the Rat Check to Travis CI

SCB-431 Added Rat Check to TravisCI

---

samples/jaxrs-sample/README.md
samples/jaxrs-sample/jaxrs-consumer/pom.xml
samples/jaxrs-sample/jaxrs-consumer/src/main/java/org/apache/servicecomb/samples/jaxrs/consumer/JaxrsConsumerMain.java
samples/jaxrs-sample/jaxrs-provider/pom.xml
samples/jaxrs-sample/jaxrs-provider/src/main/java/org/apache/servicecomb/samples/jaxrs/provider/JaxrsHelloImpl.java

---
fix jaxrs-provider sample dependency

[SCB-434] fix jaxrs-provider sample dependency

---

foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrap.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrapConfig.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsInitializer.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/PolledEvent.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/TestMetricsBootstrap.java
foundations/foundation-test-scaffolding/pom.xml
foundations/foundation-test-scaffolding/src/main/java/com/netflix/spectator/api/SpectatorUtils.java
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE
metrics/metrics-core/pom.xml
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/DefaultMetricsInitializer.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/MetricsBootListener.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/ConsumerMeters.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/ProducerMeters.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/AbstractInvocationMeter.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/AbstractInvocationMeters.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/ConsumerInvocationMeter.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/ConsumerInvocationMeters.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/MeterInvocationConst.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/ProducerInvocationMeter.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/meter/invocation/ProducerInvocationMeters.java
metrics/metrics-core/src/main/resources/META-INF/services/org.apache.servicecomb.foundation.metrics.MetricsInitializer
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestDefaultMetricsInitializer.java

[SCB-383] Metrics subscribe invocation life event and statistics

---

handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConsumerQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java

---
see details in [https://issues.apache.org/jira/browse/SCB-443](https://issues.apache.org/jira/browse/SCB-443   "Apache Jira Issue")
- Fix randomly UT failure of TestProviderQpsFlowControlHandler
- Change the check method of some unit tests

[SCB-443] fix randomly UT failure of TestProviderQpsFlowControlHandler

---

metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestAnMonitorManager.java

---
rename test case for adjust run sequence in order to fix UT failed.

[SCB-455] rename test case for adjust run sequence in order to fix UT failed

---

integration-tests/springmvc-tests/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequestFactory.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncRequestCallback.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncRestTemplate.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequestFactoryTest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequestTest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncRequestCallbackTest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncRestTemplateTest.java
samples/springmvc-sample/springmvc-consumer/src/main/java/org/apache/servicecomb/samples/springmvc/consumer/SpringmvcConsumerMain.java

[SCB-379] support AsyncRestTemplate

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestSimpleBodyHandler.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestVertxTLSBuilder.java
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-459]Update netty's version to 4.1.19 and vertx's version to 3.5.1

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-478]revert netty's version to 4.1.17 and vertx's version to 3.5.0

---

demo/demo-pojo/pojo-client/src/main/resources/microservice.yaml
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ConsumerQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java
handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/QpsControllerManagerTest.java
handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestConsumerQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java

[SCB-481]Fix qps handler compatible issues due to assumption to schema ids not contains dot

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrapConfig.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/BizkeeperCommand.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/BizkeeperHandlerDelegate.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/FallbackPolicyManager.java
handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/TestFallbackPolicyManager.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/DefaultRetryExtensionsFactory.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalancer.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestExtensionsManager.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/DefaultLogPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestDefaultLogPublisher.java

[SCB-488]Retry/Metrics some default behavior cause unnecessary retry and logs

---

common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestJavassistUtils.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/utils/ProtobufSchemaUtils.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/PathVarParamWriter.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpServerFilter.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpServerFilterBeforeSendResponseExecutor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/ServerRestArgsFilter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/HttpServerFilterBaseForTest.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/TestHttpServerFilter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/TestHttpServerFilterBeforeSendResponseExecutor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/filter/inner/TestServerRestArgsFilter.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/AbstractHttpServletResponse.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/HttpServletResponseEx.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/StandardHttpServletResponseEx.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/InputStreamToReadStream.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestAbstractHttpServletResponse.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestStandardHttpServletResponseEx.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerResponseToHttpServletResponse.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/DefaultRegistryInitializer.java

springmvc over rest vertx server support file download.

[SCB-483] Springmvc rest vertx file download

---

demo/demo-spring-boot-discovery/demo-spring-boot-discovery-server/src/main/resources/microservice.yaml
demo/demo-spring-boot-discovery/demo-spring-boot-zuul-proxy/src/test/java/org/apache/servicecomb/demo/discovery/zuul/DiscoveryZuulProxyIT.java
samples/bmi/webapp/pom.xml
spring-boot-starter/spring-boot-starter-discovery/pom.xml
spring-boot-starter/spring-boot-starter-discovery/src/main/java/org/apache/servicecomb/springboot/starter/discovery/CseRibbonEndpointDiscoveryFilter.java
spring-boot-starter/spring-boot-starter-discovery/src/main/java/org/apache/servicecomb/springboot/starter/discovery/ServiceCombServerList.java
spring-boot-starter/spring-boot-starter-discovery/src/test/java/org/apache/servicecomb/springboot/starter/discovery/TestServiceCombServerList.java

---
Add rest filter for spring-cloud-zuul module in order to screen highway endpoints.
only XML and Faceted project problem warnings

[SCB-474] add endpoint filter (only rest endpoints) for zuul integration

---

demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/part/AbstractPart.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/part/FilePart.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/part/FilePartForSend.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/part/TestFilePart.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerResponseToHttpServletResponse.java

[SCB-494] Delete temp file after download

---

foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrap.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/PolledEvent.java
foundations/foundation-metrics/src/test/java/org/apache/servicecomb/foundation/metrics/TestMetricsBootstrap.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestDefaultLogPublisher.java

[SCB-507] avoid rest publisher get NaN values when there is no period publisher

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-509] Update jackson's version to 2.9.5

---

archetypes/business-service-springmvc/README.md
archetypes/business-service-springmvc/pom.xml
archetypes/business-service-springmvc/src/main/java/org/apache/servicecomb/archetypes/Application.java
archetypes/business-service-springmvc/src/main/java/org/apache/servicecomb/archetypes/HelloConsumer.java
archetypes/business-service-springmvc/src/main/java/org/apache/servicecomb/archetypes/HelloEndpoint.java
archetypes/business-service-springmvc/src/main/resources/META-INF/spring/provider.bean.xml
archetypes/business-service-springmvc/src/main/resources/microservice.yaml

---
add springmvc provider archetype
it's a part of https://issues.apache.org/jira/browse/SCB-439
---
Eclipse warnings check

[SCB-442] add springmvc archetype

---

demo/demo-schema/src/main/java/org/apache/servicecomb/demo/TestMgr.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/DownloadSchemaIntf.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDownload.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DownloadSchema.java
demo/pom.xml
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/http/HttpUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/http/TestHttpUtils.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/ReadStreamPart.java
foundations/foundation-vertx/src/test/java/io/vertx/core/file/impl/AsyncFileUitls.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestReadStreamPart.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/registry/TestServiceRegistryFactory.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-487] SDK consumer download file

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/NetUtils.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java
service-registry/src/test/resources/microservice.yaml

---
for http/https, the default ports are 80 and 443. if port is not configured, the default port needs to be used. this simplifies the configuration.

[SCB-518] ServiceCenter ip address need to config default port

---

archetypes/README.md
archetypes/business-service-spring-boot-starter/README.md
archetypes/business-service-spring-boot-starter/pom.xml
archetypes/business-service-spring-boot-starter/src/main/java/org/apache/servicecomb/archetypes/Application.java
archetypes/business-service-spring-boot-starter/src/main/java/org/apache/servicecomb/archetypes/HelloConsumer.java
archetypes/business-service-spring-boot-starter/src/main/java/org/apache/servicecomb/archetypes/HelloEndpoint.java
archetypes/business-service-spring-boot-starter/src/main/resources/microservice.yaml

---
add spring boot starter provider archetype
it's a part of https://issues.apache.org/jira/browse/SCB-439

[SCB-470] add spring boot starter provider archetype

---

archetypes/business-service-pojo/README.md
archetypes/business-service-pojo/pom.xml
archetypes/business-service-pojo/src/main/java/org/apache/servicecomb/archetypes/Application.java
archetypes/business-service-pojo/src/main/java/org/apache/servicecomb/archetypes/Hello.java
archetypes/business-service-pojo/src/main/java/org/apache/servicecomb/archetypes/HelloConsumer.java
archetypes/business-service-pojo/src/main/java/org/apache/servicecomb/archetypes/HelloEndpoint.java
archetypes/business-service-pojo/src/main/resources/META-INF/spring/provider.bean.xml
archetypes/business-service-pojo/src/main/resources/microservice.yaml

---
add pojo provider archetype
it's a part of https://issues.apache.org/jira/browse/SCB-439

[SCB-440] Provide Maven Archetype of business-service-pojo

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-542] Update netty's version to 4.1.24

---

demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/Consumer.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestLastPropertyPlaceholderConfigurer.java
integration-tests/spring-zuul-tracing-tests/src/test/java/org/apache/servicecomb/spring/cloud/zuul/tracing/SpringCloudZuulTracingTest.java
integration-tests/springmvc-tests/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE
parent/pom.xml
samples/bmi/build.gradle
samples/bmi/pom.xml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
spring-boot-starter/spring-boot-starter-discovery/src/main/java/org/apache/servicecomb/springboot/starter/discovery/CseDiscoveryClient.java
spring-boot-starter/spring-boot-starter-discovery/src/main/java/org/apache/servicecomb/springboot/starter/discovery/CseDiscoveryClientConfiguration.java
spring-boot-starter/spring-boot-starter-discovery/src/test/java/org/apache/servicecomb/springboot/starter/discovery/TestCseDiscoveryClient.java

---
Spring Boot and Spring Version match
| Spring Boot Version      | Spring Version         |
| :---------- | :---------- |
| 1.5.8.RELEASE | 4.3.12.RELEASE |
| 1.5.9.RELEASE | 4.3.13.RELEASE |
| 1.5.10.RELEASE | 4.3.14.RELEASE |
| 1.5.11.RELEASE | 4.3.15.RELEASE |
| 1.5.12.RELEASE | 4.3.16.RELEASE |
If Consumer use RestTemplate make a invocation and Producer return 590 Cse Internal Server Error like ：
`ensureServerBlowsUp` in https://github.com/apache/incubator-servicecomb-java-chassis/blob/master/integration-tests/springmvc-tests/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
* 4.3.12.RELEASE still throw …

[SCB-504] upgrade spring boot version

---

java-chassis-dependencies/pom.xml

[SCB-567] treat warning as errors, modify the compilerArgments

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/FrameworkVersions.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/response/GetSchemaResponse.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/response/GetSchemasResponse.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/ServiceRegistryClient.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestServiceCenterInfo.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImplTest.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/task/TestMicroserviceRegisterTask.java

use the servicecenter new schemas interface to refactor the schema registry logic.
1、use schema summary to compare the schema local with remote
2、dev enviroment will reregistry the shcema, prod enviroment will throw a RuntimeException
---

[SCB-546] refactor the schemas registry logic

---

demo/demo-pojo/pojo-server/src/main/resources/microservice.yaml
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/URIEndpointObject.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/net/TestURIEndpointObject.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestRestTransportClient.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java

[SCB-482] Http2 support for java-chassis

---

common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/ClassConfig.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtType.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/FieldConfig.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/JavassistUtils.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/MethodConfig.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/ParameterConfig.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/StdScopedClassPool.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/StdScopedClassPoolFactory.java
common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestCtType.java
common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestJavassistUtils.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/OperationProtobuf.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/utils/ProtobufSchemaUtils.java
common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/utils/TestProtobufSchemaUtils.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/converter/ConverterMgr.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/unittest/UnitTestSwaggerUtils.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/converter/TestConverterMgr.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/converter/model/TestModelImplConverter.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/TestArrayType.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/TestSwaggerUtils.java
swagger/swagger-generator/generator-jaxrs/src/test/java/org/apache/servicecomb/swagger/generator/jaxrs/TestJaxrs.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/TestSpringmvc.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/engine/SwaggerEnvironmentForTest.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/engine/TestSwaggerEnvironment.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/arguments/TestPojoConsumerEqualProducer.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/arguments/TestPojoConsumerEqualSwagger.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/models/JaxrsImpl.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/models/PojoConsumerIntf.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/models/PojoImpl.java

still preparing for create recursive class

[SCB-533] JavassistUtils create class from CtClass

---

common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtType.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtTypeJavaType.java
common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/JavassistUtils.java
common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestCtType.java
common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestCtTypeJavaType.java
demo/demo-edge/business-2.0.0/src/main/java/org/apache/servicecomb/demo/edge/business/Impl.java
demo/demo-edge/consumer/src/main/java/org/apache/servicecomb/demo/edge/consumer/Consumer.java
demo/demo-edge/model/src/main/java/org/apache/servicecomb/demo/edge/model/DependTypeA.java
demo/demo-edge/model/src/main/java/org/apache/servicecomb/demo/edge/model/DependTypeB.java
demo/demo-edge/model/src/main/java/org/apache/servicecomb/demo/edge/model/RecursiveSelfType.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/converter/AbstractConverter.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/converter/SwaggerToClassGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/converter/model/ModelImplConverter.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/converter/property/ArrayPropertyConverter.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/converter/model/TestModelImplConverter.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/TestSwaggerToClassGenerator_base.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/TestSwaggerToClassGenerator_create.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/TestSwaggerToClassGenerator_reuse.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/ToClassSchema.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/model/DependTypeA.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/model/DependTypeB.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/model/Generic.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/converter/swaggerToClassGenerator/model/RecursiveSelfType.java

support create recursive dependency class
```
1. class A {
A a;
}
2. class A {
B b;
}
class B {
A a;
}
```

[SCB-532] Support recursive dependency

---

README.md

[SCB-585]update README.md

---

archetypes/business-service-jaxrs/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-pojo/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-springmvc/src/main/resources/archetype-resources/pom.xml

[SCB-588] Set archetypes sourceEncoding to UTF-8

---

integration-tests/spring-zuul-tracing-tests/src/test/java/org/apache/servicecomb/spring/cloud/zuul/tracing/SpringCloudZuulTracingTest.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestBodyHandler.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestDispatcher.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestVertxRestDispatcher.java

---
see details in [SCB-580](https://issues.apache.org/jira/browse/SCB-580)

[SCB-580] fix response of the upload file too large

---

common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtTypeJavaType.java
core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
integration-tests/spring-zuul-tracing-tests/src/test/java/org/apache/servicecomb/spring/cloud/zuul/tracing/SpringCloudZuulTracingTest.java

---
See details in [SCB-593](https://issues.apache.org/jira/browse/SCB-593)

[SCB-593] change log level of InvokerUtils.innerSyncInvoke()

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestRestClientRequestImpl.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/consumer/ConsumerArgumentSame.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/arguments/consumer/ConsumerArgumentSameTest.java

---
See details in [SCB-579](https://issues.apache.org/jira/browse/SCB-579)

[SCB-579] fix NullPointerException when consumer upload null file

---

demo/demo-pojo/pojo-client/src/main/resources/microservice.yaml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/MicroserviceInstance.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/consumer/MicroserviceInstancePing.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/consumer/MicroserviceVersions.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/consumer/SimpleMicroserviceInstancePing.java
service-registry/src/main/resources/META-INF/services/org.apache.servicecomb.serviceregistry.consumer.MicroserviceInstancePing
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/api/registry/TestMicroServiceInstance.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImplTest.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestMicroserviceVersions.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/TestSimpleMicroserviceInstancePing.java
spring-boot-starter/spring-boot-starter-transport/src/test/java/org/apache/servicecomb/springboot/starter/transport/TestRestServletInitializer.java

[SCB-582]Provide a way to protect instance removal

---

archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/pom.xml

[SCB-597] update sprign boot version in business-service-spring-boot-starter

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-590] Update the validator version

---

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-601]ServiceComb integrated to spring boot or tomcat will print too many logs

---

handlers/handler-fault-injection/src/main/java/org/apache/servicecomb/faultinjection/FaultInjectionUtil.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsControllerManager.java

[SCB-575] Fix doc comments for generating java doc

---

foundations/foundation-vertx/pom.xml

Just create the PR to verify the build.

SCB-381 Reverted the fork per test setting

---

demo/demo-edge/edge-service/src/main/resources/config/log4j.properties
demo/demo-edge/edge-service/src/main/resources/microservice.yaml
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/DefaultEdgeDispatcher.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedEdgeDispatcher.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/Utils.java
edge/edge-core/src/main/resources/META-INF/services/org.apache.servicecomb.transport.rest.vertx.VertxHttpDispatcher
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestDefaultEdgeDispatcher.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestURLMappedEdgeDispatcher.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestUtils.java

[SCB-611]Provide URLMappedEdgeDispatcher to using edge service easier

---

README.md

[SCB-475] Add section for dowloading latest release in README

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java

[SCB-601] print more specific logs when there are too many schema in environment

---

core/src/main/java/org/apache/servicecomb/core/definition/SchemaMeta.java

---
do not init operations if there are no path (empty interface) in swagger(prevent NPE)

[SCB-562] fix NPE when had empty interface (not have any method)

---

core/src/main/java/org/apache/servicecomb/core/definition/SchemaMeta.java
core/src/main/java/org/apache/servicecomb/core/definition/SchemaUtils.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/SwaggerUtils.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/TestSwaggerUtils.java
swagger/swagger-generator/generator-core/src/test/resources/swagger1.yaml
swagger/swagger-generator/generator-core/src/test/resources/swagger2.yaml

[SCB-601] when java.lang.Error: not support def type: class io.swagger.models.ComposedMode we don't know which swagger

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java

[SCB-471]watch mode: netty upgrade have add pong response and need to handle it

---

java-chassis-distribution/src/release/LICENSE
java-chassis-distribution/src/release/licenses/LICENSE-javax-el
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/parser/CompositeVertxRestAccessLogItemMeta.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/parser/impl/VertxRestAccessLogPatternParser.java

Update LICENSE for release 1.0.0-m2, re-ordered the libraries in alphabetical order ignoring case.
Also fixed some minor issues in javadoc.
---

[SCB-647] Update LICENSE for release 1.0.0-m2

---

core/src/main/java/org/apache/servicecomb/core/definition/schema/ProducerSchemaFactory.java

[SCB-646] if local swagger exists, not generate swagger according to class

---

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestTransport.java

[SCB-649] when port can't been listened,log warn and show more detail message

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java
demo/demo-jaxrs/jaxrs-client/src/main/resources/microservice.yaml
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/RequestClientTimeOut.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java

[SCB-653]Transfer-Encoding and Content-Length can not be set to response

---

edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/AbstractEdgeDispatcher.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestAbstractEdgeDispatcher.java

[SCB-656]edge service should return back the providers error code

---

integration-tests/springmvc-tests/springmvc-tests-common/pom.xml

---
springmvc-tests-common not marked as a test-jar

[SCB-659] fix springmvc integration test failed

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
core/src/main/java/org/apache/servicecomb/core/invocation/InvocationFactory.java
core/src/main/java/org/apache/servicecomb/core/unittest/UnitTestMeta.java
core/src/test/java/org/apache/servicecomb/core/TestInvocationFactory.java
core/src/test/java/org/apache/servicecomb/core/TestSCBEngine.java
core/src/test/java/org/apache/servicecomb/core/provider/consumer/TestInvokerUtils.java
providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestCseClientHttpRequest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequestTest.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerInvoke.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayServerInvoke.java

[SCB-667] fix gracefully shutdown is not work in some case

---

common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtTypeJavaType.java
common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestCtTypeJavaType.java

---
Add extra hashcode into CtTypeJavaType to fix list type response body deserialization problem.
See details in [SCB-669](https://issues.apache.org/jira/browse/SCB-669)

[SCB-669] add extra hashcode into CtTypeJavaType to avoid deserialization problem

---

core/src/main/java/org/apache/servicecomb/core/definition/schema/ConsumerSchemaFactory.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/BizkeeperCommand.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/provider/RSAProviderTokenManager.java

[SCB-661]logs give more information and remove unnecessary log for each invocation

---

handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsController.java

Added the logic for the first cycle of qps controller so that the number of requests allowed per second equals to its limit value.
---

[SCB-651] Fixes bug of qps rate limit value

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/FormProcessorCreator.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/DefaultValues.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/OperationGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/parameter/AbstractParameterProcessor.java

[SCB-697] Service comb chassis must support JAX-RS @DefaultValue

---

foundations/foundation-config/pom.xml

[SCB-702] Deleted unwanted json-lib maven dependency for foundation-config

---

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/AccessLogParam.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/LocalHostItem.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/impl/AccessLogHandler.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/LocalHostItemTest.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/impl/AccessLogHandlerTest.java

---
See details in [SCB-696](https://issues.apache.org/jira/browse/SCB-696)

[SCB-696] access log print %v correctly in short-lived connections

---

common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/CtType.java
common/common-javassist/src/test/java/org/apache/servicecomb/common/javassist/TestCtType.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstSpringmvcIntf.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestResponse.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestRestTemplate.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/converter/ConverterMgr.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/converter/ConverterMgrTest.java

---
See details in [SCB-703](https://issues.apache.org/jira/browse/SCB-703)

[SCB-703] Fix deserialization problem in invoking void operation in RPC style

---

common/common-javassist/src/main/java/org/apache/servicecomb/common/javassist/JavassistUtils.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/ProtobufManager.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/utils/ScopedProtobufSchemaManager.java
core/src/main/java/org/apache/servicecomb/core/definition/MicroserviceMeta.java
core/src/main/java/org/apache/servicecomb/core/definition/classloader/DefaultMicroserviceClassLoaderFactory.java
core/src/main/java/org/apache/servicecomb/core/definition/classloader/MicroserviceClassLoader.java
core/src/main/java/org/apache/servicecomb/core/definition/schema/AbstractSchemaFactory.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClient.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/JvmUtils.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigMapping.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/archaius/sources/AbstractConfigLoader.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/RuleClassNameExtentionsFactory.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/SwaggerGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/utils/ClassUtils.java

[SCB-715]working in thread that do not have context class loader

---

core/src/main/java/org/apache/servicecomb/core/definition/loader/SchemaLoader.java
core/src/main/java/org/apache/servicecomb/core/unittest/UnitTestMeta.java
core/src/main/resources/microservice.yaml
core/src/test/java/org/apache/servicecomb/core/definition/schema/TestProducerSchemaFactory.java
demo/demo-multiple/multiple-client/src/main/resources/microservice.yaml
demo/demo-multiple/multiple-server/src/main/resources/microservice.yaml
demo/demo-schema/src/main/resources/microservice.yaml
demo/demo-server-servlet/src/main/resources/microservice.yaml
demo/demo-spring-boot-provider/demo-spring-boot-jaxrs-client/src/main/resources/microservice.yaml
demo/demo-spring-boot-provider/demo-spring-boot-jaxrs-server/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/ConsumerTestsAfterBootup.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
foundations/foundation-config/src/test/resources/test1.yaml
foundations/foundation-config/src/test/resources/test2.yaml
integration-tests/pojo-test/src/test/java/org/apache/servicecomb/demo/pojo/test/PojoIntegrationTestBase.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java

[SCB-712]Do not register service path to service center when not necessary

---

demo/demo-springmvc/springmvc-client/pom.xml
demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigUtil.java

[SCB-671]Duplicate cse.xxx to servicecomb.xxx forget dynamic config

---

core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/test/java/org/apache/servicecomb/core/TestInvocation.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/unittest/LocalProducerInvoker.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/SwaggerInvocation.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/context/InvocationContext.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/TestSwaggerInvocation.java

this makes developers easier to save data to invocation, and used them in HttpServerFilter.beforeSendResponse

[SCB-733] open handlerContext for business logic, and add a new name:localContext

---

service-registry/pom.xml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/task/TestMicroserviceRegisterTask.java

[SCB-727] Local generated schema and service center schema are different then print the diff content to the user

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/CodeFirstRestTemplateJaxrs.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java
demo/demo-jaxrs/jaxrs-server/src/main/resources/microservice.yaml

[SCB-747] add jaxrs upload file demo

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/Log4jUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/Log4jUtilsTest.java

---
See details in [SCB-752](https://issues.apache.org/jira/browse/SCB-752)

[SCB-752] provide a configuration to determine whether to output merged.log4j.properties

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/TestRegistry.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/LocalServiceRegistryClientImplTest.java

[SCB-753]NPE when query not exists service

---

archetypes/README.md
samples/bmi/build.gradle
samples/bmi/calculator/build.gradle
samples/bmi/webapp/build.gradle
samples/codefirst-sample/build.gradle
samples/codefirst-sample/codefirst-consumer/build.gradle
samples/codefirst-sample/codefirst-provider/build.gradle
samples/trust-sample/customer/pom.xml
samples/trust-sample/hacker/pom.xml
samples/trust-sample/pom.xml
samples/trust-sample/store/pom.xml

---
See details in [SCB-759](https://issues.apache.org/jira/browse/SCB-759)

[SCB-759] fix ServiceComb version

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java

[SCB-755] 755 Duplicate copy cse config to Servicecomb config

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/UrlWithProviderPrefixClientHttpRequestFactory.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestUrlWithProviderPrefixClientHttpRequestFactory.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/TestInstanceCacheChecker.java

[SCB-760]provide a way to invoke service with full path

---

service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestAbstractClientPool.java

The AddressResolverOptions just uses the vertx defaults. The conigSource
is set to null when creating. So there is no need to test these options.
---

[SCB-666] Remove assert for AddressResolverOptions

---

demo/demo-springmvc/springmvc-client/pom.xml
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstSpringmvcIntf.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestResponse.java
demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-client/src/test/java/org/apache/servicecomb/demo/springmvc/SpringMvcIT.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
handlers/handler-fault-injection/src/main/java/org/apache/servicecomb/faultinjection/AbortFault.java
handlers/handler-fault-injection/src/main/java/org/apache/servicecomb/faultinjection/DelayFault.java
handlers/handler-fault-injection/src/main/java/org/apache/servicecomb/faultinjection/Fault.java
handlers/handler-fault-injection/src/test/java/org/apache/servicecomb/faultinjection/AbortFaultTest.java
handlers/handler-fault-injection/src/test/java/org/apache/servicecomb/faultinjection/DelayFaultTest.java
handlers/handler-fault-injection/src/test/java/org/apache/servicecomb/faultinjection/TestFaultInjectHandler.java

---
See details in [SCB-769](https://issues.apache.org/jira/browse/SCB-769)

[SCB-769] Fix delay fault injection blocking thread

---

core/src/main/java/org/apache/servicecomb/core/definition/schema/ProducerSchemaFactory.java
core/src/test/java/org/apache/servicecomb/core/definition/schema/TestProducerSchemaFactory.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/Const.java

[SCB-778]add container path to base path

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/AbstractRestObjectMapper.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapper.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapperFactory.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/CookieProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/ParamValueProcessor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/QueryVarParamWriter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/PojoModel.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/TestRestOperationMeta.java
demo/demo-edge/edge-service/src/main/java/org/apache/servicecomb/demo/edge/service/encrypt/filter/DecodeBodyFilter.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/MultiErrorCodeServiceClient.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/CodeFirstJaxrs.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/ComputeImpl.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/multiErrorCode/MultiErrorCodeService.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/RestObjectMapperWithStringMapper.java
demo/demo-spring-boot-provider/demo-spring-boot-jaxrs-client/src/main/java/org/apache/servicecomb/springboot/jaxrs/client/JaxrsClient.java
demo/demo-spring-boot-provider/demo-spring-boot-jaxrs-server/src/main/java/org/apache/servicecomb/springboot/jaxrs/server/JaxrsServer.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
integration-tests/jaxrs-tests/src/test/java/org/apache/servicecomb/demo/jaxrs/tests/JaxrsIntegrationTestBase.java
integration-tests/jaxrs-tests/src/test/java/org/apache/servicecomb/demo/jaxrs/tests/endpoints/SomeAbstractJaxrsRestEndpoint.java
integration-tests/springmvc-tests/springmvc-tests-common/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
integration-tests/springmvc-tests/springmvc-tests-common/src/test/java/org/apache/servicecomb/demo/springmvc/tests/endpoints/CodeFirstSpringmvcBase.java

[SCB-775]support invoke service using raw type like JsonObject & String

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/SessionStickinessRule.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestSessionSticknessRule.java

[SCB-780] sessionstickrule add the judgement of whether lastServer can be accessed.

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java

[SCB]in small & simple situations, unavailable server not cleaned

---

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestDefaultHttpClientFilter.java

[SCB-794]Edge invocation do not properly send servlet filter response code

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-795] update jackson from 2.9.5 to 2.9.6

---

core/src/main/java/org/apache/servicecomb/core/Const.java
core/src/main/java/org/apache/servicecomb/core/Transport.java
core/src/main/java/org/apache/servicecomb/core/transport/AbstractTransport.java
core/src/test/java/org/apache/servicecomb/core/TestTransport.java
coverage-reports/pom.xml
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/ClientEvent.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/ConnectionEvent.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/EventType.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/ServerType.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/TransportType.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpServer.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpServerConnection.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypePojo.java
integration-tests/spring-pojo-tests/src/test/java/org/apache/servicecomb/demo/pojo/test/ConnectionEventWatcher.java
integration-tests/springmvc-tests/springmvc-tests-common/src/test/java/org/apache/servicecomb/demo/springmvc/tests/ConnectionEventWatcher.java
integration-tests/springmvc-tests/springmvc-tests-connection-limit/pom.xml
integration-tests/springmvc-tests/springmvc-tests-connection-limit/src/test/java/org/apache/servicecomb/demo/springmvc/tests/RawSpringMvcIntegrationTest.java
integration-tests/springmvc-tests/springmvc-tests-connection-limit/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcTestMain.java
integration-tests/springmvc-tests/springmvc-tests-connection-limit/src/test/resources/microservice.yaml
integration-tests/springmvc-tests/springmvc-tests-simplified-mapping/src/test/java/org/apache/servicecomb/demo/springmvc/tests/RawSpringMvcSimplifiedMappingAnnotationIntegrationTest.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClientConnection.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayServerVerticle.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayTransport.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayClient.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestTransport.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java

---
Add `servicecomb.rest.server.connection-limit` for setting this limit
Default value is Integer.MAX_VALUE
https://github.com/eclipse/vert.x/issues/2542

[SCB-688] vertx rest server not accept too many connection

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java

[SCB-801] Delete useless demo

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/beanParam/BeanParamPojoClient.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/beanParam/BeanParamTestServiceIntf.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/beanParam/TestBeanParameter.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/beanParam/TestBeanParameterWithUpload.java
swagger/swagger-generator/generator-jaxrs/src/main/java/org/apache/servicecomb/swagger/generator/jaxrs/processor/annotation/BeanParamAnnotationProcessor.java
swagger/swagger-generator/generator-jaxrs/src/test/java/org/apache/servicecomb/swagger/generator/jaxrs/processor/annotation/BeanParamAnnotationProcessorTest.java

---
See details in [SCB-800](https://issues.apache.org/jira/browse/SCB-800)

[SCB-800] params in BeanParam is generated by declared field order

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java

[SCB-787]fix ping time gap bug and add configuration to time interval

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/JaxRSDefaultValues.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/SpringMvcDefaultValues.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/OperationGenerator.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/CookieValueAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/PathVariableAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestAttributeAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestParamAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestPartAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/test/resources/schemas/mixupAnnotations.yaml

[SCB-736] generate default value to swagger for primitive type when there is no defaultValue annotation

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java

[SCB-832] modify the errorThresholdPercentage from 20 to 0

---

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
core/src/test/java/org/apache/servicecomb/core/TestSCBEngine.java
core/src/test/java/org/apache/servicecomb/core/provider/consumer/TestInvokerUtils.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/DefaultRetryExtensionsFactory.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestExtensionsManager.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerEnvironment.java

[SCB-833]Provide a retry mechanism to meet upgrade no interrupt

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstSpringmvcIntf.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestResponse.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/decoderesponse/DecodeTestResponse.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/decoderesponse/DecodeTestResponse.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestDefaultHttpClientFilter.java

---
See details in [SCB-827](https://issues.apache.org/jira/browse/SCB-827)

[SCB-827] Add response body decoding error log

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/DefaultRetryExtensionsFactory.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestExtensionsManager.java

---
There are many kinds of exception that are subclass of `java.lang.IOException`, some of them should not trigger retry mechanism. So we remove `java.lang.IOException`

[SCB-833] IOException do not trigger retry mechanism

---

foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/ReadStreamPart.java

it's a small probability bug, not so easy to reproduce during UT or IT.

[SCB-845] bug fix: some times download file can not get correct content

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ParseConfigUtils.java

[SCB-846] ConfigCenterClient log much in the pull mode

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/MultiErrorCodeServiceClient.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/multiErrorCode/MultiErrorCodeService.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/multiErrorCode/NoClientErrorCode200.java
demo/demo-jaxrs/jaxrs-server/src/main/java/org/apache/servicecomb/demo/jaxrs/server/multiErrorCode/NoClientErrorCode400.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/ResponsesMeta.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/response/TestResponsesMeta.java

[SCB-847][revert]make response default and compatible to old behavior

---

handlers/handler-tracing-zipkin/pom.xml
java-chassis-distribution/src/release/LICENSE

parent class brave.http.HttpClientAdapter<Req, Resp> of ConsumerInvocationAdapter and ProviderInvocationAdapter, depend both zipkin1 and zipkin2

[SCB-810] fix compile error for eclipse "Photon Release (4.8.0)"

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestResponse.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/CodeFirstSpringmvc.java
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/response/ResponsesMeta.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestDefaultHttpClientFilter.java

[SCB-861]490,590 response not properly used

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java

[SCB-884] Already return, no need else

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/QueryProcessorCreator.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestQueryProcessorCreator.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerProducerOperation.java

[SCB-880]Give an option to query parameter convert empty to null

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/PathProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/PathVarParamWriter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestPathProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/path/PathVarParamWriterTest.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/http/TestHttpUtils.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/base/TestParamCodec.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ParamCodecSchema.java

---
See details in [SCB-886](https://issues.apache.org/jira/browse/SCB-886)

[SCB-886] Fix path param encode decode problem

---

handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/HystrixCommandPropertiesExt.java

[SCB-898] Governance function is not effective when configuration Start with servicecomb

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/MultiErrorCodeServiceClient.java
demo/demo-schema/pom.xml
demo/demo-spring-boot-discovery/demo-spring-boot-discovery-server/pom.xml
demo/demo-springmvc/springmvc-client/pom.xml
demo/demo-springmvc/springmvc-server/pom.xml
integration-tests/pom.xml

[SCB-895]When json parse fail will not get 400 but 590

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/base/TestParamCodecEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/base/TestRestServerConfig.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestServerConfigSchema.java
integration-tests/it-producer/src/main/resources/microservice.yaml
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/TransportConfig.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestTransportConfig.java

---
See details in [SCB-897](https://issues.apache.org/jira/browse/SCB-897)

[SCB-897] Support max initial line length config

---

demo/demo-springmvc/springmvc-client/pom.xml
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestBizkeeper.java
demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/BizkeeperTest.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
demo/pom.xml

[SCB-897] add bizkeepertestdemo

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/QueryProcessorCreator.java
core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/main/java/org/apache/servicecomb/core/definition/OperationMeta.java
integration-tests/it-common/src/main/resources/microservice.yaml
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultJsonValueJaxrsSchema.java
integration-tests/it-edge/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultJsonValueJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultJsonValueRequest.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultJsonValueResponse.java

[SCB-903]Add a feature to serialize/deserialize using Object to avoid information lose

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/ExceptionUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/TestExceptionUtils.java
handlers/handler-bizkeeper/src/main/java/org/apache/servicecomb/bizkeeper/BizkeeperHandler.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/exception/ExceptionToResponseConverters.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/exception/TestExceptionToResponseConverters.java

[SCB-911]Timeout scenario print too many logs

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/SPIOrder.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/GateRestTemplate.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodecEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestServerConfig.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestServerConfigEdge.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestServerConfigSchema.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/GlobalRestFailureHandler.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/TestRestServerVerticle.java

---
See details in [SCB-905](https://issues.apache.org/jira/browse/SCB-905)

[SCB-905] Add global rest failure handler

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestAnnotatedAttribute.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/AnnotatedAttributeSpringmvcSchema.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/CookieValueAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/PathVariableAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestAttributeAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestHeaderAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestParamAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestPartAnnotationProcessor.java
transports/transport-rest/transport-rest-servlet/src/main/java/org/apache/servicecomb/transport/rest/servlet/RestAsyncListener.java
transports/transport-rest/transport-rest-servlet/src/test/java/org/apache/servicecomb/transport/rest/servlet/TestRestAsyncListener.java

[SCB-904] SpringMVC annotation do not support value,only support name

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestServerConfigEdge.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java

[SCB-905] GlobalRestFailureHandler handle InvocationException properly

---

integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/CommonModel.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/ApiParamJaxrsSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/ApiParamPojoSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/ApiParamSpringmvcSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestApiParam.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/OperationGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/AnnotationUtils.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/pojo/extend/parameter/PendingBodyParameter.java

just only process parameter  level, it's enough now.

 [SCB-215] Process @ApiParam

---

coverage-reports/pom.xml
foundations/foundation-protobuf/pom.xml
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/parser/ContentFileReader.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/parser/ProtoParser.java
foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/internal/parser/TestProtoParser.java
foundations/foundation-protobuf/src/test/resources/protobufRoot.proto
foundations/pom.xml
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

add protoStuff-parser dependency
upgrade guava/guice version

[SCB-917] parse proto file to model

---

demo/demo-crossapp/crossapp-client/src/main/java/org/apache/servicecomb/demo/crossapp/CrossappClient.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxTLSBuilder.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/server/TcpServer.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestServerConfigEdge.java
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
transports/transport-rest/transport-rest-client/src/test/java/io/vertx/core/http/impl/VertxImplTestUtils.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java

[SCB-931]upgrade vert.x to 3.5.3 to fix some know issues

---

handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsController.java

[SCB-932]Time jump cause the new request injected
---

[SCB-932]Time jump cause the new request injected

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapper.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ControllerImpl.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/RequestBaseModel.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/RequestModel.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/ResponseBaseModel.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/ResponseModel.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultJsonValueJaxrsSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRequestBodySpringMvcSchema.java
integration-tests/it-edge/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RequestBodySpringMvcSchema.java

[SCB-933]Revert changes to RestObjectMapper that fail on primitive types not present

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDataTypePrimitive.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultValue.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypePojoSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeSpringmvcSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultValueJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultValueSpringmvcSchema.java

[SCB-939] move double type test case from demo to integration-test

---

core/src/main/resources/META-INF/spring/cse.bean.xml
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/LambdaMetafactoryUtils.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/bean/MapGetter.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/bean/MapSetter.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/bean/Setter.java
foundations/foundation-protobuf/pom.xml
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/bean/BeanDescriptor.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/bean/BeanDescriptorManager.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/bean/BeanFactory.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/bean/PropertyDescriptor.java
foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/internal/bean/TestBeanDescriptorManager.java
pom.xml

prepare for protobuf codec
not use this feature yet.

[SCB-922] collect Getter/Setter from pojo

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpClientFilter.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpServerFilter.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/HttpServerFilterBeforeSendResponseExecutor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/filter/inner/ServerRestArgsFilter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/thirdparty/Test3rdPartyInvocation.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java

[SCB-943]make ProduceJsonProcessor,DefaultHttpClientFilter,ServerRestArgsFilter changable

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/PathVarParamWriter.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/path/PathVarParamWriterTest.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/http/HttpUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/http/TestHttpUtils.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITSCBRestTemplate.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDataTypePrimitive.java
integration-tests/it-producer-deploy-springboot2-servlet/src/main/java/org/apache/servicecomb/it/SpringBoot2ServletApplication.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/AccessLogConfiguration.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/AccessLogConfigurationTest.java

---
See details in [SCB-936](https://issues.apache.org/jira/browse/SCB-936)

[SCB-936] encode slash in path param

---

providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java
providers/provider-pojo/src/test/java/org/apache/servicecomb/provider/pojo/TestInvoker.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/context/ContextUtils.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/context/InvocationContextCompletableFuture.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/context/TestContextUtils.java

https://issues.apache.org/jira/browse/SCB-960

[SCB-960] get context from future

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java

[SCB-961]provide a way to isolate for at least a moment

---

foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/SSLOption.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/TestVertxTLSBuilder.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/ApiOperationJaxrsSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/ApiOperationSpringMVCSchema.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/schema/TestApiOperation.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/ApiOperationProcessor.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/SwaggerDefinitionProcessor.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/ApiOperationProcessorTest.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/generator/core/processor/annotation/SwaggerDefinitionProcessorTest.java
swagger/swagger-generator/generator-jaxrs/src/main/java/org/apache/servicecomb/swagger/generator/jaxrs/processor/annotation/ConsumesAnnotationProcessor.java
swagger/swagger-generator/generator-jaxrs/src/main/java/org/apache/servicecomb/swagger/generator/jaxrs/processor/annotation/ProducesAnnotationProcessor.java
swagger/swagger-generator/generator-jaxrs/src/test/java/org/apache/servicecomb/swagger/generator/jaxrs/processor/annotation/ConsumesAnnotationProcessorTest.java
swagger/swagger-generator/generator-jaxrs/src/test/java/org/apache/servicecomb/swagger/generator/jaxrs/processor/annotation/ProducesAnnotationProcessorTest.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/AbstractHttpMethodMappingAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/test/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestMappingMethodAnnotationProcessorTest.java

[SCB-964] Fix setting MediaType problem

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/IpPortManager.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/TestIpPortManager.java

[SCB-718]If auto discovery failed, will cause a dead cycle

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/deploy/MicroserviceDeploy.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java

[SCB-718]fix compile errors

---

demo/demo-spring-boot-discovery/demo-spring-boot-zuul-proxy/pom.xml
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/config/impl/XmlLoader.java
java-chassis-dependencies-springboot2/pom.xml
spring-boot2-starter-parent/pom.xml
spring-boot2-starter-parent/spring-boot2-starter-discovery/pom.xml
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/CseDiscoveryClient.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/CseDiscoveryClientConfiguration.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/CseRibbonClientConfiguration.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/CseRibbonConfiguration.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/CseRibbonEndpointDiscoveryFilter.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/ServiceCombServerList.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/java/org/apache/servicecomb/springboot2/starter/discovery/package-info.java
spring-boot2-starter-parent/spring-boot2-starter-discovery/src/main/resources/META-INF/spring.factories

The code is copied from springboot-starter-discovery and test code
is removed. Adjusted the springboot and spring cloud versions for
compatibility issues.
---

[SCB-985] Add spring-boot2-starter-discovery

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITSCBRestTemplate.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestController.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestControllerEmptyMappingSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestControllerSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestControllerWithRequestMappingSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestControllerWithRestSchemaSchema.java
providers/provider-rest-common/src/main/java/org/apache/servicecomb/provider/rest/common/RestProducers.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/SpringmvcSwaggerGeneratorContext.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RestControllerClassAnnotationProcessor.java

[SCB-989]scan RestController to to make springmvc controller publish as ServiceComb Rest easier

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ControllerImpl.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java

[SCB-996]When retries fail, return the last error

---

integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/Generic.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/User.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestGenericEdge.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/base/TestGeneric.java
integration-tests/it-edge/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/GenericSchema.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/utils/ClassUtils.java

[SCB-1007] not support CustomGeneric<Map<String,String>>

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/encrypt/Encryption.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/encrypt/Encryptions.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/encrypt/NoEncryption.java
foundations/foundation-common/src/main/resources/META-INF/services/org.apache.servicecomb.foundation.common.encrypt.Encryption
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/encrypt/TestEncryptions.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/AbstractClientPool.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/HttpClientPool.java

[SCB-1009]Supporting configure encrypted password for proxy settings

---

archetypes/business-service-jaxrs/README.md
archetypes/business-service-jaxrs/src/main/resources/archetype-resources/README.md
archetypes/business-service-jaxrs/src/main/resources/archetype-resources/src/main/resources/microservice.yaml
archetypes/business-service-pojo/README.md
archetypes/business-service-pojo/src/main/resources/archetype-resources/README.md
archetypes/business-service-pojo/src/main/resources/archetype-resources/src/main/resources/microservice.yaml
archetypes/business-service-spring-boot-starter/README.md
archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/README.md
archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/src/main/resources/microservice.yaml
archetypes/business-service-springmvc/README.md
archetypes/business-service-springmvc/src/main/resources/archetype-resources/README.md
archetypes/business-service-springmvc/src/main/resources/archetype-resources/src/main/resources/microservice.yaml
etc/releaseNotes.md
parent/pom.xml
pom.xml
samples/auth-sample/README.md
samples/bmi/README.md
samples/codefirst-sample/README.md
samples/config-apollo-sample/README.md
samples/custom-handler-sample/README.md
samples/jaxrs-sample/README.md
samples/pojo-sample/README.md
samples/springmvc-sample/README.md

---
Incubator-ServiceComb-Java-Chassis -> ServiceComb-Java-Chassis

[SCB-973] update ServiceComb-java-chassis repo name

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java

[SCB-1020]No need unregister when bootup failure before register service

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestCodec.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/AbstractParamProcessor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/CookieProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/FormProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/PathProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/QueryProcessorCreator.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestCookieProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestFormProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestHeaderProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestPathProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestQueryProcessor.java
demo/demo-schema/src/main/resources/microservices/pojo/server.yaml
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/SpringMvcDefaultValues.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestAnnotatedAttribute.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultValue.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/AnnotatedAttributeSpringmvcSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DefaultValueSpringmvcSchema.java
integration-tests/springmvc-tests/springmvc-tests-common/src/test/java/org/apache/servicecomb/demo/springmvc/tests/SpringMvcIntegrationTestBase.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/parameter/AbstractParameterProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/CookieValueAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestHeaderAnnotationProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/annotation/RequestParamAnnotationProcessor.java

[SCB-925] Springmvc, when have defaultValue, required should be false, when param not exist, should check isRequired

---

core/src/main/java/org/apache/servicecomb/core/definition/schema/ConsumerSchemaFactory.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/client/http/TestServiceRegistryClientImpl.java

[SCB-1063]Improve the time cost when first time loading schema

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/main/java/org/apache/servicecomb/core/definition/OperationMeta.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/ProviderQpsFlowControlHandler.java
handlers/handler-flowcontrol-qps/src/main/java/org/apache/servicecomb/qps/QpsController.java
handlers/handler-flowcontrol-qps/src/test/java/org/apache/servicecomb/qps/TestProviderQpsFlowControlHandler.java

---
See details in [SCB-1056](https://issues.apache.org/jira/browse/SCB-1056)

[SCB-1056] put provider flow control logic in front

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/TestRestOperationMeta.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDownload.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DownloadSchema.java

[SCB-1054]when download file, we should ignore consumer acceptType

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/context/InvocationContext.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/swagger/invocation/context/TestInvocationContext.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayCodec.java
transports/transport-highway/src/test/java/org/apache/servicecomb/transport/highway/TestHighwayCodec.java

[SCB-1065] when request not contain traceId,should use provider's invocation's traceId

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestExceptionConvertEdge.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/converter/CustomException.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/converter/CustomExceptionConverter.java
integration-tests/it-edge/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.invocation.exception.ExceptionToProducerResponseConverter
integration-tests/it-edge/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/EdgeExceptionConvertSchema.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-1060]edge support Exception converter

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/event/IsolationServerEvent.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java

[SCB-1068] add the instance infomation into instance isolation event

---

demo/demo-edge/business-1.0.0/pom.xml
demo/demo-jaxrs/jaxrs-server/pom.xml
demo/demo-multiple/multiple-client/pom.xml
demo/demo-multiple/multiple-server/pom.xml
demo/demo-multiple/pom.xml
demo/demo-pojo/pojo-client/pom.xml
demo/demo-pojo/pojo-server/pom.xml
demo/demo-spring-boot-discovery/demo-spring-boot-discovery-client/pom.xml
demo/demo-spring-boot-transport/demo-spring-boot-pojo-server/pom.xml
demo/demo-springmvc/springmvc-client/pom.xml
demo/pom.xml
integration-tests/it-producer-deploy-springboot2-standalone/pom.xml
integration-tests/pom.xml
integration-tests/spring-pojo-connection-limit-test/pom.xml
integration-tests/spring-pojo-tests/pom.xml
integration-tests/springmvc-tests/springmvc-tests-general-with-springboot/pom.xml
java-chassis-dependencies-springboot2/pom.xml
java-chassis-dependencies/pom.xml
samples/apm-agent/pom.xml
samples/local-service-registry/local-registry-server/pom.xml
samples/pom.xml

[SCB-1072]change dependency management version to project.version

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterConfig.java
dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/client/TestConfigCenterConfig.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/InstanceCacheChecker.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/TestInstanceCacheChecker.java

---
See details in [SCB-1073](https://issues.apache.org/jira/browse/SCB-1073)

[SCB-1073] InstanceCacheChecker should ignore StaticMicroserviceVersions

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-1076]upgrade guava to 25.1

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-1077]upgrade hystrix to 1.5.12

---

java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-1075]upgrade spring-framework to 4.3.20.RELEASE

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestCodec.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/AddressResolverConfig.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceWatchTask.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/exception/ExceptionToProducerResponseConverters.java

[SCB-1074]minor fixes for mistakes and logs

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalancer.java

[SCB-1080]Add a log while get empty server list
---

[SCB-1080]Add a log while get empty server list

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/event/IsolationServerEvent.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java

[SCB-1088] SDK IsolationServerEvent is missing endpoint information

---

handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestWeightedResponseTimeRuleExt.java

[SCB-1083]fix ut random fail on slow machine

---

dynamic-config/config-apollo/src/main/java/org/apache/servicecomb/config/client/ApolloClient.java
dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/event/SimpleSubscriber.java
foundations/foundation-metrics/src/main/java/org/apache/servicecomb/foundation/metrics/MetricsBootstrap.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/InstanceCacheChecker.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/RemoteServiceRegistry.java

[SCB-1095]Timer task need catch all throwable to protected from unexpected error

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestCodec.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestCodec.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestAnnotatedAttribute.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/EmptyScheam.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/SwaggerUtils.java

[CB-1102]fix empty swagger and information leak problem

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/HeaderProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/QueryProcessorCreator.java

[SCB-925]allow disable required check for a while

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/DefaultRetryExtensionsFactory.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestDefaultRetryhandler.java

[SCB-1105] NoRouteToHostException, should allow all error message

---

transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/HttpStatusItem.java
transports/transport-rest/transport-rest-vertx/src/test/java/org/apache/servicecomb/transport/rest/vertx/accesslog/element/impl/HttpStatusItemTest.java

[SCB-1108]when timeout, the access log status is 200

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/discovery/InstanceStatusDiscoveryFilter.java

[SCB-1104]fix review comments
---

[SCB-1106]isolation must make sure one of instances is available

---

core/src/test/java/org/apache/servicecomb/core/transport/TestAbstractTransport.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/net/NetUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/net/TestNetUtils.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/RegistryUtils.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java

---
Currently our IP address parsing logic cannot work properly in IPv6 environment

[SCB-1101] support IPv6 address format

---

handlers/handler-tracing-zipkin/pom.xml
handlers/handler-tracing-zipkin/src/main/java/org/apache/servicecomb/tracing/zipkin/TracingConfiguration.java
integration-tests/pom.xml
integration-tests/spring-zuul-tracing-tests/pom.xml
integration-tests/test-common/pom.xml
integration-tests/test-common/src/test/java/org/apache/servicecomb/tests/tracing/TraceContextConfig.java
integration-tests/test-common/src/test/java/org/apache/servicecomb/tests/tracing/TracingTestBase.java
integration-tests/tracing-tests/pom.xml
java-chassis-dependencies/pom.xml
java-chassis-distribution/src/release/LICENSE
java-chassis-spring-boot/spring-boot-starter/spring-cloud-zuul-zipkin/pom.xml
tracing/tracing-zipkin/src/test/java/org/apache/servicecomb/tracing/zipkin/ZipkinSpanAspectTest.java
tracing/tracing-zipkin/src/test/java/org/apache/servicecomb/tracing/zipkin/ZipkinTracingAdviserTest.java

[SCB-1114]upgrade zipkin

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestClientRequest.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/FormProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/param/TestRestClientRequestImpl.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerRequestToHttpServletRequest.java
integration-tests/it-common/src/main/resources/logback.xml
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestUpload.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/UploadJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/UploadSpringmvcSchema.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CommonToHttpServletRequest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestCommonToHttpServletRequest.java
swagger/swagger-generator/generator-core/pom.xml
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/CommonParameterTypeProcessor.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/OperationGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/parametertype/HttpServletRequestProcessor.java
swagger/swagger-generator/generator-springmvc/pom.xml
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/parameter/MultipartFileArrayTypeProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/processor/parameter/MultipartFileListTypeProcessor.java
swagger/swagger-generator/generator-springmvc/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.generator.core.CommonParameterTypeProcessor
swagger/swagger-invocation/invocation-core/pom.xml
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/converter/ConverterMgr.java
swagger/swagger-invocation/invocation-springmvc/pom.xml
swagger/swagger-invocation/invocation-springmvc/src/main/java/org/apache/servicecomb/swagger/invocation/converter/SpringMultipartArrayConverter.java
swagger/swagger-invocation/invocation-springmvc/src/main/java/org/apache/servicecomb/swagger/invocation/converter/SpringMultipartListConverter.java

[SCB-1046] file upload support file array for the same name

---

archetypes/business-service-jaxrs/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-jaxrs/src/main/resources/archetype-resources/src/main/java/Application.java
archetypes/business-service-jaxrs/src/main/resources/archetype-resources/src/main/java/HelloConsumer.java
archetypes/business-service-jaxrs/src/main/resources/archetype-resources/src/main/java/HelloImpl.java
archetypes/business-service-jaxrs/src/main/resources/archetype-resources/src/main/resources/log4j2.xml
archetypes/business-service-pojo/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-pojo/src/main/resources/archetype-resources/src/main/java/Application.java
archetypes/business-service-pojo/src/main/resources/archetype-resources/src/main/java/Hello.java
archetypes/business-service-pojo/src/main/resources/archetype-resources/src/main/java/HelloConsumer.java
archetypes/business-service-pojo/src/main/resources/archetype-resources/src/main/java/HelloImpl.java
archetypes/business-service-pojo/src/main/resources/archetype-resources/src/main/resources/log4j2.xml
archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/src/main/java/Application.java
archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/src/main/java/HelloConsumer.java
archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/src/main/java/HelloImpl.java
archetypes/business-service-springmvc/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-springmvc/src/main/resources/archetype-resources/src/main/java/Application.java
archetypes/business-service-springmvc/src/main/resources/archetype-resources/src/main/java/HelloConsumer.java
archetypes/business-service-springmvc/src/main/resources/archetype-resources/src/main/java/HelloImpl.java
archetypes/business-service-springmvc/src/main/resources/archetype-resources/src/main/resources/META-INF/spring/provider.bean.xml
archetypes/business-service-springmvc/src/main/resources/archetype-resources/src/main/resources/log4j2.xml

Signed-off-by: MabinGo <bin.ma@huawei.com>
---

[SCB-1126] springmvc project generated by ServiceComb scaffold can not run

---

foundations/foundation-test-scaffolding/src/main/java/org/apache/servicecomb/foundation/test/scaffolding/model/Media.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodec.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodecEdge.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ParamCodecSchema.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ModelResolverExt.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/introspector/JsonPropertyIntrospector.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/module/EnumModuleExt.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/extend/introspector/JsonPropertyIntrospectorTest.java
swagger/swagger-generator/generator-core/src/test/java/org/apache/servicecomb/swagger/extend/module/EnumModuleExtTest.java

---
See details in [SCB-1129](https://issues.apache.org/jira/browse/SCB-1129)

[SCB-1129] Fix @JsonProperty problem in enum param

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestVertxTransportConfig.java
integration-tests/it-consumer/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/RestVertxTransportConfigSchema.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestTransportClientConfig.java

---
See details in [SCB-1135](https://issues.apache.org/jira/browse/SCB-1135)
A config item `servicecomb.rest.client.maxHeaderSize` is provided.

[SCB-1135] Add client receive header size config

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/WebsocketUtils.java

[SCB-1143]Servicecomb support watch service center with auth headers

---

core/src/main/java/org/apache/servicecomb/core/CseApplicationListener.java
core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
core/src/main/java/org/apache/servicecomb/core/definition/MicroserviceMeta.java
core/src/main/java/org/apache/servicecomb/core/definition/OperationConfig.java
core/src/main/java/org/apache/servicecomb/core/definition/OperationMeta.java
core/src/test/java/org/apache/servicecomb/core/definition/TestMicroserviceMeta.java
core/src/test/java/org/apache/servicecomb/core/definition/TestOperationMeta.java
metrics/metrics-core/pom.xml
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/MetricsBootListener.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/SlowInvocationLogger.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestSlowInvocationLogger.java

- support global/service/schema/operation level configuration
- support enabled and time configuration
- enabled default to be false
- time default to be 1000 millisecond

[SCB-1147] Log slow invocation stage trace information

---

java-chassis-distribution/src/release/LICENSE
java-chassis-spring-boot/spring-boot2-starter-parent/pom.xml
java-chassis-spring-boot/spring-boot2-starter-parent/spring-boot2-starter-gateway/pom.xml

- Add spring-boot2-starter-gateway module to support spring-cloud-gateway 2.0.0.RELEASE in java-chassis. 
- spring-boot2-starter-gateway support 3rd invoke internal microservice by spring-cloud-gateway. 
- The  compile and function test is OK.
---

[#1085] Support spring-cloud-gateway

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/deploy/NormalDeploy.java
java-chassis-spring-boot/spring-boot-starter/spring-boot-starter-discovery/pom.xml
java-chassis-spring-boot/spring-boot2-starter-parent/spring-boot2-starter-discovery/pom.xml
java-chassis-spring-boot/spring-boot2-starter-parent/spring-boot2-starter-gateway/pom.xml

[SCB-1157]Remove discovery's dependence on zuul

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/SwaggerGenerator.java

[SCB-1165] skip bridge method when generate operation swagger

---

foundations/foundation-config/src/test/java/org/apache/servicecomb/config/inject/TestConfigObjectFactory.java

[SCB-1178]In the unit test, the issue of assertEquals and Float.MAX_VALUE.

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterClient.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RestUtils.java

---
Add some log to help locate DNS problem.

[SCB-1185] add DNS related error log

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/response/DefaultResponseTypeProcessor.java

The related description at https://github.com/apache/servicecomb-java-chassis/issues/1122

[SCB-1191] fix the bug of latest DefaultResponseTypeProcessor

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/BeanUtils.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/JvmUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/TestBeanUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/TestJvmUtils.java

[SCB-1179]Optimize the mainclass auto-discovery logic to cover more scenes.

---

metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/SlowInvocationLogger.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestSlowInvocationLogger.java

[SCB-1147] fix slow invocation log problem

---

foundations/foundation-test-scaffolding/pom.xml
java-chassis-dependencies/default/pom.xml
java-chassis-spring-boot/spring-boot-common/pom.xml
java-chassis-spring-boot/spring-boot-starter/pom.xml
java-chassis-spring-boot/spring-boot2-starter-parent/pom.xml
parents/default/pom.xml
parents/spring4/pom.xml
parents/spring5/pom.xml
parents/springboot1/pom.xml
parents/springboot2/pom.xml
pom.xml

[SCB-1193]fix review comments and spring-boot-common parent error

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/URLPathBuilder.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/path/URLPathBuilderTest.java

---
See details in [SCB-1220](https://issues.apache.org/jira/browse/SCB-1220)

[SCB-1220] consumer side support path param regex

---

archetypes/business-service-spring-boot-starter/src/main/resources/archetype-resources/pom.xml

[SCB-1222] change groupId of "hibernate-validator" from "org.hibernate" to "org.hibernate.validator" to avoid dependency warning

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/ZoneAwareDiscoveryFilter.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java

[SCB-1224] az affinity is conflict with empty instance protection

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapperFactory.java
coverage-reports/pom.xml
java-chassis-dependencies/default/pom.xml
java-chassis-distribution/pom.xml
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ConcreteInterfaceRegister.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/extend/ModelResolverExt.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/SwaggerGeneratorUtils.java
swagger/swagger-generator/generator-spring-data/pom.xml
swagger/swagger-generator/generator-spring-data/src/main/java/org/apache/servicecomb/swagger/generator/springdata/PageResponseTypeProcessor.java
swagger/swagger-generator/generator-spring-data/src/main/java/org/apache/servicecomb/swagger/generator/springdata/SpringDataConcreteInterfaceRegister.java
swagger/swagger-generator/generator-spring-data/src/main/java/org/apache/servicecomb/swagger/generator/springdata/SpringDataModule.java
swagger/swagger-generator/generator-spring-data/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module
swagger/swagger-generator/generator-spring-data/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.extend.ConcreteInterfaceRegister
swagger/swagger-generator/generator-spring-data/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.generator.ResponseTypeProcessor
swagger/swagger-generator/generator-spring-data/src/test/java/org/apache/servicecomb/swagger/generator/springdata/TestPageResponseTypeProcessor.java
swagger/swagger-generator/generator-spring-data/src/test/resources/pageSchema.yaml

support generate model from Page interface and deserialize to page

[SCB-1242][WIP][WEAK] spring data plugin

---

edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/AbstractEdgeDispatcher.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/deploy/Deploys.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestServerConfigEdge.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/DemoDispatcherWithFailureHandler.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/DemoDispatcherWithoutFailureHandler.java
integration-tests/it-edge/src/main/resources/META-INF/services/org.apache.servicecomb.transport.rest.vertx.VertxHttpDispatcher
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/RestServerVerticle.java

---
[SCB-1253](https://issues.apache.org/jira/browse/SCB-1253)
- fix some problem in FailureHandler
- adjust the priority of `GlobalRestFailureHandler`
- read `-Xmx` config value from system property, like `-DSCB_IT_MAX_HEAP_SIZE=200m clean install -Pit`

[SCB-1253] Adjust priority of failure handler

---

edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeInvocation.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestEdgeInvocation.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodec.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodecEdge.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/context/InheritInvocationContextFilter.java
integration-tests/it-edge/src/main/resources/META-INF/services/org.apache.servicecomb.common.rest.filter.HttpServerFilter
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ParamCodecSchema.java

[SCB-1263] do not inherit InvocationContext from request header in edge

---

swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/SwaggerUtils.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/OperationGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/SwaggerGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractOperationGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/AbstractSwaggerGenerator.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/pojo/PojoSwaggerGenerator.java
swagger/swagger-generator/generator-jaxrs/src/main/java/org/apache/servicecomb/swagger/generator/jaxrs/JaxrsSwaggerGenerator.java
swagger/swagger-generator/generator-springmvc/src/main/java/org/apache/servicecomb/swagger/generator/springmvc/SpringmvcSwaggerGenerator.java

generate swagger depeond on this, so no need to write more UT

[SCB-1286][WIP][WEAK] support only generate response for a operation

---

edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/AbstractEdgeDispatcher.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/DefaultEdgeDispatcher.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedEdgeDispatcher.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestDispatcher.java

[SCB-1287]refactor edge dispatcher to make them more extensible

---

core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/main/java/org/apache/servicecomb/core/definition/OperationConfig.java
core/src/main/java/org/apache/servicecomb/core/provider/consumer/ReferenceConfig.java
core/src/main/java/org/apache/servicecomb/core/unittest/UnitTestMeta.java
core/src/test/java/org/apache/servicecomb/core/TestInvocation.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITSCBRestTemplate.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/thirdparty/Test3rdPartyInvocation.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeJaxrsSchema.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/Microservice.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/StaticMicroservice.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/consumer/StaticMicroserviceVersionsTest.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/http/TestRestClientInvocation.java

---
See details in [SCB-1278](https://issues.apache.org/jira/browse/SCB-1278)

[SCB-1278] Not send x-cse* header to third party service by default

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/Consumers.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITAsyncClientHttpRequest.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITAsyncClientHttpRequestFactory.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/extend/engine/ITSCBAsyncRestTemplate.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDefaultValue.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncClientHttpRequest.java
providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/async/CseAsyncRequestCallback.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestCseClientHttpRequest.java

[SCB-1305] CseAysncRestTemplate is not set headers

---

providers/provider-springmvc/src/main/java/org/apache/servicecomb/provider/springmvc/reference/CseClientHttpRequest.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestUrlWithProviderPrefixClientHttpRequestFactory.java
providers/provider-springmvc/src/test/java/org/apache/servicecomb/provider/springmvc/reference/TestUrlWithServiceNameClientHttpRequestFactory.java

[SCB-1289]restTemplate transmission parameter is empty protection

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestApiOperationOverride.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ApiOperationJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ApiOperationSpringmvcSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/ApiOpertionPojoSchema.java
providers/provider-pojo/src/main/java/org/apache/servicecomb/provider/pojo/Invoker.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerEnvironment.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/unittest/LocalProducerInvoker.java

 [SCB-1291]supportApiOperationMethodOverride

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigurationSpringInitializer.java

[SCB-1297]Environment parsing failed to fix

---

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestTransportClientConfig.java

[SCB-1405] supporting maxWaitQueueSize setting in RestTransportClient

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/api/registry/MicroserviceInstance.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/InstanceCacheChecker.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/InstanceCacheResult.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceInstanceRegisterTask.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/TestInstanceCacheChecker.java

[SCB-1407] Add new field when print provideCache log

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalancer.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServer.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombServerStats.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilter.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/filter/IsolationDiscoveryFilterTest.java

---
See details in [SCB-1308](https://issues.apache.org/jira/browse/SCB-1308)

[SCB-1308] improve instance isolation recovery mechanism

---

java-chassis-dependencies/default/pom.xml
java-chassis-dependencies/spring4/pom.xml
java-chassis-dependencies/spring5/pom.xml
java-chassis-dependencies/springboot1/pom.xml
java-chassis-dependencies/springboot2/pom.xml

[SCB-1431] set all dependency versions as properties

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigurationSpringInitializer.java
foundations/foundation-config/src/test/java/org/apache/servicecomb/config/TestConfigurationSpringInitializer.java

…vicecomb.config.ignoreResolveFailure
---

[SCB-1297] NPE would be arised if you haven't set any value for servicecomb.config.ignoreResolveFailure 

---

archetypes/business-service-spring-boot2-starter/README.md
archetypes/business-service-spring-boot2-starter/pom.xml
archetypes/business-service-spring-boot2-starter/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/README.md
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/pom.xml
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/src/main/java/Application.java
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/src/main/java/HelloConsumer.java
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/src/main/java/HelloImpl.java
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/src/main/resources/application.yaml
archetypes/business-service-spring-boot2-starter/src/main/resources/archetype-resources/src/main/resources/microservice.yaml
archetypes/pom.xml

[SCB-1434] add a springboot2 archetype

---

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
core/src/main/java/org/apache/servicecomb/core/bootup/AddressInformationCollector.java
core/src/main/java/org/apache/servicecomb/core/bootup/BootUpInformationCollector.java
core/src/main/java/org/apache/servicecomb/core/bootup/ServiceInformationCollector.java
core/src/main/resources/META-INF/services/org.apache.servicecomb.core.bootup.BootUpInformationCollector

[SCB-1451] Printing the service information on the log

---

handlers/handler-publickey-auth/src/main/java/org/apache/servicecomb/authentication/provider/RSAProviderTokenManager.java
handlers/handler-publickey-auth/src/test/java/org/apache/servicecomb/authentication/TestRSAProviderTokenManager.java

[SCB-1318]RSAProviderTokenManager#validatedToken expired resource recycling

---

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/ProtobufManager.java

[SCB-1457] delete no use code in ProtobufManager

---

java-chassis-dependencies/default/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-1488] Upgrading protobuf version to 3.7.1

---

.travis.yml
scripts/travis.sh

[SCB-1515]use jdk 8 compiler for java-chassis

---

java-chassis-dependencies/default/pom.xml

[SCB-1516] Upgrading third-party dependency versions

---

handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java

The UTs of `TestLoadBalanceHandler2` rely on `Thread#sleep` to simulate time elapsing. But this operation is not so accurate, which may cause UT failures.
So I mock the method `System#currentTimeMillis` to replace the thread sleep operation.

[SCB-1388] fix random failure in TestLoadBalanceHandler2

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java

[SCB-1494] Optimizing log when starting a new microservice
---

[SCB-1494] Optimizing log when starting a new microservice

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java

[SCB-1523] Stopping retrying another server when no server available

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java

[SCB-1489] Use old instanceId to re-register instance to service center

---

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/task/MicroserviceRegisterTask.java

[SCB-1524]support register schema when old schema already exists

---

metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/DefaultLogPublisher.java

[SCB-1544]default metrics printer should not print 0 operations

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/RestConst.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestCodec.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/engine/SwaggerProducerOperation.java

[SCB-1525]print codec error stack

---

samples/bmi/calculator/src/main/java/org/apache/servicecomb/samples/bmi/CalculatorServiceImpl.java

[SCB-1546] fix wrong code for sample

---

client/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java
client/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterRawClient.java
client/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/exception/OperationException.java
client/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/http/HttpRequest.java
client/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/http/HttpTransport.java
client/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/http/HttpTransportImpl.java
client/service-center-client/src/test/java/org/apache/servicecomb/service/center/client/HttpTransportImplTest.java
client/service-center-client/src/test/java/org/apache/servicecomb/service/center/client/ServiceCenterRawClientTest.java

This PR completes some optimizations of service-center-client:
1. Set the tenantName to a customizable parameter.
2. Optimize HttpClient layer code
3. Throw an exception instead of output error log

[SCB-1571]set tenantName parameter and add exceptions handle

---

client/kie-client/README.md

To help users use the Kie-client more easily, add a README to the Kie-client.

[SCB-1574] Add README for Kie-Client

---

client/service-center-client/README.md

To help users use the service-center-client more easily, add a README to the service-center-client.

[SCB-1575] Add README for Service-Center-Client

---

java-chassis-dependencies/default/pom.xml

[SCB-1582] Delete unused thirdparty dependencies

---

core/src/main/java/org/apache/servicecomb/core/bootup/AddressInformationCollector.java
core/src/main/java/org/apache/servicecomb/core/bootup/ServiceInformationCollector.java

[SCB-1557] Fix application start info log incorrect

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadBalancer.java

[SCB-1588]ServerListFilterExt add switch

---

java-chassis-dependencies/default/pom.xml
java-chassis-distribution/src/release/LICENSE

[SCB-1582] Upgrading thirdParty dependency versions

---

core/src/main/java/org/apache/servicecomb/core/SCBEngine.java

[SCB-1601]Abandon waiting 30 seconds after waiting request timeout.

---

handlers/handler-router/pom.xml
handlers/handler-router/src/main/java/org/apache/servicecomb/router/RouterFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/cache/RouterRuleCache.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/constom/CanaryInvokeFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/constom/CanaryServerListFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/constom/MicroserviceCache.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/constom/RouterInvokeFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/constom/RouterServerListFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/constom/ServiceCombCanaryDistributer.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/distribute/AbstractRouterDistributor.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/distribute/RouterDistributor.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/exception/RouterIllegalParamException.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/match/RouterHeaderFilterExt.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/match/RouterRuleMatcher.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/model/HeaderRule.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/model/Matcher.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/model/PolicyRuleItem.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/model/RouteItem.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/model/ServiceInfoCache.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/model/TagItem.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/util/VersionCompareUtil.java
handlers/handler-router/src/test/java/org/apache/servicecomb/router/RouterDistributorTest.java
handlers/handler-router/src/test/java/org/apache/servicecomb/router/VersionCompareUtilTest.java
handlers/pom.xml

[SCB-1407] Add gray release feature 

---

edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/DefaultEdgeDispatcher.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedConfigurationItem.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedConfigurationLoader.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedEdgeDispatcher.java
edge/edge-core/src/test/java/org/apache/servicecomb/edge/core/TestURLMappedEdgeDispatcher.java
transports/transport-rest/transport-rest-vertx/src/main/java/org/apache/servicecomb/transport/rest/vertx/VertxRestDispatcher.java

[SCB-1616]refactor edge dispatcher to make them more extensible

---

demo/demo-springmvc/springmvc-client/src/main/resources/microservice.yaml
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/ServiceRegistryClientImpl.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/WebsocketUtils.java

[SCB-1638]servicecenter do not handle websocket PING/PONG message

---

handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/MicroserviceCache.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/RouterHeaderFilterExt.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/RouterInvokeFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/RouterServerListFilter.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/custom/ServiceCombCanaryDistributer.java
handlers/handler-router/src/main/java/org/apache/servicecomb/router/match/RouterRuleMatcher.java

[SCB-1407] handler-router decoupled spi/rename package

---

foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigUtil.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/archaius/sources/ConfigModel.java

[SCB-1407] delete sensitive log

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/ResourceUtil.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/ResourceUtilsTest.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/swagger/SwaggerLoader.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/swagger/TestSwaggerLoader.java

To load the resource files without the help of Spring dependencies.

[SCB-1636] Add ResourceUtils for resource loading

---

coverage-reports/pom.xml
handlers/handler-router/src/main/resources/META-INF/services/org.apache.servicecomb.common.rest.filter.HttpServerFilter
handlers/handler-router/src/main/resources/META-INF/services/org.apache.servicecomb.loadbalance.ServerListFilterExt
java-chassis-dependencies/default/pom.xml
java-chassis-distribution/pom.xml
solutions/solution-basic/pom.xml

[SCB-1407] router add spi config file/add to dependencies

---

clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/ServiceCenterClient.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/GetSchemaResponse.java
clients/service-center-client/src/main/java/org/apache/servicecomb/service/center/client/model/SchemaInfo.java
clients/service-center-client/src/test/java/org/apache/servicecomb/service/center/client/ServiceCenterClientTest.java

#1423  add service center schemas related API in service-center-client

[SCB-1697] Add schema API in service-center-client

---

demo/demo-schema/pom.xml
foundations/foundation-common/pom.xml
integration-tests/pom.xml
java-chassis-dependencies/default/pom.xml
java-chassis-distribution/src/release/LICENSE
java-chassis-spring-boot/java-chassis-spring-boot-starters/java-chassis-spring-boot-starter-servlet/pom.xml
swagger/swagger-generator/generator-core/pom.xml
transports/transport-rest/transport-rest-servlet/pom.xml

[SCB-1705] Update javax.servlet to jakarta.servlet

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/CustomLoadbalanceExtensionsFactory.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/ConfigMapping.java
foundations/foundation-config/src/main/resources/mapping.yaml
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/Configuration.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/DefaultRetryExtensionsFactory.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ExtensionsManager.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/RuleNameExtentionsFactory.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/ServiceCombLoadBalancerStats.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestConfiguration.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalancer.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestServiceCombLoadBalancerStats.java

[SCB-1716] Fix high cpu load when there are too many instances

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/RestClientRequestImpl.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/ReadStreamPart.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/http/VertxServerResponseToHttpServletResponse.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpCommon.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/stream/PumpFromPart.java
foundations/foundation-vertx/src/test/java/org/apache/servicecomb/foundation/vertx/http/TestVertxServerResponseToHttpServletResponse.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-1717] Fix returning nothing when file upload execption occurs

---

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/internal/converter/SwaggerToProtoGenerator.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClient.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestWeakPojo.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/WeakPojo.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CategorizedTestCaseRunner.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/server/GenericsModel.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/WeakSpringmvc.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/DeserializerSchemaManager.java

[SCB-1722]add generics test case and fix know problems

---

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/OperationProtobuf.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/RequestRootDeserializer.java
common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/ResponseRootDeserializer.java
common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/internal/converter/TestSchemaMetaCodec.java
common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/internal/converter/TestSchemaMetaCodecRestTemplate.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestWeakPojo.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/CodeFirstRestTemplateSpringmvc.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestObject.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestResponse.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestRestTemplate.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/ProtoUtils.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/any/AnyEntrySchema.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/any/AnySchema.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/DeserializerSchemaManager.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/repeated/impl/AnyRepeatedReadSchemas.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/SerializerSchemaManager.java
foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/internal/schema/TestAnySchema.java
foundations/foundation-test-scaffolding/src/main/java/org/apache/servicecomb/foundation/test/scaffolding/model/People.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayCodec.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/message/ResponseHeader.java
transports/transport-highway/src/main/resources/LoginRequest.proto
transports/transport-highway/src/main/resources/LoginResponse.proto
transports/transport-highway/src/main/resources/RequestHeader.proto
transports/transport-highway/src/main/resources/ResponseHeader.proto

[SCB-1727]support encode/decode Object(Any) types

---

core/src/main/java/org/apache/servicecomb/core/Invocation.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/SpringmvcClient.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ControllerImpl.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/scalar/AbstractScalarReadSchemas.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/scalar/Int32ReadSchemas.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/scalar/StringReadSchemas.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/scalar/StringWriteSchemas.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayCodec.java

[SCB-1730]highway support primitive default values and convert char/byte/short

---

common/common-protobuf/src/main/java/org/apache/servicecomb/codec/protobuf/definition/ResponseRootDeserializer.java
common/common-protobuf/src/test/java/org/apache/servicecomb/codec/protobuf/definition/TestResponseRootDeserializer.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/JsonUtils.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/junit/ITJUnitUtils.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestDataTypePrimitive.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestParamCodec.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestJAXRSObjectParamType.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestRPCObjectParamType.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestSpringMVCObjectParamType.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/thirdparty/Test3rdPartyInvocation.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/weak/consumer/TestSpringmvcBasic.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/DataTypeJaxrsSchema.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/arguments/producer/ProducerBeanParamMapper.java

[SCB-1725]turn on integration tests of highway and fix known problems

---

handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/RandomRuleExt.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/WeightedResponseTimeRuleExt.java

[#1467]use ThreadLocalRandom instead of Random

---

demo/demo-jaxrs/jaxrs-client/src/main/java/org/apache/servicecomb/demo/jaxrs/client/JaxrsClient.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/converter/CustomExceptionConverter.java
integration-tests/it-edge/src/main/java/org/apache/servicecomb/it/edge/handler/ExceptionConvertHandler.java
transports/transport-highway/src/main/java/org/apache/servicecomb/transport/highway/HighwayClient.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-1623]when timeout, return 408 error code and message is timeout

---

LICENSE
java-chassis-distribution/src/release/LICENSE

[SCB-1625]update license for spring components

---

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/main/java/org/apache/servicecomb/core/SCBEngine.java
dynamic-config/config-cc/src/test/java/org/apache/servicecomb/config/client/TestConfigCenterClient.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/event/SimpleSubscriber.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/LambdaMetafactoryUtils.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/event/TestEventBus.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/event/TestEventManager.java
foundations/foundation-common/src/test/java/org/apache/servicecomb/foundation/common/utils/TestLambdaMetafactoryUtils.java
foundations/foundation-protobuf/src/test/java/org/apache/servicecomb/foundation/protobuf/internal/schema/scalar/TestEnumSchema.java
handlers/handler-bizkeeper/src/test/java/org/apache/servicecomb/bizkeeper/event/TestCircutBreakerEventNotifier.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadBalanceHandler2.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/registry/AbstractServiceRegistry.java

[SCB-1745]remove accessor modifier in reflection

---

foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/LambdaMetafactoryUtils.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/bean/SetterWrapper.java
foundations/foundation-config/src/main/java/org/apache/servicecomb/config/inject/ConfigObjectFactory.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/bean/BeanDescriptor.java

[SCB-1749] fix OperationConfig setter problem

---

dependencies/default/pom.xml
distribution/src/release/LICENSE
distribution/src/release/licenses/LICENSE-edl-v10
foundations/foundation-common/pom.xml
parents/default/pom.xml

[SCB-1755]add JavaBeans Activation Framework implicitly

---

coverage-reports/pom.xml
dependencies/default/pom.xml
distribution/pom.xml
dynamic-config/config-kie/pom.xml
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/archaius/sources/KieConfigurationSourceImpl.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/ConnFailEvent.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/ConnSuccEvent.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieConfig.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieUtil.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieWatcher.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/KVBody.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/KVDoc.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/KVResponse.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/LabelDocResponse.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/ValueType.java
dynamic-config/config-kie/src/main/resources/META-INF/services/org.apache.servicecomb.config.spi.ConfigCenterConfigurationSource
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/client/TestKieClient.java
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/client/TestKieConfig.java
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/client/TestKieWatcher.java
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/sources/TestKieConfigurationSource.java
dynamic-config/config-kie/src/test/resources/microservice.yaml
handlers/handler-router/pom.xml

(cherry picked from commit 833af5050ca3e26e75b327b499b0f9534f55d8b6)
---

[SCB-1711] support kie

---

swagger/swagger-invocation/invocation-validator/src/main/java/org/apache/servicecomb/swagger/invocation/validator/ParameterValidator.java

[SCB-1472] Allow users to disable the param validation by configuration

---

dynamic-config/config-nacos/src/main/java/org/apache/servicecomb/config/nacos/client/NacosConfig.java
dynamic-config/config-nacos/src/test/resources/microservice.yaml

[SCB-1767] adjust nacos config name

---

solutions/solution-basic/pom.xml

[SCB-1643] add a slution to integrate with huaweicloud

---

pom.xml

[SCB-1772] fix javadoc compile error

---

integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestVertxTransportConfig.java
spring-boot/spring-boot-starters/java-chassis-spring-boot-starter-servlet/src/main/java/org/apache/servicecomb/springboot2/starter/servlet/RestServletInitializer.java

[SCB-1785] Run java-chassis in spring boot with external tomcat

---

metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java

[SCB-1779] update servicecomb test cases to make run in MAC

---

common/common-rest/pom.xml
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapper.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/AbstractUrlParamWriter.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/path/PathVarParamWriter.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDateTimeSchema.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/DateTimeSchema.java
demo/demo-springmvc/springmvc-server/src/main/java/org/apache/servicecomb/demo/springmvc/server/ProducerTestsAfterBootup.java
demo/demo-springmvc/springmvc-server/src/main/resources/microservice.yaml

[SCB-1737] support ISO 8601 data and time (part1: REST)

---

common/common-rest/pom.xml
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapperFactory.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/fix/TestDoSFix.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/RestObjectMapperWithStringMapper.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestDateTimeSchema.java
foundations/foundation-common/pom.xml
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/AbstractRestObjectMapper.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/JsonUtils.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/RestObjectMapper.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/deserializer/scalar/Int64ReadSchemas.java
foundations/foundation-protobuf/src/main/java/org/apache/servicecomb/foundation/protobuf/internal/schema/serializer/scalar/Int64WriteSchemas.java

[SCB-1737] support ISO 8601 data and time (part2: HIGHWAY)

---

foundations/foundation-ssl/src/main/java/org/apache/servicecomb/foundation/ssl/TrustAllManager.java

add comment to warn it is not secure

---

dependencies/default/pom.xml
distribution/src/release/LICENSE

[SCB-1794] update the version of commons-beautils

---

core/src/main/java/org/apache/servicecomb/core/provider/producer/ProducerProviderManager.java
demo/demo-register-url-prefix/demo-register-url-prefix-client/pom.xml
demo/demo-register-url-prefix/demo-register-url-prefix-client/src/main/java/org/apache/servicecomb/demo/prefix/Application.java
demo/demo-register-url-prefix/demo-register-url-prefix-client/src/main/resources/application.yml
demo/demo-register-url-prefix/demo-register-url-prefix-client/src/test/java/org/apache/servicecomb/demo/prefix/RegisterUrlPrefixIT.java
demo/demo-register-url-prefix/demo-register-url-prefix-server/pom.xml
demo/demo-register-url-prefix/demo-register-url-prefix-server/src/main/java/org/apache/servicecomb/demo/prefix/PrefixApplication.java
demo/demo-register-url-prefix/demo-register-url-prefix-server/src/main/java/org/apache/servicecomb/demo/prefix/RegisterUrlPrefixEndpoint.java
demo/demo-register-url-prefix/demo-register-url-prefix-server/src/main/resources/application.yml
demo/demo-register-url-prefix/pom.xml
demo/pom.xml

[SCB-1799]add back servicecomb.service.registry.registerUrlPrefix

---

dependencies/default/pom.xml
distribution/src/release/LICENSE
dynamic-config/config-apollo/pom.xml
dynamic-config/config-apollo/src/main/java/org/apache/servicecomb/config/archaius/sources/ApolloConfigurationSourceImpl.java
dynamic-config/config-nacos/pom.xml
dynamic-config/config-nacos/src/main/java/org/apache/servicecomb/config/nacos/archaius/sources/NacosConfigurationSourceImpl.java
spring-boot/spring-boot-starters/java-chassis-spring-boot-starter-discovery/pom.xml
swagger/swagger-invocation/invocation-validator/pom.xml
swagger/swagger-invocation/invocation-validator/src/main/java/org/apache/servicecomb/swagger/invocation/validator/ParameterValidator.java

[SCB-1805]clear some unused 3rd party software

---

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieConfig.java

[SCB-1803] kie support long polling

---

core/src/main/java/org/apache/servicecomb/core/provider/consumer/InvokerUtils.java
demo/demo-crossapp/crossapp-client/src/main/java/org/apache/servicecomb/demo/crossapp/CrossappClient.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClient.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/TestWeakPojo.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/invoker/ClientModel.java
demo/demo-pojo/pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/invoker/TestInvokerEndpoint.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/invoker/InvokerEndpoint.java
demo/demo-pojo/pojo-server/src/main/java/org/apache/servicecomb/demo/pojo/server/invoker/ServerModel.java
demo/demo-spring-boot-transport/demo-spring-boot-pojo-client/src/main/java/org/apache/servicecomb/demo/pojo/client/PojoClientTest.java
demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestWeakSpringmvc.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/TestRegistryBase.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/TestInstanceCacheChecker.java

[SCB-1798]InvokerUtils support specify response type

---

integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/objectparams/QueryObjectModel.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/objectparams/TestSpringMVCObjectParamType.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/objectparams/SpringMVCObjectParamTypeSchema.java

[SCB-1793] add ut for weak kernel

---

transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/RestTransportClient.java

[SCB-1787]Http 2 idleTimeoutInSeconds is not used

---

service-registry/src/test/java/org/apache/servicecomb/serviceregistry/diagnosis/instance/TestInstanceCacheChecker.java

[SCB-1779]add some logs to help find random fail ut to find reasons

---

core/src/main/java/org/apache/servicecomb/core/Endpoint.java
core/src/test/java/org/apache/servicecomb/core/TestEndpoint.java

[SCB-1812]Endpoint add new constructor to support user defined transport

---

dependencies/default/pom.xml
distribution/pom.xml
distribution/src/assembly/bin.xml

[SCB-1814]binary release only include java-chassis artifacts

---

solutions/solution-basic/pom.xml

[SCB-1837]revert changes for SCB-1643, do not include huaweicloud jar

---

edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/DefaultEdgeClientFilter.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/EdgeAddHeaderClientFilter.java
edge/edge-core/src/main/java/org/apache/servicecomb/edge/core/URLMappedEdgeDispatcher.java
edge/edge-core/src/main/resources/META-INF/services/org.apache.servicecomb.common.rest.filter.HttpClientFilter
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/publicHeaders/TestPublicHeadersEdge.java
integration-tests/it-edge/src/main/resources/microservice.yaml
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/publicHeaders/EdgePublicHeadersJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/publicHeaders/EdgePublicHeadersSpringMVCSchema.java

[SCB-1832] Edge will lose public request headers

---

metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/ClientEndpointsLogPublisher.java
metrics/metrics-core/src/main/java/org/apache/servicecomb/metrics/core/publish/ServerEndpointsLogPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/TestVertxMetersInitializer.java

[SCB-1839] SDK metrics move remote to the last column

---

.travis.yml
scripts/travis.sh

[SCB-1835] travis CI do not need release/deploy when cut release version

---

core/src/main/java/org/apache/servicecomb/core/Invocation.java
core/src/main/java/org/apache/servicecomb/core/handler/impl/ProducerOperationHandler.java
handlers/handler-loadbalance/src/main/java/org/apache/servicecomb/loadbalance/LoadbalanceHandler.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/RestClientInvocation.java

[SCB-1154]invocation related log must invoke with marker

---

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieUtil.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/KVDoc.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/KVResponse.java
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/client/TestKieClient.java

[SCB-1851] config-kie: support enable property

---

demo/demo-edge/authentication/pom.xml
demo/demo-edge/authentication/src/main/resources/microservice.yaml
demo/demo-edge/business-1-1-0/pom.xml
demo/demo-edge/business-1-1-0/src/main/resources/microservice.yaml
demo/demo-edge/business-1.0.0/pom.xml
demo/demo-edge/business-1.0.0/src/main/resources/microservice.yaml
demo/demo-edge/business-2.0.0/pom.xml
demo/demo-edge/business-2.0.0/src/main/resources/microservice.yaml
demo/demo-edge/consumer/pom.xml
demo/demo-edge/consumer/src/test/java/org/apache/servicecomb/demo/edge/consumer/EdgeDemoIT.java
demo/demo-edge/edge-service/pom.xml
demo/demo-edge/edge-service/src/main/resources/microservice.yaml
demo/demo-edge/pom.xml
demo/docker-build-config/pom.xml
demo/docker-run-config-edge/pom.xml
demo/pom.xml
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestDefaultLogPublisher.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestThreadPoolPublishModelFactory.java

[SCB-1850]add demo-edge to integrations tests and run when build

---

README.md
README_ZH.md

[SCB-1853]fix problems in README.md

---

common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
core/src/test/java/org/apache/servicecomb/core/handler/impl/TestSimpleLoadBalanceHandler.java
handlers/handler-loadbalance/src/test/java/org/apache/servicecomb/loadbalance/TestLoadbalanceHandler.java
swagger/swagger-invocation/invocation-core/src/main/java/org/apache/servicecomb/swagger/invocation/exception/ExceptionFactory.java
swagger/swagger-invocation/invocation-core/src/test/java/org/apache/servicecomb/core/TestResponse.java

[SCB-1859] modify sdk error msg

---

dynamic-config/config-cc/src/main/java/org/apache/servicecomb/config/client/ConfigCenterConfig.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/ConfigKieHttpClientOptionsSPI.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieConfig.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieUtil.java
dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/model/ValueType.java
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/client/TestKieClient.java
dynamic-config/config-kie/src/test/java/org/apache/servicecomb/config/kie/client/TestKieUtil.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/VertxConst.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClientOptionsSPI.java
foundations/foundation-vertx/src/main/java/org/apache/servicecomb/foundation/vertx/client/http/HttpClients.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/client/http/RegistryHttpClientOptionsSPI.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfig.java
service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfigBuilder.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/HttpTransportHttpClientOptionsSPI.java

[SCB-1861] fix config kie value parsing errors

---

common/common-rest/src/main/java/org/apache/servicecomb/common/rest/AbstractRestInvocation.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/RestObjectMapperFactory.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/BodyProcessorCreator.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/param/ParamValueProcessor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceJsonProcessor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessor.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/codec/produce/ProduceProcessorManager.java
common/common-rest/src/main/java/org/apache/servicecomb/common/rest/definition/RestOperationMeta.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/TestAbstractRestInvocation.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/TestRestObjectMapper.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/produce/TestProduceJsonProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/produce/TestProduceProcessorManager.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/codec/produce/TestProduceTextPlainProcessor.java
common/common-rest/src/test/java/org/apache/servicecomb/common/rest/definition/TestRestOperationMeta.java
demo/demo-schema/src/main/java/org/apache/servicecomb/demo/CodeFirstRestTemplate.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/RegisterManager.java
foundations/foundation-common/src/main/java/org/apache/servicecomb/foundation/common/utils/RestObjectMapper.java
integration-tests/it-common/src/main/java/org/apache/servicecomb/it/schema/PersonViewModel.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/ConsumerMain.java
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestJsonView.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/JsonViewJaxrsSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/JsonViewPojoSchema.java
integration-tests/it-producer/src/main/java/org/apache/servicecomb/it/schema/JsonViewSpringmvcSchema.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/SwaggerConst.java
swagger/swagger-generator/generator-core/src/main/java/org/apache/servicecomb/swagger/generator/core/processor/parameter/JsonViewProcessor.java
swagger/swagger-generator/generator-core/src/main/resources/META-INF/services/org.apache.servicecomb.swagger.generator.ParameterProcessor
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/http/DefaultHttpClientFilter.java

[SCB-1828] Support @JSONVIEW 

---

service-registry/src/main/java/org/apache/servicecomb/serviceregistry/config/ServiceRegistryConfigBuilder.java
service-registry/src/test/java/org/apache/servicecomb/serviceregistry/config/TestServiceRegistryConfig.java
transports/transport-rest/transport-rest-client/src/main/java/org/apache/servicecomb/transport/rest/client/TransportClientConfig.java
transports/transport-rest/transport-rest-client/src/test/java/org/apache/servicecomb/transport/rest/client/TestTransportClientConfig.java

[SCB-1849]fix parameter default value not proper

---

demo/demo-springmvc/springmvc-client/src/main/java/org/apache/servicecomb/demo/springmvc/client/TestMaxHttpUrlLength.java
dependencies/default/pom.xml
integration-tests/it-consumer/src/main/java/org/apache/servicecomb/it/testcase/TestRestVertxTransportConfig.java
metrics/metrics-core/src/test/java/org/apache/servicecomb/metrics/core/publish/TestDefaultLogPublisher.java

[SCB-1867] dependency update: netty, from 4.1.45.Final to 4.1.47.Final

---

handlers/handler-router/src/main/java/org/apache/servicecomb/router/util/VersionCompareUtil.java
handlers/handler-router/src/test/java/org/apache/servicecomb/router/VersionCompareUtilTest.java

[SCB-1873] using Version to implement VersionCompareUtil

---

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieClient.java

[SCB-1863] toke the revision when pull from kie

---

deployment/src/main/java/org/apache/servicecomb/deployment/DefaultDeploymentProvider.java
deployment/src/test/java/org/apache/servicecomb/deployment/TestDeployment.java

Got `Failed to create SSL connection` error when HTTPS is used when the local service center is not setup for HTTPS connection. 
---

[SCB-1886]use http for default service center for dev environment

---

dynamic-config/config-kie/src/main/java/org/apache/servicecomb/config/kie/client/KieWatcher.java

(cherry picked from commit 08eaf304364111b5965bc21360f5222ab36f9de0)
---

[SCB-1861] fix bug when delete all config
